import { DTC } from '../../types/dtc.types';

export const B00XX_DTCS: DTC[] = [
  // Airbag/Restraints System (B0000-B0099)
  { code: "B0000", description: "Driver Airbag Circuit Malfunction" },
  { code: "B0001", description: "Driver Airbag Circuit Range/Performance" },
  { code: "B0002", description: "Driver Airbag Circuit Low Resistance" },
  { code: "B0003", description: "Driver Airbag Circuit High Resistance" },
  { code: "B0004", description: "Driver Airbag Circuit Open" },
  { code: "B0005", description: "Driver Airbag Circuit Short to Ground" },
  { code: "B0006", description: "Driver Airbag Circuit Short to Battery" },
  { code: "B0010", description: "Passenger Airbag Circuit Malfunction" },
  { code: "B0011", description: "Passenger Airbag Circuit Range/Performance" },
  { code: "B0012", description: "Passenger Airbag Circuit Low Resistance" },
  { code: "B0013", description: "Passenger Airbag Circuit High Resistance" },
  { code: "B0014", description: "Passenger Airbag Circuit Open" },
  { code: "B0015", description: "Passenger Airbag Circuit Short to Ground" },
  { code: "B0016", description: "Passenger Airbag Circuit Short to Battery" },
  { code: "B0020", description: "Left Side Airbag Circuit Malfunction" },
  { code: "B0021", description: "Left Side Airbag Circuit Range/Performance" },
  { code: "B0022", description: "Left Side Airbag Circuit Low Resistance" },
  { code: "B0023", description: "Left Side Airbag Circuit High Resistance" },
  { code: "B0024", description: "Left Side Airbag Circuit Open" },
  { code: "B0025", description: "Left Side Airbag Circuit Short to Ground" },
  { code: "B0026", description: "Left Side Airbag Circuit Short to Battery" },
  { code: "B0030", description: "Right Side Airbag Circuit Malfunction" },
  { code: "B0031", description: "Right Side Airbag Circuit Range/Performance" },
  { code: "B0032", description: "Right Side Airbag Circuit Low Resistance" },
  { code: "B0033", description: "Right Side Airbag Circuit High Resistance" },
  { code: "B0034", description: "Right Side Airbag Circuit Open" },
  { code: "B0035", description: "Right Side Airbag Circuit Short to Ground" },
  { code: "B0036", description: "Right Side Airbag Circuit Short to Battery" },
  { code: "B0040", description: "Left Curtain Airbag Circuit Malfunction" },
  { code: "B0041", description: "Left Curtain Airbag Circuit Range/Performance" },
  { code: "B0042", description: "Left Curtain Airbag Circuit Low Resistance" },
  { code: "B0043", description: "Left Curtain Airbag Circuit High Resistance" },
  { code: "B0044", description: "Left Curtain Airbag Circuit Open" },
  { code: "B0045", description: "Left Curtain Airbag Circuit Short to Ground" },
  { code: "B0046", description: "Left Curtain Airbag Circuit Short to Battery" },
  { code: "B0050", description: "Right Curtain Airbag Circuit Malfunction" },
  { code: "B0051", description: "Right Curtain Airbag Circuit Range/Performance" },
  { code: "B0052", description: "Right Curtain Airbag Circuit Low Resistance" },
  { code: "B0053", description: "Right Curtain Airbag Circuit High Resistance" },
  { code: "B0054", description: "Right Curtain Airbag Circuit Open" },
  { code: "B0055", description: "Right Curtain Airbag Circuit Short to Ground" },
  { code: "B0056", description: "Right Curtain Airbag Circuit Short to Battery" },
  { code: "B0060", description: "Seat Belt Pretensioner Driver Circuit Malfunction" },
  { code: "B0061", description: "Seat Belt Pretensioner Driver Circuit Range/Performance" },
  { code: "B0062", description: "Seat Belt Pretensioner Driver Circuit Low Resistance" },
  { code: "B0063", description: "Seat Belt Pretensioner Driver Circuit High Resistance" },
  { code: "B0064", description: "Seat Belt Pretensioner Driver Circuit Open" },
  { code: "B0065", description: "Seat Belt Pretensioner Driver Circuit Short to Ground" },
  { code: "B0066", description: "Seat Belt Pretensioner Driver Circuit Short to Battery" },
  { code: "B0070", description: "Seat Belt Pretensioner Passenger Circuit Malfunction" },
  { code: "B0071", description: "Seat Belt Pretensioner Passenger Circuit Range/Performance" },
  { code: "B0072", description: "Seat Belt Pretensioner Passenger Circuit Low Resistance" },
  { code: "B0073", description: "Seat Belt Pretensioner Passenger Circuit High Resistance" },
  { code: "B0074", description: "Seat Belt Pretensioner Passenger Circuit Open" },
  { code: "B0075", description: "Seat Belt Pretensioner Passenger Circuit Short to Ground" },
  { code: "B0076", description: "Seat Belt Pretensioner Passenger Circuit Short to Battery" },
  { code: "B0080", description: "Occupant Classification Sensor Circuit Malfunction" },
  { code: "B0081", description: "Occupant Classification Sensor Circuit Range/Performance" },
  { code: "B0082", description: "Occupant Classification Sensor Circuit Low" },
  { code: "B0083", description: "Occupant Classification Sensor Circuit High" },
  { code: "B0084", description: "Occupant Classification Sensor Circuit Intermittent" },
  { code: "B0090", description: "Crash Sensor Circuit Malfunction" },
  { code: "B0091", description: "Crash Sensor Circuit Range/Performance" },
  { code: "B0092", description: "Crash Sensor Circuit Low" },
  { code: "B0093", description: "Crash Sensor Circuit High" }
];