import { DTC } from '../../types/dtc.types';

export const B01XX_DTCS: DTC[] = [
  // HVAC System (B0100-B0199)
  { code: "B0100", description: "HVAC Control Module Internal Malfunction" },
  { code: "B0101", description: "HVAC Control Module Communication Error" },
  { code: "B0102", description: "HVAC Control Module Power Supply Low" },
  { code: "B0103", description: "HVAC Control Module Power Supply High" },
  { code: "B0110", description: "Ambient Temperature Sensor Circuit Malfunction" },
  { code: "B0111", description: "Ambient Temperature Sensor Circuit Range/Performance" },
  { code: "B0112", description: "Ambient Temperature Sensor Circuit Low" },
  { code: "B0113", description: "Ambient Temperature Sensor Circuit High" },
  { code: "B0114", description: "Ambient Temperature Sensor Circuit Intermittent" },
  { code: "B0120", description: "In-Cabin Temperature Sensor Circuit Malfunction" },
  { code: "B0121", description: "In-Cabin Temperature Sensor Circuit Range/Performance" },
  { code: "B0122", description: "In-Cabin Temperature Sensor Circuit Low" },
  { code: "B0123", description: "In-Cabin Temperature Sensor Circuit High" },
  { code: "B0124", description: "In-Cabin Temperature Sensor Circuit Intermittent" },
  { code: "B0130", description: "Solar Sensor Circuit Malfunction" },
  { code: "B0131", description: "Solar Sensor Circuit Range/Performance" },
  { code: "B0132", description: "Solar Sensor Circuit Low" },
  { code: "B0133", description: "Solar Sensor Circuit High" },
  { code: "B0134", description: "Solar Sensor Circuit Intermittent" },
  { code: "B0140", description: "Evaporator Temperature Sensor Circuit Malfunction" },
  { code: "B0141", description: "Evaporator Temperature Sensor Circuit Range/Performance" },
  { code: "B0142", description: "Evaporator Temperature Sensor Circuit Low" },
  { code: "B0143", description: "Evaporator Temperature Sensor Circuit High" },
  { code: "B0144", description: "Evaporator Temperature Sensor Circuit Intermittent" },
  { code: "B0150", description: "Blower Motor Control Circuit Malfunction" },
  { code: "B0151", description: "Blower Motor Control Circuit Low" },
  { code: "B0152", description: "Blower Motor Control Circuit High" },
  { code: "B0153", description: "Blower Motor Control Circuit Open" },
  { code: "B0160", description: "Mode Door Actuator Circuit Malfunction" },
  { code: "B0161", description: "Mode Door Actuator Circuit Range/Performance" },
  { code: "B0162", description: "Mode Door Actuator Circuit Low" },
  { code: "B0163", description: "Mode Door Actuator Circuit High" },
  { code: "B0164", description: "Mode Door Actuator Circuit Stall" },
  { code: "B0170", description: "Temperature Door Actuator Left Circuit Malfunction" },
  { code: "B0171", description: "Temperature Door Actuator Left Circuit Range/Performance" },
  { code: "B0172", description: "Temperature Door Actuator Left Circuit Low" },
  { code: "B0173", description: "Temperature Door Actuator Left Circuit High" },
  { code: "B0174", description: "Temperature Door Actuator Left Circuit Stall" },
  { code: "B0180", description: "Temperature Door Actuator Right Circuit Malfunction" },
  { code: "B0181", description: "Temperature Door Actuator Right Circuit Range/Performance" },
  { code: "B0182", description: "Temperature Door Actuator Right Circuit Low" },
  { code: "B0183", description: "Temperature Door Actuator Right Circuit High" },
  { code: "B0184", description: "Temperature Door Actuator Right Circuit Stall" },
  { code: "B0190", description: "Recirculation Door Actuator Circuit Malfunction" },
  { code: "B0191", description: "Recirculation Door Actuator Circuit Range/Performance" },
  { code: "B0192", description: "Recirculation Door Actuator Circuit Low" },
  { code: "B0193", description: "Recirculation Door Actuator Circuit High" },
  { code: "B0194", description: "Recirculation Door Actuator Circuit Stall" }
];