import { DTC } from '../../types/dtc.types';

export const B02XX_DTCS: DTC[] = [
  // Instrument Cluster (B0200-B0299)
  { code: "B0200", description: "Instrument Cluster Internal Malfunction" },
  { code: "B0201", description: "Instrument Cluster Communication Error" },
  { code: "B0202", description: "Instrument Cluster Power Supply Low" },
  { code: "B0203", description: "Instrument Cluster Power Supply High" },
  { code: "B0210", description: "Speedometer Circuit Malfunction" },
  { code: "B0211", description: "Speedometer Circuit Range/Performance" },
  { code: "B0212", description: "Speedometer Circuit Low" },
  { code: "B0213", description: "Speedometer Circuit High" },
  { code: "B0220", description: "Tachometer Circuit Malfunction" },
  { code: "B0221", description: "Tachometer Circuit Range/Performance" },
  { code: "B0222", description: "Tachometer Circuit Low" },
  { code: "B0223", description: "Tachometer Circuit High" },
  { code: "B0230", description: "Fuel Gauge Circuit Malfunction" },
  { code: "B0231", description: "Fuel Gauge Circuit Range/Performance" },
  { code: "B0232", description: "Fuel Gauge Circuit Low" },
  { code: "B0233", description: "Fuel Gauge Circuit High" },
  { code: "B0240", description: "Coolant Temperature Gauge Circuit Malfunction" },
  { code: "B0241", description: "Coolant Temperature Gauge Circuit Range/Performance" },
  { code: "B0242", description: "Coolant Temperature Gauge Circuit Low" },
  { code: "B0243", description: "Coolant Temperature Gauge Circuit High" },
  { code: "B0250", description: "Oil Pressure Gauge Circuit Malfunction" },
  { code: "B0251", description: "Oil Pressure Gauge Circuit Range/Performance" },
  { code: "B0252", description: "Oil Pressure Gauge Circuit Low" },
  { code: "B0253", description: "Oil Pressure Gauge Circuit High" },
  { code: "B0260", description: "Voltmeter Circuit Malfunction" },
  { code: "B0261", description: "Voltmeter Circuit Range/Performance" },
  { code: "B0262", description: "Voltmeter Circuit Low" },
  { code: "B0263", description: "Voltmeter Circuit High" },
  { code: "B0270", description: "Odometer Circuit Malfunction" },
  { code: "B0271", description: "Odometer Circuit Range/Performance" },
  { code: "B0272", description: "Odometer Circuit Low" },
  { code: "B0273", description: "Odometer Circuit High" },
  { code: "B0280", description: "Trip Odometer Circuit Malfunction" },
  { code: "B0281", description: "Trip Odometer Circuit Range/Performance" },
  { code: "B0282", description: "Trip Odometer Circuit Low" },
  { code: "B0283", description: "Trip Odometer Circuit High" },
  { code: "B0290", description: "Warning Indicator Circuit Malfunction" },
  { code: "B0291", description: "Warning Indicator Circuit Low" },
  { code: "B0292", description: "Warning Indicator Circuit High" },
  { code: "B0293", description: "Warning Indicator Circuit Open" }
];