import { DTC } from '../../types/dtc.types';

export const B03XX_DTCS: DTC[] = [
  // Power Windows (B0300-B0319)
  { code: "B0300", description: "Driver Window Motor Circuit Malfunction" },
  { code: "B0301", description: "Driver Window Motor Circuit Low" },
  { code: "B0302", description: "Driver Window Motor Circuit High" },
  { code: "B0303", description: "Driver Window Motor Circuit Stall" },
  { code: "B0304", description: "Passenger Window Motor Circuit Malfunction" },
  { code: "B0305", description: "Passenger Window Motor Circuit Low" },
  { code: "B0306", description: "Passenger Window Motor Circuit High" },
  { code: "B0307", description: "Passenger Window Motor Circuit Stall" },
  { code: "B0308", description: "Rear Left Window Motor Circuit Malfunction" },
  { code: "B0309", description: "Rear Left Window Motor Circuit Low" },
  { code: "B0310", description: "Rear Left Window Motor Circuit High" },
  { code: "B0311", description: "Rear Left Window Motor Circuit Stall" },
  { code: "B0312", description: "Rear Right Window Motor Circuit Malfunction" },
  { code: "B0313", description: "Rear Right Window Motor Circuit Low" },
  { code: "B0314", description: "Rear Right Window Motor Circuit High" },
  { code: "B0315", description: "Rear Right Window Motor Circuit Stall" },
  
  // Door Locks (B0320-B0339)
  { code: "B0320", description: "Driver Door Lock Actuator Circuit Malfunction" },
  { code: "B0321", description: "Driver Door Lock Actuator Circuit Low" },
  { code: "B0322", description: "Driver Door Lock Actuator Circuit High" },
  { code: "B0323", description: "Passenger Door Lock Actuator Circuit Malfunction" },
  { code: "B0324", description: "Passenger Door Lock Actuator Circuit Low" },
  { code: "B0325", description: "Passenger Door Lock Actuator Circuit High" },
  { code: "B0326", description: "Rear Left Door Lock Actuator Circuit Malfunction" },
  { code: "B0327", description: "Rear Left Door Lock Actuator Circuit Low" },
  { code: "B0328", description: "Rear Left Door Lock Actuator Circuit High" },
  { code: "B0329", description: "Rear Right Door Lock Actuator Circuit Malfunction" },
  { code: "B0330", description: "Rear Right Door Lock Actuator Circuit Low" },
  { code: "B0331", description: "Rear Right Door Lock Actuator Circuit High" },
  { code: "B0332", description: "Trunk/Hatch Lock Actuator Circuit Malfunction" },
  { code: "B0333", description: "Trunk/Hatch Lock Actuator Circuit Low" },
  { code: "B0334", description: "Trunk/Hatch Lock Actuator Circuit High" },
  
  // Lighting (B0340-B0359)
  { code: "B0340", description: "Headlight Control Circuit Malfunction" },
  { code: "B0341", description: "Headlight Control Circuit Low" },
  { code: "B0342", description: "Headlight Control Circuit High" },
  { code: "B0343", description: "Left Headlight Circuit Malfunction" },
  { code: "B0344", description: "Left Headlight Circuit Open" },
  { code: "B0345", description: "Left Headlight Circuit Short" },
  { code: "B0346", description: "Right Headlight Circuit Malfunction" },
  { code: "B0347", description: "Right Headlight Circuit Open" },
  { code: "B0348", description: "Right Headlight Circuit Short" },
  { code: "B0349", description: "Daytime Running Light Circuit Malfunction" },
  { code: "B0350", description: "Fog Light Circuit Malfunction" },
  { code: "B0351", description: "Turn Signal Circuit Malfunction" },
  { code: "B0352", description: "Brake Light Circuit Malfunction" },
  { code: "B0353", description: "Reverse Light Circuit Malfunction" },
  { code: "B0354", description: "License Plate Light Circuit Malfunction" },
  
  // Wipers (B0360-B0379)
  { code: "B0360", description: "Wiper Motor Circuit Malfunction" },
  { code: "B0361", description: "Wiper Motor Circuit Low" },
  { code: "B0362", description: "Wiper Motor Circuit High" },
  { code: "B0363", description: "Wiper Motor Park Switch Circuit Malfunction" },
  { code: "B0364", description: "Wiper Motor Park Switch Circuit Low" },
  { code: "B0365", description: "Wiper Motor Park Switch Circuit High" },
  { code: "B0366", description: "Wiper Relay Circuit Malfunction" },
  { code: "B0367", description: "Wiper Relay Circuit Low" },
  { code: "B0368", description: "Wiper Relay Circuit High" },
  { code: "B0369", description: "Washer Pump Circuit Malfunction" },
  { code: "B0370", description: "Washer Pump Circuit Low" },
  { code: "B0371", description: "Washer Pump Circuit High" },
  { code: "B0372", description: "Rain Sensor Circuit Malfunction" },
  { code: "B0373", description: "Rain Sensor Circuit Range/Performance" },
  { code: "B0374", description: "Rain Sensor Circuit Low" },
  { code: "B0375", description: "Rain Sensor Circuit High" },
  { code: "B0376", description: "Rain Sensor Circuit Intermittent" },
  
  // Seats (B0380-B0399)
  { code: "B0380", description: "Driver Seat Motor Circuit Malfunction" },
  { code: "B0381", description: "Driver Seat Motor Circuit Low" },
  { code: "B0382", description: "Driver Seat Motor Circuit High" },
  { code: "B0383", description: "Driver Seat Position Sensor Circuit Malfunction" },
  { code: "B0384", description: "Driver Seat Position Sensor Circuit Range/Performance" },
  { code: "B0385", description: "Driver Seat Position Sensor Circuit Low" },
  { code: "B0386", description: "Driver Seat Position Sensor Circuit High" },
  { code: "B0387", description: "Driver Seat Heater Circuit Malfunction" },
  { code: "B0388", description: "Driver Seat Heater Circuit Low" },
  { code: "B0389", description: "Driver Seat Heater Circuit High" },
  { code: "B0390", description: "Passenger Seat Motor Circuit Malfunction" },
  { code: "B0391", description: "Passenger Seat Motor Circuit Low" },
  { code: "B0392", description: "Passenger Seat Motor Circuit High" },
  { code: "B0393", description: "Passenger Seat Position Sensor Circuit Malfunction" },
  { code: "B0394", description: "Passenger Seat Position Sensor Circuit Range/Performance" },
  { code: "B0395", description: "Passenger Seat Position Sensor Circuit Low" },
  { code: "B0396", description: "Passenger Seat Position Sensor Circuit High" },
  { code: "B0397", description: "Passenger Seat Heater Circuit Malfunction" },
  { code: "B0398", description: "Passenger Seat Heater Circuit Low" },
  { code: "B0399", description: "Passenger Seat Heater Circuit High" }
];