import { DTC } from '../../types/dtc.types';

export const C00XX_DTCS: DTC[] = [
  { code: "C0000", description: "Vehicle Speed Information Circuit Malfunction" },
  { code: "C0001", description: "TCS Control Channel A Malfunction" },
  { code: "C0002", description: "TCS Control Channel B Malfunction" },
  { code: "C0003", description: "ABS Control Module Internal Malfunction" },
  { code: "C0004", description: "ABS Pump Motor Control Circuit Malfunction" },
  { code: "C0005", description: "ABS Pump Motor Speed Circuit Malfunction" },
  { code: "C0010", description: "Left Front Inlet Valve Control Circuit Malfunction" },
  { code: "C0011", description: "Left Front Inlet Valve Control Circuit Low" },
  { code: "C0012", description: "Left Front Inlet Valve Control Circuit High" },
  { code: "C0013", description: "Right Front Inlet Valve Control Circuit Malfunction" },
  { code: "C0014", description: "Right Front Inlet Valve Control Circuit Low" },
  { code: "C0015", description: "Right Front Inlet Valve Control Circuit High" },
  { code: "C0016", description: "Left Rear Inlet Valve Control Circuit Malfunction" },
  { code: "C0017", description: "Left Rear Inlet Valve Control Circuit Low" },
  { code: "C0018", description: "Left Rear Inlet Valve Control Circuit High" },
  { code: "C0019", description: "Right Rear Inlet Valve Control Circuit Malfunction" },
  { code: "C0020", description: "Right Rear Inlet Valve Control Circuit Low" },
  { code: "C0021", description: "Right Rear Inlet Valve Control Circuit High" },
  { code: "C0022", description: "Left Front Outlet Valve Control Circuit Malfunction" },
  { code: "C0023", description: "Left Front Outlet Valve Control Circuit Low" },
  { code: "C0024", description: "Left Front Outlet Valve Control Circuit High" },
  { code: "C0025", description: "Right Front Outlet Valve Control Circuit Malfunction" },
  { code: "C0026", description: "Right Front Outlet Valve Control Circuit Low" },
  { code: "C0027", description: "Right Front Outlet Valve Control Circuit High" },
  { code: "C0028", description: "Left Rear Outlet Valve Control Circuit Malfunction" },
  { code: "C0029", description: "Left Rear Outlet Valve Control Circuit Low" },
  { code: "C0030", description: "Left Rear Outlet Valve Control Circuit High" },
  { code: "C0031", description: "Right Rear Outlet Valve Control Circuit Malfunction" },
  { code: "C0032", description: "Right Rear Outlet Valve Control Circuit Low" },
  { code: "C0033", description: "Right Rear Outlet Valve Control Circuit High" },
  { code: "C0034", description: "Left Front Wheel Speed Sensor Circuit Malfunction" },
  { code: "C0035", description: "Left Front Wheel Speed Sensor Circuit Range/Performance" },
  { code: "C0036", description: "Left Front Wheel Speed Sensor Circuit Low Input" },
  { code: "C0037", description: "Left Front Wheel Speed Sensor Circuit High Input" },
  { code: "C0038", description: "Left Front Wheel Speed Sensor Circuit Intermittent" },
  { code: "C0039", description: "Right Front Wheel Speed Sensor Circuit Malfunction" },
  { code: "C0040", description: "Right Front Wheel Speed Sensor Circuit Range/Performance" },
  { code: "C0041", description: "Right Front Wheel Speed Sensor Circuit Low Input" },
  { code: "C0042", description: "Right Front Wheel Speed Sensor Circuit High Input" },
  { code: "C0043", description: "Right Front Wheel Speed Sensor Circuit Intermittent" },
  { code: "C0044", description: "Left Rear Wheel Speed Sensor Circuit Malfunction" },
  { code: "C0045", description: "Left Rear Wheel Speed Sensor Circuit Range/Performance" },
  { code: "C0046", description: "Left Rear Wheel Speed Sensor Circuit Low Input" },
  { code: "C0047", description: "Left Rear Wheel Speed Sensor Circuit High Input" },
  { code: "C0048", description: "Left Rear Wheel Speed Sensor Circuit Intermittent" },
  { code: "C0049", description: "Right Rear Wheel Speed Sensor Circuit Malfunction" },
  { code: "C0050", description: "Right Rear Wheel Speed Sensor Circuit Range/Performance" },
  { code: "C0051", description: "Right Rear Wheel Speed Sensor Circuit Low Input" },
  { code: "C0052", description: "Right Rear Wheel Speed Sensor Circuit High Input" },
  { code: "C0053", description: "Right Rear Wheel Speed Sensor Circuit Intermittent" },
  { code: "C0054", description: "Brake Fluid Level Sensor Circuit Malfunction" },
  { code: "C0055", description: "Brake Fluid Level Sensor Circuit Low" },
  { code: "C0056", description: "Brake Fluid Level Sensor Circuit High" },
  { code: "C0060", description: "Left Front ABS Solenoid Circuit Malfunction" },
  { code: "C0061", description: "Left Front ABS Solenoid Circuit Low" },
  { code: "C0062", description: "Left Front ABS Solenoid Circuit High" },
  { code: "C0063", description: "Right Front ABS Solenoid Circuit Malfunction" },
  { code: "C0064", description: "Right Front ABS Solenoid Circuit Low" },
  { code: "C0065", description: "Right Front ABS Solenoid Circuit High" },
  { code: "C0066", description: "Left Rear ABS Solenoid Circuit Malfunction" },
  { code: "C0067", description: "Left Rear ABS Solenoid Circuit Low" },
  { code: "C0068", description: "Left Rear ABS Solenoid Circuit High" },
  { code: "C0069", description: "Right Rear ABS Solenoid Circuit Malfunction" },
  { code: "C0070", description: "Right Rear ABS Solenoid Circuit Low" },
  { code: "C0071", description: "Right Rear ABS Solenoid Circuit High" },
  { code: "C0072", description: "Brake Pedal Position Sensor Circuit Malfunction" },
  { code: "C0073", description: "Brake Pedal Position Sensor Circuit Range/Performance" },
  { code: "C0074", description: "Brake Pedal Position Sensor Circuit Low" },
  { code: "C0075", description: "Brake Pedal Position Sensor Circuit High" },
  { code: "C0076", description: "Brake Pedal Position Sensor Circuit Intermittent" },
  { code: "C0080", description: "Brake Booster Pressure Sensor Circuit Malfunction" },
  { code: "C0081", description: "Brake Booster Pressure Sensor Circuit Range/Performance" },
  { code: "C0082", description: "Brake Booster Pressure Sensor Circuit Low" },
  { code: "C0083", description: "Brake Booster Pressure Sensor Circuit High" },
  { code: "C0084", description: "Brake Booster Pressure Sensor Circuit Intermittent" },
  { code: "C0090", description: "ABS Hydraulic Pump Motor Circuit Malfunction" },
  { code: "C0091", description: "ABS Hydraulic Pump Motor Circuit Low" },
  { code: "C0092", description: "ABS Hydraulic Pump Motor Circuit High" },
  { code: "C0093", description: "ABS Hydraulic Pump Motor Circuit Intermittent" },
  { code: "C0094", description: "ABS System Relay Circuit Malfunction" },
  { code: "C0095", description: "ABS System Relay Circuit Low" },
  { code: "C0096", description: "ABS System Relay Circuit High" },
  { code: "C0097", description: "ABS System Relay Circuit Intermittent" },
  { code: "C0110", description: "ABS Pump Motor Stalled" },
  { code: "C0111", description: "ABS Pump Motor Ground Circuit Open" },
  { code: "C0121", description: "Valve Relay Coil Circuit Malfunction" },
  { code: "C0122", description: "Valve Relay Coil Circuit Low" },
  { code: "C0123", description: "Valve Relay Coil Circuit High" },
  { code: "C0124", description: "Valve Relay Contact Circuit Malfunction" },
  { code: "C0125", description: "Valve Relay Contact Circuit Low" },
  { code: "C0126", description: "Valve Relay Contact Circuit High" }
];