import { DTC } from '../../types/dtc.types';

export const C01XX_DTCS: DTC[] = [
  { code: "C1000", description: "Steering Angle Sensor Circuit Malfunction" },
  { code: "C1001", description: "Steering Angle Sensor Circuit Range/Performance" },
  { code: "C1002", description: "Steering Angle Sensor Circuit Low" },
  { code: "C1003", description: "Steering Angle Sensor Circuit High" },
  { code: "C1004", description: "Steering Angle Sensor Circuit Intermittent" },
  { code: "C1010", description: "Steering Torque Sensor Circuit Malfunction" },
  { code: "C1011", description: "Steering Torque Sensor Circuit Range/Performance" },
  { code: "C1012", description: "Steering Torque Sensor Circuit Low" },
  { code: "C1013", description: "Steering Torque Sensor Circuit High" },
  { code: "C1014", description: "Steering Torque Sensor Circuit Intermittent" },
  { code: "C1020", description: "Steering Motor Circuit Malfunction" },
  { code: "C1021", description: "Steering Motor Circuit Low" },
  { code: "C1022", description: "Steering Motor Circuit High" },
  { code: "C1023", description: "Steering Motor Circuit Intermittent" },
  { code: "C1024", description: "Steering Motor Over Temperature" },
  { code: "C1025", description: "Steering Motor Stall" },
  { code: "C1030", description: "EPS Control Module Internal Malfunction" },
  { code: "C1031", description: "EPS Control Module Processor" },
  { code: "C1032", description: "EPS Control Module Memory Error" },
  { code: "C1033", description: "EPS Control Module Calibration Error" },
  { code: "C1040", description: "Ride Height Sensor Front Left Circuit Malfunction" },
  { code: "C1041", description: "Ride Height Sensor Front Left Circuit Range/Performance" },
  { code: "C1042", description: "Ride Height Sensor Front Left Circuit Low" },
  { code: "C1043", description: "Ride Height Sensor Front Left Circuit High" },
  { code: "C1044", description: "Ride Height Sensor Front Left Circuit Intermittent" },
  { code: "C1045", description: "Ride Height Sensor Front Right Circuit Malfunction" },
  { code: "C1046", description: "Ride Height Sensor Front Right Circuit Range/Performance" },
  { code: "C1047", description: "Ride Height Sensor Front Right Circuit Low" },
  { code: "C1048", description: "Ride Height Sensor Front Right Circuit High" },
  { code: "C1049", description: "Ride Height Sensor Front Right Circuit Intermittent" },
  { code: "C1050", description: "Ride Height Sensor Rear Left Circuit Malfunction" },
  { code: "C1051", description: "Ride Height Sensor Rear Left Circuit Range/Performance" },
  { code: "C1052", description: "Ride Height Sensor Rear Left Circuit Low" },
  { code: "C1053", description: "Ride Height Sensor Rear Left Circuit High" },
  { code: "C1054", description: "Ride Height Sensor Rear Left Circuit Intermittent" },
  { code: "C1055", description: "Ride Height Sensor Rear Right Circuit Malfunction" },
  { code: "C1056", description: "Ride Height Sensor Rear Right Circuit Range/Performance" },
  { code: "C1057", description: "Ride Height Sensor Rear Right Circuit Low" },
  { code: "C1058", description: "Ride Height Sensor Rear Right Circuit High" },
  { code: "C1059", description: "Ride Height Sensor Rear Right Circuit Intermittent" },
  { code: "C1060", description: "Air Suspension Compressor Circuit Malfunction" },
  { code: "C1061", description: "Air Suspension Compressor Circuit Low" },
  { code: "C1062", description: "Air Suspension Compressor Circuit High" },
  { code: "C1063", description: "Air Suspension Compressor Over Temperature" },
  { code: "C1070", description: "Air Suspension Solenoid Front Left Circuit Malfunction" },
  { code: "C1071", description: "Air Suspension Solenoid Front Left Circuit Low" },
  { code: "C1072", description: "Air Suspension Solenoid Front Left Circuit High" },
  { code: "C1073", description: "Air Suspension Solenoid Front Right Circuit Malfunction" },
  { code: "C1074", description: "Air Suspension Solenoid Front Right Circuit Low" },
  { code: "C1075", description: "Air Suspension Solenoid Front Right Circuit High" },
  { code: "C1076", description: "Air Suspension Solenoid Rear Left Circuit Malfunction" },
  { code: "C1077", description: "Air Suspension Solenoid Rear Left Circuit Low" },
  { code: "C1078", description: "Air Suspension Solenoid Rear Left Circuit High" },
  { code: "C1079", description: "Air Suspension Solenoid Rear Right Circuit Malfunction" },
  { code: "C1080", description: "Air Suspension Solenoid Rear Right Circuit Low" },
  { code: "C1081", description: "Air Suspension Solenoid Rear Right Circuit High" }
];