import { DTC } from '../../types/dtc.types';

export const C02XX_DTCS: DTC[] = [
  { code: "C2000", description: "Traction Control System Malfunction" },
  { code: "C2001", description: "TCS Control Module Internal Malfunction" },
  { code: "C2002", description: "TCS Control Module Processor" },
  { code: "C2003", description: "TCS Control Module Memory Error" },
  { code: "C2004", description: "TCS Control Module Calibration Error" },
  { code: "C2010", description: "Accelerator Pedal Position Sensor Circuit Malfunction" },
  { code: "C2011", description: "Accelerator Pedal Position Sensor Circuit Range/Performance" },
  { code: "C2012", description: "Accelerator Pedal Position Sensor Circuit Low" },
  { code: "C2013", description: "Accelerator Pedal Position Sensor Circuit High" },
  { code: "C2014", description: "Accelerator Pedal Position Sensor Circuit Intermittent" },
  { code: "C2020", description: "Lateral Acceleration Sensor Circuit Malfunction" },
  { code: "C2021", description: "Lateral Acceleration Sensor Circuit Range/Performance" },
  { code: "C2022", description: "Lateral Acceleration Sensor Circuit Low" },
  { code: "C2023", description: "Lateral Acceleration Sensor Circuit High" },
  { code: "C2024", description: "Lateral Acceleration Sensor Circuit Intermittent" },
  { code: "C2030", description: "Yaw Rate Sensor Circuit Malfunction" },
  { code: "C2031", description: "Yaw Rate Sensor Circuit Range/Performance" },
  { code: "C2032", description: "Yaw Rate Sensor Circuit Low" },
  { code: "C2033", description: "Yaw Rate Sensor Circuit High" },
  { code: "C2034", description: "Yaw Rate Sensor Circuit Intermittent" },
  { code: "C2040", description: "Longitudinal Acceleration Sensor Circuit Malfunction" },
  { code: "C2041", description: "Longitudinal Acceleration Sensor Circuit Range/Performance" },
  { code: "C2042", description: "Longitudinal Acceleration Sensor Circuit Low" },
  { code: "C2043", description: "Longitudinal Acceleration Sensor Circuit High" },
  { code: "C2044", description: "Longitudinal Acceleration Sensor Circuit Intermittent" },
  { code: "C2050", description: "Steering Angle Sensor Not Plausible" },
  { code: "C2051", description: "Steering Angle Sensor Zero Point Not Learned" },
  { code: "C2060", description: "Brake Override Switch Circuit Malfunction" },
  { code: "C2061", description: "Brake Override Switch Circuit Low" },
  { code: "C2062", description: "Brake Override Switch Circuit High" },
  { code: "C2063", description: "Brake Override Switch Circuit Intermittent" },
  { code: "C2070", description: "TCS Throttle Control Circuit Malfunction" },
  { code: "C2071", description: "TCS Throttle Control Circuit Low" },
  { code: "C2072", description: "TCS Throttle Control Circuit High" },
  { code: "C2073", description: "TCS Throttle Control Circuit Intermittent" },
  { code: "C2080", description: "TCS Brake Control Circuit Malfunction" },
  { code: "C2081", description: "TCS Brake Control Circuit Low" },
  { code: "C2082", description: "TCS Brake Control Circuit High" },
  { code: "C2083", description: "TCS Brake Control Circuit Intermittent" },
  { code: "C2090", description: "TCS Communication Circuit Malfunction" },
  { code: "C2091", description: "TCS Communication Circuit Low" },
  { code: "C2092", description: "TCS Communication Circuit High" },
  { code: "C2093", description: "TCS Communication Circuit Intermittent" }
];