import { DTC } from '../../types/dtc.types';

export const C03XX_DTCS: DTC[] = [
  { code: "C3000", description: "Chassis Control Module Power Supply Circuit Malfunction" },
  { code: "C3001", description: "Chassis Control Module Power Supply Circuit Low" },
  { code: "C3002", description: "Chassis Control Module Power Supply Circuit High" },
  { code: "C3003", description: "Chassis Control Module Ground Circuit Malfunction" },
  { code: "C3010", description: "Sensor Supply Voltage 'A' Circuit Malfunction" },
  { code: "C3011", description: "Sensor Supply Voltage 'A' Circuit Low" },
  { code: "C3012", description: "Sensor Supply Voltage 'A' Circuit High" },
  { code: "C3013", description: "Sensor Supply Voltage 'B' Circuit Malfunction" },
  { code: "C3014", description: "Sensor Supply Voltage 'B' Circuit Low" },
  { code: "C3015", description: "Sensor Supply Voltage 'B' Circuit High" },
  { code: "C3020", description: "Chassis CAN Bus Communication Malfunction" },
  { code: "C3021", description: "Chassis CAN Bus Communication Performance" },
  { code: "C3022", description: "Chassis CAN Bus (+) Open" },
  { code: "C3023", description: "Chassis CAN Bus (+) Low" },
  { code: "C3024", description: "Chassis CAN Bus (+) High" },
  { code: "C3025", description: "Chassis CAN Bus (-) Open" },
  { code: "C3026", description: "Chassis CAN Bus (-) Low" },
  { code: "C3027", description: "Chassis CAN Bus (-) High" },
  { code: "C3028", description: "Chassis CAN Bus (-) shorted to Bus (+)" },
  { code: "C3030", description: "Lost Communication With ABS Module" },
  { code: "C3031", description: "Lost Communication With Steering Control Module" },
  { code: "C3032", description: "Lost Communication With Suspension Control Module" },
  { code: "C3033", description: "Lost Communication With TCS Module" },
  { code: "C3034", description: "Lost Communication With Brake Module" },
  { code: "C3040", description: "Chassis Control Module Internal Temperature Too High" },
  { code: "C3041", description: "Chassis Control Module Internal Temperature Sensor Circuit" },
  { code: "C3042", description: "Chassis Control Module Internal Temperature Sensor Range/Performance" },
  { code: "C3043", description: "Chassis Control Module Internal Temperature Sensor Low" },
  { code: "C3044", description: "Chassis Control Module Internal Temperature Sensor High" },
  { code: "C3050", description: "Vehicle Speed Signal Malfunction" },
  { code: "C3051", description: "Vehicle Speed Signal Range/Performance" },
  { code: "C3052", description: "Vehicle Speed Signal Low" },
  { code: "C3053", description: "Vehicle Speed Signal High" },
  { code: "C3054", description: "Vehicle Speed Signal Intermittent" },
  { code: "C3060", description: "Brake Light Switch Circuit Malfunction" },
  { code: "C3061", description: "Brake Light Switch Circuit Low" },
  { code: "C3062", description: "Brake Light Switch Circuit High" },
  { code: "C3063", description: "Brake Light Switch Circuit Intermittent" },
  { code: "C3070", description: "Park Brake Switch Circuit Malfunction" },
  { code: "C3071", description: "Park Brake Switch Circuit Low" },
  { code: "C3072", description: "Park Brake Switch Circuit High" },
  { code: "C3073", description: "Park Brake Switch Circuit Intermittent" }
];