// p00xx-fuel-air-metering.js
export const P00XX_DTCS = [
  { code: "P0001", description: "Fuel Volume Regulator Control Circuit/Open" },
  { code: "P0002", description: "Fuel Volume Regulator Control Circuit Range/Performance" },
  { code: "P0003", description: "Fuel Volume Regulator Control Circuit Low" },
  { code: "P0004", description: "Fuel Volume Regulator Control Circuit High" },
  { code: "P0005", description: "Fuel Shutoff Valve 'A' Control Circuit/Open" },
  { code: "P0006", description: "Fuel Shutoff Valve 'A' Control Circuit Low" },
  { code: "P0007", description: "Fuel Shutoff Valve 'A' Control Circuit High" },
  { code: "P0008", description: "Engine Position System Performance", location: "Bank 1" },
  { code: "P0009", description: "Engine Position System Performance", location: "Bank 2" },
  { code: "P0010", description: "'A' Camshaft Position Actuator Circuit", location: "Bank 1" },
  { code: "P0011", description: "'A' Camshaft Position - Timing Over-Advanced or System Performance", location: "Bank 1" },
  { code: "P0012", description: "'A' Camshaft Position - Timing Over-Retarded", location: "Bank 1" },
  { code: "P0013", description: "'B' Camshaft Position - Actuator Circuit", location: "Bank 1" },
  { code: "P0014", description: "'B' Camshaft Position - Timing Over-Advanced or System Performance", location: "Bank 1" },
  { code: "P0015", description: "'B' Camshaft Position - Timing Over-Retarded", location: "Bank 1" },
  { code: "P0016", description: "Crankshaft Position - Camshaft Position Correlation", location: "Bank 1 Sensor A" },
  { code: "P0017", description: "Crankshaft Position - Camshaft Position Correlation", location: "Bank 1 Sensor B" },
  { code: "P0018", description: "Crankshaft Position - Camshaft Position Correlation", location: "Bank 2 Sensor A" },
  { code: "P0019", description: "Crankshaft Position - Camshaft Position Correlation", location: "Bank 2 Sensor B" },
  { code: "P0020", description: "'A' Camshaft Position Actuator Circuit", location: "Bank 2" },
  { code: "P0021", description: "'A' Camshaft Position - Timing Over-Advanced or System Performance", location: "Bank 2" },
  { code: "P0022", description: "'A' Camshaft Position - Timing Over-Retarded", location: "Bank 2" },
  { code: "P0023", description: "'B' Camshaft Position - Actuator Circuit", location: "Bank 2" },
  { code: "P0024", description: "'B' Camshaft Position - Timing Over-Advanced or System Performance", location: "Bank 2" },
  { code: "P0025", description: "'B' Camshaft Position - Timing Over-Retarded", location: "Bank 2" },
  { code: "P0026", description: "Intake Valve Control Solenoid Circuit Range/Performance", location: "Bank 1" },
  { code: "P0027", description: "Exhaust Valve Control Solenoid Circuit Range/Performance", location: "Bank 1" },
  { code: "P0028", description: "Intake Valve Control Solenoid Circuit Range/Performance", location: "Bank 2" },
  { code: "P0029", description: "Exhaust Valve Control Solenoid Circuit Range/Performance", location: "Bank 2" },
  { code: "P0030", description: "HO2S Heater Control Circuit", location: "Bank 1 Sensor 1" },
  { code: "P0031", description: "HO2S Heater Control Circuit Low", location: "Bank 1 Sensor 1" },
  { code: "P0032", description: "HO2S Heater Control Circuit High", location: "Bank 1 Sensor 1" },
  { code: "P0033", description: "Turbo Charger Bypass Valve Control Circuit" },
  { code: "P0034", description: "Turbo Charger Bypass Valve Control Circuit Low" },
  { code: "P0035", description: "Turbo Charger Bypass Valve Control Circuit High" },
  { code: "P0036", description: "HO2S Heater Control Circuit", location: "Bank 1 Sensor 2" },
  { code: "P0037", description: "HO2S Heater Control Circuit Low", location: "Bank 1 Sensor 2" },
  { code: "P0038", description: "HO2S Heater Control Circuit High", location: "Bank 1 Sensor 2" },
  { code: "P0039", description: "Turbo/Super Charger Bypass Valve Control Circuit Range/Performance" },
  { code: "P0040", description: "O2 Sensor Signals Swapped", location: "Bank 1 Sensor 1/Bank 2 Sensor 1" },
  { code: "P0041", description: "O2 Sensor Signals Swapped", location: "Bank 1 Sensor 2/Bank 2 Sensor 2" },
  { code: "P0042", description: "HO2S Heater Control Circuit", location: "Bank 1 Sensor 3" },
  { code: "P0043", description: "HO2S Heater Control Circuit Low", location: "Bank 1 Sensor 3" },
  { code: "P0044", description: "HO2S Heater Control Circuit High", location: "Bank 1 Sensor 3" },
  { code: "P0045", description: "Turbo/Super Charger Boost Control Solenoid Circuit/Open" },
  { code: "P0046", description: "Turbo/Super Charger Boost Control Solenoid Circuit Range/Performance" },
  { code: "P0047", description: "Turbo/Super Charger Boost Control Solenoid Circuit Low" },
  { code: "P0048", description: "Turbo/Super Charger Boost Control Solenoid Circuit High" },
  { code: "P0049", description: "Turbo/Super Charger Turbine Overspeed" },
  { code: "P0050", description: "HO2S Heater Control Circuit", location: "Bank 2 Sensor 1" },
  { code: "P0051", description: "HO2S Heater Control Circuit Low", location: "Bank 2 Sensor 1" },
  { code: "P0052", description: "HO2S Heater Control Circuit High", location: "Bank 2 Sensor 1" },
  { code: "P0053", description: "HO2S Heater Resistance", location: "Bank 1 Sensor 1" },
  { code: "P0054", description: "HO2S Heater Resistance", location: "Bank 1 Sensor 2" },
  { code: "P0055", description: "HO2S Heater Resistance", location: "Bank 1 Sensor 3" },
  { code: "P0056", description: "HO2S Heater Control Circuit", location: "Bank 2 Sensor 2" },
  { code: "P0057", description: "HO2S Heater Control Circuit Low", location: "Bank 2 Sensor 2" },
  { code: "P0058", description: "HO2S Heater Control Circuit High", location: "Bank 2 Sensor 2" },
  { code: "P0059", description: "HO2S Heater Resistance", location: "Bank 2 Sensor 1" },
  { code: "P0060", description: "HO2S Heater Resistance", location: "Bank 2 Sensor 2" },
  { code: "P0061", description: "HO2S Heater Resistance", location: "Bank 2 Sensor 3" },
  { code: "P0062", description: "HO2S Heater Control Circuit", location: "Bank 2 Sensor 3" },
  { code: "P0063", description: "HO2S Heater Control Circuit Low", location: "Bank 2 Sensor 3" },
  { code: "P0064", description: "HO2S Heater Control Circuit High", location: "Bank 2 Sensor 3" },
  { code: "P0065", description: "Air Assisted Injector Control Range/Performance" },
  { code: "P0066", description: "Air Assisted Injector Control Circuit or Circuit Low" },
  { code: "P0067", description: "Air Assisted Injector Control Circuit High" },
  { code: "P0068", description: "MAP/MAF - Throttle Position Correlation" },
  { code: "P0069", description: "Manifold Absolute Pressure - Barometric Pressure Correlation" },
  { code: "P0070", description: "Ambient Air Temperature Sensor Circuit" },
  { code: "P0071", description: "Ambient Air Temperature Sensor Range/Performance" },
  { code: "P0072", description: "Ambient Air Temperature Sensor Circuit Low" },
  { code: "P0073", description: "Ambient Air Temperature Sensor Circuit High" },
  { code: "P0074", description: "Ambient Air Temperature Sensor Circuit Intermittent" },
  { code: "P0075", description: "Intake Valve Control Solenoid Circuit", location: "Bank 1" },
  { code: "P0076", description: "Intake Valve Control Solenoid Circuit Low", location: "Bank 1" },
  { code: "P0077", description: "Intake Valve Control Solenoid Circuit High", location: "Bank 1" },
  { code: "P0078", description: "Exhaust Valve Control Solenoid Circuit", location: "Bank 1" },
  { code: "P0079", description: "Exhaust Valve Control Solenoid Circuit Low", location: "Bank 1" },
  { code: "P0080", description: "Exhaust Valve Control Solenoid Circuit High", location: "Bank 1" },
  { code: "P0081", description: "Intake Valve Control Solenoid Circuit", location: "Bank 2" },
  { code: "P0082", description: "Intake Valve Control Solenoid Circuit Low", location: "Bank 2" },
  { code: "P0083", description: "Intake Valve Control Solenoid Circuit High", location: "Bank 2" },
  { code: "P0084", description: "Exhaust Valve Control Solenoid Circuit", location: "Bank 2" },
  { code: "P0085", description: "Exhaust Valve Control Solenoid Circuit Low", location: "Bank 2" },
  { code: "P0086", description: "Exhaust Valve Control Solenoid Circuit High", location: "Bank 2" },
  { code: "P0087", description: "Fuel Rail/System Pressure Too Low" },
  { code: "P0088", description: "Fuel Rail/System Pressure Too High" },
  { code: "P0089", description: "Fuel Pressure Regulator 1 Performance" },
  { code: "P0090", description: "Fuel Pressure Regulator 1 Control Circuit" },
  { code: "P0091", description: "Fuel Pressure Regulator 1 Control Circuit Low" },
  { code: "P0092", description: "Fuel Pressure Regulator 1 Control Circuit High" },
  { code: "P0093", description: "Fuel System Leak Detected - Large Leak" },
  { code: "P0094", description: "Fuel System Leak Detected - Small Leak" },
  { code: "P0095", description: "Intake Air Temperature Sensor 2 Circuit" },
  { code: "P0096", description: "Intake Air Temperature Sensor 2 Circuit Range/Performance" },
  { code: "P0097", description: "Intake Air Temperature Sensor 2 Circuit Low" },
  { code: "P0098", description: "Intake Air Temperature Sensor 2 Circuit High" },
  { code: "P0099", description: "Intake Air Temperature Sensor 2 Circuit Intermittent/Erratic" }
];