// p02xx-injectors.js
export const P02XX_DTCS = [
  { code: "P0200", description: "Injector Circuit/Open" },
  { code: "P0201", description: "Injector Circuit/Open - Cylinder 1" },
  { code: "P0202", description: "Injector Circuit/Open - Cylinder 2" },
  { code: "P0203", description: "Injector Circuit/Open - Cylinder 3" },
  { code: "P0204", description: "Injector Circuit/Open - Cylinder 4" },
  { code: "P0205", description: "Injector Circuit/Open - Cylinder 5" },
  { code: "P0206", description: "Injector Circuit/Open - Cylinder 6" },
  { code: "P0207", description: "Injector Circuit/Open - Cylinder 7" },
  { code: "P0208", description: "Injector Circuit/Open - Cylinder 8" },
  { code: "P0209", description: "Injector Circuit/Open - Cylinder 9" },
  { code: "P0210", description: "Injector Circuit/Open - Cylinder 10" },
  { code: "P0211", description: "Injector Circuit/Open - Cylinder 11" },
  { code: "P0212", description: "Injector Circuit/Open - Cylinder 12" },
  { code: "P0213", description: "Cold Start Injector 1" },
  { code: "P0214", description: "Cold Start Injector 2" },
  { code: "P0215", description: "Engine Shutoff Solenoid" },
  { code: "P0216", description: "Injector/Injection Timing Control Circuit" },
  { code: "P0217", description: "Engine Coolant Over Temperature Condition" },
  { code: "P0218", description: "Transmission Fluid Over Temperature Condition" },
  { code: "P0219", description: "Engine Overspeed Condition" },
  { code: "P0220", description: "Throttle/Pedal Position Sensor/Switch 'B' Circuit" },
  { code: "P0221", description: "Throttle/Pedal Position Sensor/Switch 'B' Circuit Range/Performance" },
  { code: "P0222", description: "Throttle/Pedal Position Sensor/Switch 'B' Circuit Low" },
  { code: "P0223", description: "Throttle/Pedal Position Sensor/Switch 'B' Circuit High" },
  { code: "P0224", description: "Throttle/Pedal Position Sensor/Switch 'B' Circuit Intermittent" },
  { code: "P0225", description: "Throttle/Pedal Position Sensor/Switch 'C' Circuit" },
  { code: "P0226", description: "Throttle/Pedal Position Sensor/Switch 'C' Circuit Range/Performance" },
  { code: "P0227", description: "Throttle/Pedal Position Sensor/Switch 'C' Circuit Low" },
  { code: "P0228", description: "Throttle/Pedal Position Sensor/Switch 'C' Circuit High" },
  { code: "P0229", description: "Throttle/Pedal Position Sensor/Switch 'C' Circuit Intermittent" },
  { code: "P0230", description: "Fuel Pump Primary Circuit" },
  { code: "P0231", description: "Fuel Pump Secondary Circuit Low" },
  { code: "P0232", description: "Fuel Pump Secondary Circuit High" },
  { code: "P0233", description: "Fuel Pump Secondary Circuit Intermittent" },
  { code: "P0234", description: "Turbo/Super Charger Overboost Condition" },
  { code: "P0235", description: "Turbo/Super Charger Boost Sensor 'A' Circuit" },
  { code: "P0236", description: "Turbo/Super Charger Boost Sensor 'A' Circuit Range/Performance" },
  { code: "P0237", description: "Turbo/Super Charger Boost Sensor 'A' Circuit Low" },
  { code: "P0238", description: "Turbo/Super Charger Boost Sensor 'A' Circuit High" },
  { code: "P0239", description: "Turbo/Super Charger Boost Sensor 'B' Circuit" },
  { code: "P0240", description: "Turbo/Super Charger Boost Sensor 'B' Circuit Range/Performance" },
  { code: "P0241", description: "Turbo/Super Charger Boost Sensor 'B' Circuit Low" },
  { code: "P0242", description: "Turbo/Super Charger Boost Sensor 'B' Circuit High" },
  { code: "P0243", description: "Turbo/Super Charger Wastegate Solenoid 'A'" },
  { code: "P0244", description: "Turbo/Super Charger Wastegate Solenoid 'A' Range/Performance" },
  { code: "P0245", description: "Turbo/Super Charger Wastegate Solenoid 'A' Low" },
  { code: "P0246", description: "Turbo/Super Charger Wastegate Solenoid 'A' High" },
  { code: "P0247", description: "Turbo/Super Charger Wastegate Solenoid 'B'" },
  { code: "P0248", description: "Turbo/Super Charger Wastegate Solenoid 'B' Range/Performance" },
  { code: "P0249", description: "Turbo/Super Charger Wastegate Solenoid 'B' Low" },
  { code: "P0250", description: "Turbo/Super Charger Wastegate Solenoid 'B' High" },
  { code: "P0261", description: "Cylinder 1 Injector Circuit Low" },
  { code: "P0262", description: "Cylinder 1 Injector Circuit High" },
  { code: "P0263", description: "Cylinder 1 Contribution/Balance" },
  { code: "P0264", description: "Cylinder 2 Injector Circuit Low" },
  { code: "P0265", description: "Cylinder 2 Injector Circuit High" },
  { code: "P0266", description: "Cylinder 2 Contribution/Balance" },
  { code: "P0267", description: "Cylinder 3 Injector Circuit Low" },
  { code: "P0268", description: "Cylinder 3 Injector Circuit High" },
  { code: "P0269", description: "Cylinder 3 Contribution/Balance" },
  { code: "P0270", description: "Cylinder 4 Injector Circuit Low" },
  { code: "P0271", description: "Cylinder 4 Injector Circuit High" },
  { code: "P0272", description: "Cylinder 4 Contribution/Balance" },
  { code: "P0273", description: "Cylinder 5 Injector Circuit Low" },
  { code: "P0274", description: "Cylinder 5 Injector Circuit High" },
  { code: "P0275", description: "Cylinder 5 Contribution/Balance" },
  { code: "P0276", description: "Cylinder 6 Injector Circuit Low" },
  { code: "P0277", description: "Cylinder 6 Injector Circuit High" },
  { code: "P0278", description: "Cylinder 6 Contribution/Balance" },
  { code: "P0279", description: "Cylinder 7 Injector Circuit Low" },
  { code: "P0280", description: "Cylinder 7 Injector Circuit High" },
  { code: "P0281", description: "Cylinder 7 Contribution/Balance" },
  { code: "P0282", description: "Cylinder 8 Injector Circuit Low" },
  { code: "P0283", description: "Cylinder 8 Injector Circuit High" },
  { code: "P0284", description: "Cylinder 8 Contribution/Balance" },
  { code: "P0285", description: "Cylinder 9 Injector Circuit Low" },
  { code: "P0286", description: "Cylinder 9 Injector Circuit High" },
  { code: "P0287", description: "Cylinder 9 Contribution/Balance" },
  { code: "P0288", description: "Cylinder 10 Injector Circuit Low" },
  { code: "P0289", description: "Cylinder 10 Injector Circuit High" },
  { code: "P0290", description: "Cylinder 10 Contribution/Balance" },
  { code: "P0291", description: "Cylinder 11 Injector Circuit Low" },
  { code: "P0292", description: "Cylinder 11 Injector Circuit High" },
  { code: "P0293", description: "Cylinder 11 Contribution/Balance" },
  { code: "P0294", description: "Cylinder 12 Injector Circuit Low" },
  { code: "P0295", description: "Cylinder 12 Injector Circuit High" },
  { code: "P0296", description: "Cylinder 12 Contribution/Balance" },
  { code: "P0297", description: "Vehicle Overspeed Condition" },
  { code: "P0298", description: "Engine Oil Over Temperature" },
  { code: "P0299", description: "Turbo/Super Charger Underboost" }
];