// p03xx-ignition-misfire.js
export const P03XX_DTCS = [
  { code: "P0300", description: "Random/Multiple Cylinder Misfire Detected" },
  { code: "P0301", description: "Cylinder 1 Misfire Detected" },
  { code: "P0302", description: "Cylinder 2 Misfire Detected" },
  { code: "P0303", description: "Cylinder 3 Misfire Detected" },
  { code: "P0304", description: "Cylinder 4 Misfire Detected" },
  { code: "P0305", description: "Cylinder 5 Misfire Detected" },
  { code: "P0306", description: "Cylinder 6 Misfire Detected" },
  { code: "P0307", description: "Cylinder 7 Misfire Detected" },
  { code: "P0308", description: "Cylinder 8 Misfire Detected" },
  { code: "P0309", description: "Cylinder 9 Misfire Detected" },
  { code: "P0310", description: "Cylinder 10 Misfire Detected" },
  { code: "P0311", description: "Cylinder 11 Misfire Detected" },
  { code: "P0312", description: "Cylinder 12 Misfire Detected" },
  { code: "P0313", description: "Misfire Detected with Low Fuel" },
  { code: "P0314", description: "Single Cylinder Misfire (Cylinder not Specified)" },
  { code: "P0315", description: "Crankshaft Position System Variation Not Learned" },
  { code: "P0316", description: "Engine Misfire Detected on Startup (First 1000 Revolutions)" },
  { code: "P0317", description: "Rough Road Hardware Not Present" },
  { code: "P0318", description: "Rough Road Sensor 'A' Signal Circuit" },
  { code: "P0319", description: "Rough Road Sensor 'B'" },
  { code: "P0320", description: "Ignition/Distributor Engine Speed Input Circuit" },
  { code: "P0321", description: "Ignition/Distributor Engine Speed Input Circuit Range/Performance" },
  { code: "P0322", description: "Ignition/Distributor Engine Speed Input Circuit No Signal" },
  { code: "P0323", description: "Ignition/Distributor Engine Speed Input Circuit Intermittent" },
  { code: "P0324", description: "Knock Control System Error" },
  { code: "P0325", description: "Knock Sensor 1 Circuit", location: "Bank 1 or Single Sensor" },
  { code: "P0326", description: "Knock Sensor 1 Circuit Range/Performance", location: "Bank 1 or Single Sensor" },
  { code: "P0327", description: "Knock Sensor 1 Circuit Low", location: "Bank 1 or Single Sensor" },
  { code: "P0328", description: "Knock Sensor 1 Circuit High", location: "Bank 1 or Single Sensor" },
  { code: "P0329", description: "Knock Sensor 1 Circuit Input Intermittent", location: "Bank 1 or Single Sensor" },
  { code: "P0330", description: "Knock Sensor 2 Circuit", location: "Bank 2" },
  { code: "P0331", description: "Knock Sensor 2 Circuit Range/Performance", location: "Bank 2" },
  { code: "P0332", description: "Knock Sensor 2 Circuit Low", location: "Bank 2" },
  { code: "P0333", description: "Knock Sensor 2 Circuit High", location: "Bank 2" },
  { code: "P0334", description: "Knock Sensor 2 Circuit Input Intermittent", location: "Bank 2" },
  { code: "P0335", description: "Crankshaft Position Sensor 'A' Circuit" },
  { code: "P0336", description: "Crankshaft Position Sensor 'A' Circuit Range/Performance" },
  { code: "P0337", description: "Crankshaft Position Sensor 'A' Circuit Low" },
  { code: "P0338", description: "Crankshaft Position Sensor 'A' Circuit High" },
  { code: "P0339", description: "Crankshaft Position Sensor 'A' Circuit Intermittent" },
  { code: "P0340", description: "Camshaft Position Sensor 'A' Circuit", location: "Bank 1 or Single Sensor" },
  { code: "P0341", description: "Camshaft Position Sensor 'A' Circuit Range/Performance", location: "Bank 1 or Single Sensor" },
  { code: "P0342", description: "Camshaft Position Sensor 'A' Circuit Low", location: "Bank 1 or Single Sensor" },
  { code: "P0343", description: "Camshaft Position Sensor 'A' Circuit High", location: "Bank 1 or Single Sensor" },
  { code: "P0344", description: "Camshaft Position Sensor 'A' Circuit Intermittent", location: "Bank 1 or Single Sensor" },
  { code: "P0345", description: "Camshaft Position Sensor 'A' Circuit", location: "Bank 2" },
  { code: "P0346", description: "Camshaft Position Sensor 'A' Circuit Range/Performance", location: "Bank 2" },
  { code: "P0347", description: "Camshaft Position Sensor 'A' Circuit Low", location: "Bank 2" },
  { code: "P0348", description: "Camshaft Position Sensor 'A' Circuit High", location: "Bank 2" },
  { code: "P0349", description: "Camshaft Position Sensor 'A' Circuit Intermittent", location: "Bank 2" },
  { code: "P0350", description: "Ignition Coil Primary/Secondary Circuit" },
  { code: "P0351", description: "Ignition Coil 'A' Primary/Secondary Circuit" },
  { code: "P0352", description: "Ignition Coil 'B' Primary/Secondary Circuit" },
  { code: "P0353", description: "Ignition Coil 'C' Primary/Secondary Circuit" },
  { code: "P0354", description: "Ignition Coil 'D' Primary/Secondary Circuit" },
  { code: "P0355", description: "Ignition Coil 'E' Primary/Secondary Circuit" },
  { code: "P0356", description: "Ignition Coil 'F' Primary/Secondary Circuit" },
  { code: "P0357", description: "Ignition Coil 'G' Primary/Secondary Circuit" },
  { code: "P0358", description: "Ignition Coil 'H' Primary/Secondary Circuit" },
  { code: "P0359", description: "Ignition Coil 'I' Primary/Secondary Circuit" },
  { code: "P0360", description: "Ignition Coil 'J' Primary/Secondary Circuit" },
  { code: "P0361", description: "Ignition Coil 'K' Primary/Secondary Circuit" },
  { code: "P0362", description: "Ignition Coil 'L' Primary/Secondary Circuit" },
  { code: "P0363", description: "Misfire Detected - Fueling Disabled" },
  { code: "P0365", description: "Camshaft Position Sensor 'B' Circuit", location: "Bank 1" },
  { code: "P0366", description: "Camshaft Position Sensor 'B' Circuit Range/Performance", location: "Bank 1" },
  { code: "P0367", description: "Camshaft Position Sensor 'B' Circuit Low", location: "Bank 1" },
  { code: "P0368", description: "Camshaft Position Sensor 'B' Circuit High", location: "Bank 1" },
  { code: "P0369", description: "Camshaft Position Sensor 'B' Circuit Intermittent", location: "Bank 1" },
  { code: "P0380", description: "Glow Plug/Heater Circuit 'A'" },
  { code: "P0381", description: "Glow Plug/Heater Indicator Circuit" },
  { code: "P0382", description: "Glow Plug/Heater Circuit 'B'" },
  { code: "P0385", description: "Crankshaft Position Sensor 'B' Circuit" },
  { code: "P0386", description: "Crankshaft Position Sensor 'B' Circuit Range/Performance" },
  { code: "P0387", description: "Crankshaft Position Sensor 'B' Circuit Low" },
  { code: "P0388", description: "Crankshaft Position Sensor 'B' Circuit High" },
  { code: "P0389", description: "Crankshaft Position Sensor 'B' Circuit Intermittent" },
  { code: "P0390", description: "Camshaft Position Sensor 'B' Circuit", location: "Bank 2" },
  { code: "P0391", description: "Camshaft Position Sensor 'B' Circuit Range/Performance", location: "Bank 2" },
  { code: "P0392", description: "Camshaft Position Sensor 'B' Circuit Low", location: "Bank 2" },
  { code: "P0393", description: "Camshaft Position Sensor 'B' Circuit High", location: "Bank 2" },
  { code: "P0394", description: "Camshaft Position Sensor 'B' Circuit Intermittent", location: "Bank 2" }
];