// p04xx-emission-controls.js
export const P04XX_DTCS = [
  { code: "P0400", description: "Exhaust Gas Recirculation Flow" },
  { code: "P0401", description: "Exhaust Gas Recirculation Flow Insufficient Detected" },
  { code: "P0402", description: "Exhaust Gas Recirculation Flow Excessive Detected" },
  { code: "P0403", description: "Exhaust Gas Recirculation Control Circuit" },
  { code: "P0404", description: "Exhaust Gas Recirculation Control Circuit Range/Performance" },
  { code: "P0405", description: "Exhaust Gas Recirculation Sensor 'A' Circuit Low" },
  { code: "P0406", description: "Exhaust Gas Recirculation Sensor 'A' Circuit High" },
  { code: "P0407", description: "Exhaust Gas Recirculation Sensor 'B' Circuit Low" },
  { code: "P0408", description: "Exhaust Gas Recirculation Sensor 'B' Circuit High" },
  { code: "P0409", description: "Exhaust Gas Recirculation Sensor 'A' Circuit" },
  { code: "P0410", description: "Secondary Air Injection System" },
  { code: "P0411", description: "Secondary Air Injection System Incorrect Flow Detected" },
  { code: "P0412", description: "Secondary Air Injection System Switching Valve 'A' Circuit" },
  { code: "P0413", description: "Secondary Air Injection System Switching Valve 'A' Circuit Open" },
  { code: "P0414", description: "Secondary Air Injection System Switching Valve 'A' Circuit Shorted" },
  { code: "P0415", description: "Secondary Air Injection System Switching Valve 'B' Circuit" },
  { code: "P0416", description: "Secondary Air Injection System Switching Valve 'B' Circuit Open" },
  { code: "P0417", description: "Secondary Air Injection System Switching Valve 'B' Circuit Shorted" },
  { code: "P0418", description: "Secondary Air Injection System Control 'A' Circuit" },
  { code: "P0419", description: "Secondary Air Injection System Control 'B' Circuit" },
  { code: "P0420", description: "Catalyst System Efficiency Below Threshold", location: "Bank 1" },
  { code: "P0421", description: "Warm Up Catalyst Efficiency Below Threshold", location: "Bank 1" },
  { code: "P0422", description: "Main Catalyst Efficiency Below Threshold", location: "Bank 1" },
  { code: "P0423", description: "Heated Catalyst Efficiency Below Threshold", location: "Bank 1" },
  { code: "P0424", description: "Heated Catalyst Temperature Below Threshold", location: "Bank 1" },
  { code: "P0425", description: "Catalyst Temperature Sensor", location: "Bank 1" },
  { code: "P0426", description: "Catalyst Temperature Sensor Range/Performance", location: "Bank 1" },
  { code: "P0427", description: "Catalyst Temperature Sensor Low", location: "Bank 1" },
  { code: "P0428", description: "Catalyst Temperature Sensor High", location: "Bank 1" },
  { code: "P0429", description: "Catalyst Heater Control Circuit", location: "Bank 1" },
  { code: "P0430", description: "Catalyst System Efficiency Below Threshold", location: "Bank 2" },
  { code: "P0431", description: "Warm Up Catalyst Efficiency Below Threshold", location: "Bank 2" },
  { code: "P0432", description: "Main Catalyst Efficiency Below Threshold", location: "Bank 2" },
  { code: "P0433", description: "Heated Catalyst Efficiency Below Threshold", location: "Bank 2" },
  { code: "P0434", description: "Heated Catalyst Temperature Below Threshold", location: "Bank 2" },
  { code: "P0435", description: "Catalyst Temperature Sensor", location: "Bank 2" },
  { code: "P0436", description: "Catalyst Temperature Sensor Range/Performance", location: "Bank 2" },
  { code: "P0437", description: "Catalyst Temperature Sensor Low", location: "Bank 2" },
  { code: "P0438", description: "Catalyst Temperature Sensor High", location: "Bank 2" },
  { code: "P0439", description: "Catalyst Heater Control Circuit", location: "Bank 2" },
  { code: "P0440", description: "Evaporative Emission System" },
  { code: "P0441", description: "Evaporative Emission System Incorrect Purge Flow" },
  { code: "P0442", description: "Evaporative Emission System Leak Detected (small leak)" },
  { code: "P0443", description: "Evaporative Emission System Purge Control Valve Circuit" },
  { code: "P0444", description: "Evaporative Emission System Purge Control Valve Circuit Open" },
  { code: "P0445", description: "Evaporative Emission System Purge Control Valve Circuit Shorted" },
  { code: "P0446", description: "Evaporative Emission System Vent Control Circuit" },
  { code: "P0447", description: "Evaporative Emission System Vent Control Circuit Open" },
  { code: "P0448", description: "Evaporative Emission System Vent Control Circuit Shorted" },
  { code: "P0449", description: "Evaporative Emission System Vent Valve/Solenoid Circuit" },
  { code: "P0450", description: "Evaporative Emission System Pressure Sensor/Switch" },
  { code: "P0451", description: "Evaporative Emission System Pressure Sensor/Switch Range/Performance" },
  { code: "P0452", description: "Evaporative Emission System Pressure Sensor/Switch Low" },
  { code: "P0453", description: "Evaporative Emission System Pressure Sensor/Switch High" },
  { code: "P0454", description: "Evaporative Emission System Pressure Sensor/Switch Intermittent" },
  { code: "P0455", description: "Evaporative Emission System Leak Detected (large leak)" },
  { code: "P0456", description: "Evaporative Emission System Leak Detected (very small leak)" },
  { code: "P0457", description: "Evaporative Emission System Leak Detected (fuel cap loose/off)" },
  { code: "P0458", description: "Evaporative Emission System Purge Control Valve Circuit Low" },
  { code: "P0459", description: "Evaporative Emission System Purge Control Valve Circuit High" },
  { code: "P0460", description: "Fuel Level Sensor 'A' Circuit" },
  { code: "P0461", description: "Fuel Level Sensor 'A' Circuit Range/Performance" },
  { code: "P0462", description: "Fuel Level Sensor 'A' Circuit Low" },
  { code: "P0463", description: "Fuel Level Sensor 'A' Circuit High" },
  { code: "P0464", description: "Fuel Level Sensor 'A' Circuit Intermittent" },
  { code: "P0465", description: "EVAP Purge Flow Sensor Circuit" },
  { code: "P0466", description: "EVAP Purge Flow Sensor Circuit Range/Performance" },
  { code: "P0467", description: "EVAP Purge Flow Sensor Circuit Low" },
  { code: "P0468", description: "EVAP Purge Flow Sensor Circuit High" },
  { code: "P0469", description: "EVAP Purge Flow Sensor Circuit Intermittent" },
  { code: "P0470", description: "Exhaust Pressure Sensor" },
  { code: "P0471", description: "Exhaust Pressure Sensor Range/Performance" },
  { code: "P0472", description: "Exhaust Pressure Sensor Low" },
  { code: "P0473", description: "Exhaust Pressure Sensor High" },
  { code: "P0474", description: "Exhaust Pressure Sensor Intermittent" },
  { code: "P0475", description: "Exhaust Pressure Control Valve" },
  { code: "P0476", description: "Exhaust Pressure Control Valve Range/Performance" },
  { code: "P0477", description: "Exhaust Pressure Control Valve Low" },
  { code: "P0478", description: "Exhaust Pressure Control Valve High" },
  { code: "P0479", description: "Exhaust Pressure Control Valve Intermittent" },
  { code: "P0480", description: "Fan 1 Control Circuit" },
  { code: "P0481", description: "Fan 2 Control Circuit" },
  { code: "P0482", description: "Fan 3 Control Circuit" },
  { code: "P0483", description: "Fan Rationality Check" },
  { code: "P0484", description: "Fan Circuit Over Current" },
  { code: "P0485", description: "Fan Power/Ground Circuit" },
  { code: "P0486", description: "Exhaust Gas Recirculation Sensor 'B' Circuit" },
  { code: "P0487", description: "Exhaust Gas Recirculation Throttle Position Control Circuit" },
  { code: "P0488", description: "Exhaust Gas Recirculation Throttle Position Control Range/Performance" },
  { code: "P0489", description: "Exhaust Gas Recirculation Control Circuit Low" },
  { code: "P0490", description: "Exhaust Gas Recirculation Control Circuit High" },
  { code: "P0491", description: "Secondary Air Injection System Insufficient Flow", location: "Bank 1" },
  { code: "P0492", description: "Secondary Air Injection System Insufficient Flow", location: "Bank 2" },
  { code: "P0493", description: "Fan Overspeed" },
  { code: "P0494", description: "Fan Speed Low" },
  { code: "P0495", description: "Fan Speed High" },
  { code: "P0496", description: "Evaporative Emission System High Purge Flow" },
  { code: "P0497", description: "Evaporative Emission System Low Purge Flow" },
  { code: "P0498", description: "Evaporative Emission System Vent Valve Control Circuit Low" },
  { code: "P0499", description: "Evaporative Emission System Vent Valve Control Circuit High" }
];