// p05xx-speed-idle-inputs.js
export const P05XX_DTCS = [
  { code: "P0500", description: "Vehicle Speed Sensor 'A'" },
  { code: "P0501", description: "Vehicle Speed Sensor 'A' Range/Performance" },
  { code: "P0502", description: "Vehicle Speed Sensor 'A' Circuit Low Input" },
  { code: "P0503", description: "Vehicle Speed Sensor 'A' Intermittent/Erratic/High" },
  { code: "P0504", description: "Brake Switch 'A'/'B' Correlation" },
  { code: "P0505", description: "Idle Air Control System" },
  { code: "P0506", description: "Idle Air Control System RPM Lower Than Expected" },
  { code: "P0507", description: "Idle Air Control System RPM Higher Than Expected" },
  { code: "P0508", description: "Idle Air Control System Circuit Low" },
  { code: "P0509", description: "Idle Air Control System Circuit High" },
  { code: "P0510", description: "Closed Throttle Position Switch" },
  { code: "P0511", description: "Idle Air Control Circuit" },
  { code: "P0512", description: "Starter Request Circuit" },
  { code: "P0513", description: "Incorrect Immobilizer Key" },
  { code: "P0514", description: "Battery Temperature Sensor Circuit Range/Performance" },
  { code: "P0515", description: "Battery Temperature Sensor Circuit" },
  { code: "P0516", description: "Battery Temperature Sensor Circuit Low" },
  { code: "P0517", description: "Battery Temperature Sensor Circuit High" },
  { code: "P0518", description: "Idle Air Control Circuit Intermittent" },
  { code: "P0519", description: "Idle Air Control System Performance" },
  { code: "P0520", description: "Engine Oil Pressure Sensor/Switch Circuit" },
  { code: "P0521", description: "Engine Oil Pressure Sensor/Switch Range/Performance" },
  { code: "P0522", description: "Engine Oil Pressure Sensor/Switch Low Voltage" },
  { code: "P0523", description: "Engine Oil Pressure Sensor/Switch High Voltage" },
  { code: "P0524", description: "Engine Oil Pressure Too Low" },
  { code: "P0530", description: "A/C Refrigerant Pressure Sensor 'A' Circuit" },
  { code: "P0531", description: "A/C Refrigerant Pressure Sensor 'A' Circuit Range/Performance" },
  { code: "P0532", description: "A/C Refrigerant Pressure Sensor 'A' Circuit Low" },
  { code: "P0533", description: "A/C Refrigerant Pressure Sensor 'A' Circuit High" },
  { code: "P0534", description: "Air Conditioner Refrigerant Charge Loss" },
  { code: "P0540", description: "Intake Air Heater 'A' Circuit" },
  { code: "P0541", description: "Intake Air Heater 'A' Circuit Low" },
  { code: "P0542", description: "Intake Air Heater 'A' Circuit High" },
  { code: "P0543", description: "Intake Air Heater 'A' Circuit Open" },
  { code: "P0544", description: "Exhaust Gas Temperature Sensor Circuit", location: "Bank 1 Sensor 1" },
  { code: "P0545", description: "Exhaust Gas Temperature Sensor Circuit Low", location: "Bank 1 Sensor 1" },
  { code: "P0546", description: "Exhaust Gas Temperature Sensor Circuit High", location: "Bank 1 Sensor 1" },
  { code: "P0547", description: "Exhaust Gas Temperature Sensor Circuit", location: "Bank 2 Sensor 1" },
  { code: "P0548", description: "Exhaust Gas Temperature Sensor Circuit Low", location: "Bank 2 Sensor 1" },
  { code: "P0549", description: "Exhaust Gas Temperature Sensor Circuit High", location: "Bank 2 Sensor 1" },
  { code: "P0550", description: "Power Steering Pressure Sensor/Switch Circuit" },
  { code: "P0551", description: "Power Steering Pressure Sensor/Switch Circuit Range/Performance" },
  { code: "P0552", description: "Power Steering Pressure Sensor/Switch Circuit Low Input" },
  { code: "P0553", description: "Power Steering Pressure Sensor/Switch Circuit High Input" },
  { code: "P0554", description: "Power Steering Pressure Sensor/Switch Circuit Intermittent" },
  { code: "P0560", description: "System Voltage" },
  { code: "P0561", description: "System Voltage Unstable" },
  { code: "P0562", description: "System Voltage Low" },
  { code: "P0563", description: "System Voltage High" },
  { code: "P0564", description: "Cruise Control Multi-Function Input 'A' Circuit" },
  { code: "P0565", description: "Cruise Control On Signal" },
  { code: "P0566", description: "Cruise Control Off Signal" },
  { code: "P0567", description: "Cruise Control Resume Signal" },
  { code: "P0568", description: "Cruise Control Set Signal" },
  { code: "P0569", description: "Cruise Control Coast Signal" },
  { code: "P0570", description: "Cruise Control Accelerate Signal" },
  { code: "P0571", description: "Brake Switch 'A' Circuit" },
  { code: "P0572", description: "Brake Switch 'A' Circuit Low" },
  { code: "P0573", description: "Brake Switch 'A' Circuit High" },
  { code: "P0574", description: "Cruise Control System - Vehicle Speed Too High" },
  { code: "P0575", description: "Cruise Control Input Circuit" },
  { code: "P0576", description: "Cruise Control Input Circuit Low" },
  { code: "P0577", description: "Cruise Control Input Circuit High" }
];