// p06xx-computer-outputs.js
export const P06XX_DTCS = [
  { code: "P0600", description: "Serial Communication Link" },
  { code: "P0601", description: "Internal Control Module Memory Check Sum Error" },
  { code: "P0602", description: "Control Module Programming Error" },
  { code: "P0603", description: "Internal Control Module Keep Alive Memory (KAM) Error" },
  { code: "P0604", description: "Internal Control Module Random Access Memory (RAM) Error" },
  { code: "P0605", description: "Internal Control Module Read Only Memory (ROM) Error" },
  { code: "P0606", description: "ECM/PCM Processor" },
  { code: "P0607", description: "Control Module Performance" },
  { code: "P0608", description: "Control Module VSS Output 'A'" },
  { code: "P0609", description: "Control Module VSS Output 'B'" },
  { code: "P0610", description: "Control Module Vehicle Options Error" },
  { code: "P0611", description: "Fuel Injector Control Module Performance" },
  { code: "P0612", description: "Fuel Injector Control Module Relay Control" },
  { code: "P0613", description: "TCM Processor" },
  { code: "P0614", description: "ECM/TCM Incompatible" },
  { code: "P0615", description: "Starter Relay Circuit" },
  { code: "P0616", description: "Starter Relay Circuit Low" },
  { code: "P0617", description: "Starter Relay Circuit High" },
  { code: "P0620", description: "Generator Control Circuit" },
  { code: "P0621", description: "Generator Lamp/L Terminal Circuit" },
  { code: "P0622", description: "Generator Field/F Terminal Circuit" },
  { code: "P0623", description: "Generator Lamp Control Circuit" },
  { code: "P0624", description: "Fuel Cap Lamp Control Circuit" },
  { code: "P0625", description: "Generator Field/F Terminal Circuit Low" },
  { code: "P0626", description: "Generator Field/F Terminal Circuit High" },
  { code: "P0627", description: "Fuel Pump 'A' Control Circuit /Open" },
  { code: "P0628", description: "Fuel Pump 'A' Control Circuit Low" },
  { code: "P0629", description: "Fuel Pump 'A' Control Circuit High" },
  { code: "P0630", description: "VIN Not Programmed or Incompatible - ECM/PCM" },
  { code: "P0631", description: "VIN Not Programmed or Incompatible - TCM" },
  { code: "P0632", description: "Odometer Not Programmed - ECM/PCM" },
  { code: "P0633", description: "Immobilizer Key Not Programmed - ECM/PCM" },
  { code: "P0634", description: "PCM/ECM/TCM Internal Temperature Too High" },
  { code: "P0638", description: "Throttle Actuator Control Range/Performance", location: "Bank 1" },
  { code: "P0639", description: "Throttle Actuator Control Range/Performance", location: "Bank 2" },
  { code: "P0640", description: "Intake Air Heater Control Circuit" },
  { code: "P0641", description: "Sensor Reference Voltage 'A' Circuit/Open" },
  { code: "P0642", description: "Sensor Reference Voltage 'A' Circuit Low" },
  { code: "P0643", description: "Sensor Reference Voltage 'A' Circuit High" },
  { code: "P0645", description: "A/C Clutch Relay Control Circuit" },
  { code: "P0646", description: "A/C Clutch Relay Control Circuit Low" },
  { code: "P0647", description: "A/C Clutch Relay Control Circuit High" },
  { code: "P0650", description: "Malfunction Indicator Lamp (MIL) Control Circuit" },
  { code: "P0651", description: "Sensor Reference Voltage 'B' Circuit/Open" },
  { code: "P0652", description: "Sensor Reference Voltage 'B' Circuit Low" },
  { code: "P0653", description: "Sensor Reference Voltage 'B' Circuit High" },
  { code: "P0654", description: "Engine RPM Output Circuit" },
  { code: "P0656", description: "Fuel Level Output Circuit" }
];