// p07xx-transmission.js
export const P07XX_DTCS = [
  { code: "P0700", description: "Transmission Control System (MIL Request)" },
  { code: "P0701", description: "Transmission Control System Range/Performance" },
  { code: "P0702", description: "Transmission Control System Electrical" },
  { code: "P0703", description: "Brake Switch 'B' Circuit" },
  { code: "P0704", description: "Clutch Switch Input Circuit Malfunction" },
  { code: "P0705", description: "Transmission Range Sensor Circuit Malfunction (PRNDL Input)" },
  { code: "P0706", description: "Transmission Range Sensor Circuit Range/Performance" },
  { code: "P0707", description: "Transmission Range Sensor Circuit Low" },
  { code: "P0708", description: "Transmission Range Sensor Circuit High" },
  { code: "P0709", description: "Transmission Range Sensor Circuit Intermittent" },
  { code: "P0710", description: "Transmission Fluid Temperature Sensor 'A' Circuit" },
  { code: "P0711", description: "Transmission Fluid Temperature Sensor 'A' Circuit Range/Performance" },
  { code: "P0712", description: "Transmission Fluid Temperature Sensor 'A' Circuit Low" },
  { code: "P0713", description: "Transmission Fluid Temperature Sensor 'A' Circuit High" },
  { code: "P0715", description: "Input/Turbine Speed Sensor 'A' Circuit" },
  { code: "P0716", description: "Input/Turbine Speed Sensor 'A' Circuit Range/Performance" },
  { code: "P0717", description: "Input/Turbine Speed Sensor 'A' Circuit No Signal" },
  { code: "P0720", description: "Output Speed Sensor Circuit" },
  { code: "P0721", description: "Output Speed Sensor Circuit Range/Performance" },
  { code: "P0722", description: "Output Speed Sensor Circuit No Signal" },
  { code: "P0723", description: "Output Speed Sensor Circuit Intermittent" },
  { code: "P0725", description: "Engine Speed Input Circuit" },
  { code: "P0726", description: "Engine Speed Input Circuit Range/Performance" },
  { code: "P0727", description: "Engine Speed Input Circuit No Signal" },
  { code: "P0730", description: "Incorrect Gear Ratio" },
  { code: "P0731", description: "Gear 1 Incorrect Ratio" },
  { code: "P0732", description: "Gear 2 Incorrect Ratio" },
  { code: "P0733", description: "Gear 3 Incorrect Ratio" },
  { code: "P0734", description: "Gear 4 Incorrect Ratio" },
  { code: "P0735", description: "Gear 5 Incorrect Ratio" },
  { code: "P0736", description: "Reverse Incorrect Ratio" },
  { code: "P0740", description: "Torque Converter Clutch Circuit/Open" },
  { code: "P0741", description: "Torque Converter Clutch Circuit Performance or Stuck Off" },
  { code: "P0742", description: "Torque Converter Clutch Circuit Stuck On" },
  { code: "P0743", description: "Torque Converter Clutch Circuit Electrical" },
  { code: "P0744", description: "Torque Converter Clutch Circuit Intermittent" },
  { code: "P0745", description: "Pressure Control Solenoid 'A'" },
  { code: "P0746", description: "Pressure Control Solenoid 'A' Performance or Stuck Off" },
  { code: "P0747", description: "Pressure Control Solenoid 'A' Stuck On" },
  { code: "P0748", description: "Pressure Control Solenoid 'A' Electrical" },
  { code: "P0750", description: "Shift Solenoid 'A'" },
  { code: "P0751", description: "Shift Solenoid 'A' Performance or Stuck Off" },
  { code: "P0752", description: "Shift Solenoid 'A' Stuck On" },
  { code: "P0753", description: "Shift Solenoid 'A' Electrical" },
  { code: "P0755", description: "Shift Solenoid 'B'" },
  { code: "P0756", description: "Shift Solenoid 'B' Performance or Stuck Off" },
  { code: "P0757", description: "Shift Solenoid 'B' Stuck On" },
  { code: "P0758", description: "Shift Solenoid 'B' Electrical" },
  { code: "P0760", description: "Shift Solenoid 'C'" },
  { code: "P0761", description: "Shift Solenoid 'C' Performance or Stuck Off" },
  { code: "P0762", description: "Shift Solenoid 'C' Stuck On" },
  { code: "P0763", description: "Shift Solenoid 'C' Electrical" },
  { code: "P0765", description: "Shift Solenoid 'D'" },
  { code: "P0766", description: "Shift Solenoid 'D' Performance or Stuck Off" },
  { code: "P0767", description: "Shift Solenoid 'D' Stuck On" },
  { code: "P0768", description: "Shift Solenoid 'D' Electrical" },
  { code: "P0770", description: "Shift Solenoid 'E'" },
  { code: "P0771", description: "Shift Solenoid 'E' Performance or Stuck Off" },
  { code: "P0772", description: "Shift Solenoid 'E' Stuck On" },
  { code: "P0773", description: "Shift Solenoid 'E' Electrical" },
  { code: "P0780", description: "Shift Error" },
  { code: "P0781", description: "1-2 Shift" },
  { code: "P0782", description: "2-3 Shift" },
  { code: "P0783", description: "3-4 Shift" },
  { code: "P0784", description: "4-5 Shift" },
  { code: "P0785", description: "Shift/Timing Solenoid" },
  { code: "P0786", description: "Shift/Timing Solenoid Range/Performance" },
  { code: "P0787", description: "Shift/Timing Solenoid Low" },
  { code: "P0788", description: "Shift/Timing Solenoid High" }
];