import { DTC } from '../../types/dtc.types';

export const P08XX_DTCS: DTC[] = [
  { code: "P0800", description: "Transfer Case Control System (MIL Request)" },
  { code: "P0801", description: "Reverse Inhibit Control Circuit" },
  { code: "P0802", description: "Transmission Control System MIL Request Circuit/Open" },
  { code: "P0803", description: "1-4 Upshift (Skip Shift) Solenoid Control Circuit" },
  { code: "P0804", description: "1-4 Upshift (Skip Shift) Lamp Control Circuit" },
  { code: "P0805", description: "Clutch Position Sensor Circuit" },
  { code: "P0806", description: "Clutch Position Sensor Circuit Range/Performance" },
  { code: "P0807", description: "Clutch Position Sensor Circuit Low" },
  { code: "P0808", description: "Clutch Position Sensor Circuit High" },
  { code: "P0809", description: "Clutch Position Sensor Circuit Intermittent" },
  { code: "P0810", description: "Clutch Position Control Error" },
  { code: "P0811", description: "Excessive Clutch Slippage" },
  { code: "P0812", description: "Reverse Input Circuit" },
  { code: "P0813", description: "Reverse Output Circuit" },
  { code: "P0814", description: "Transmission Range Display Circuit" },
  { code: "P0815", description: "Upshift Switch Circuit" },
  { code: "P0816", description: "Downshift Switch Circuit" },
  { code: "P0817", description: "Starter Disable Circuit" },
  { code: "P0818", description: "Driveline Disconnect Switch Input Circuit" },
  { code: "P0819", description: "Up and Down Shift Switch to Transmission Range Correlation" },
  { code: "P0820", description: "Gear Lever X-Y Position Sensor Circuit" },
  { code: "P0821", description: "Gear Lever X Position Circuit" },
  { code: "P0822", description: "Gear Lever Y Position Circuit" },
  { code: "P0823", description: "Gear Lever X Position Circuit Intermittent" },
  { code: "P0824", description: "Gear Lever Y Position Circuit Intermittent" },
  { code: "P0825", description: "Gear Lever Push-Pull Switch (Shift Anticipate)" },
  { code: "P0826", description: "Up and Down Shift Switch Circuit" },
  { code: "P0827", description: "Up and Down Shift Switch Circuit Low" },
  { code: "P0828", description: "Up and Down Shift Switch Circuit High" },
  { code: "P0829", description: "5-6 Shift" },
  { code: "P0830", description: "Clutch Pedal Switch 'A' Circuit" },
  { code: "P0831", description: "Clutch Pedal Switch 'A' Circuit Low" },
  { code: "P0832", description: "Clutch Pedal Switch 'A' Circuit High" },
  { code: "P0833", description: "Clutch Pedal Switch 'B' Circuit" },
  { code: "P0834", description: "Clutch Pedal Switch 'B' Circuit Low" },
  { code: "P0835", description: "Clutch Pedal Switch 'B' Circuit High" },
  { code: "P0836", description: "Four Wheel Drive (4WD) Switch Circuit" },
  { code: "P0837", description: "Four Wheel Drive (4WD) Switch Circuit Range/Performance" },
  { code: "P0838", description: "Four Wheel Drive (4WD) Switch Circuit Low" },
  { code: "P0839", description: "Four Wheel Drive (4WD) Switch Circuit High" },
  { code: "P0840", description: "Transmission Fluid Pressure Sensor/Switch 'A' Circuit" },
  { code: "P0841", description: "Transmission Fluid Pressure Sensor/Switch 'A' Circuit Range/Performance" },
  { code: "P0842", description: "Transmission Fluid Pressure Sensor/Switch 'A' Circuit Low" },
  { code: "P0843", description: "Transmission Fluid Pressure Sensor/Switch 'A' Circuit High" },
  { code: "P0844", description: "Transmission Fluid Pressure Sensor/Switch 'A' Circuit Intermittent" },
  { code: "P0845", description: "Transmission Fluid Pressure Sensor/Switch 'B' Circuit" },
  { code: "P0846", description: "Transmission Fluid Pressure Sensor/Switch 'B' Circuit Range/Performance" },
  { code: "P0847", description: "Transmission Fluid Pressure Sensor/Switch 'B' Circuit Low" },
  { code: "P0848", description: "Transmission Fluid Pressure Sensor/Switch 'B' Circuit High" },
  { code: "P0849", description: "Transmission Fluid Pressure Sensor/Switch 'B' Circuit Intermittent" },
  { code: "P0850", description: "Park/Neutral Switch Input Circuit" },
  { code: "P0851", description: "Park/Neutral Switch Input Circuit Low" },
  { code: "P0852", description: "Park/Neutral Switch Input Circuit High" },
  { code: "P0853", description: "Drive Switch Input Circuit" },
  { code: "P0854", description: "Drive Switch Input Circuit Low" },
  { code: "P0855", description: "Drive Switch Input Circuit High" },
  { code: "P0856", description: "Traction Control Input Signal" },
  { code: "P0857", description: "Traction Control Input Signal Range/Performance" },
  { code: "P0858", description: "Traction Control Input Signal Low" },
  { code: "P0859", description: "Traction Control Input Signal High" },
  { code: "P0860", description: "Gear Shift Module Communication Circuit" },
  { code: "P0861", description: "Gear Shift Module Communication Circuit Low" },
  { code: "P0862", description: "Gear Shift Module Communication Circuit High" },
  { code: "P0863", description: "TCM Communication Circuit" },
  { code: "P0864", description: "TCM Communication Circuit Range/Performance" },
  { code: "P0865", description: "TCM Communication Circuit Low" },
  { code: "P0866", description: "TCM Communication Circuit High" },
  { code: "P0867", description: "Transmission Fluid Pressure" },
  { code: "P0868", description: "Transmission Fluid Pressure Low" },
  { code: "P0869", description: "Transmission Fluid Pressure High" },
  { code: "P0870", description: "Transmission Fluid Pressure Sensor/Switch 'C' Circuit" },
  { code: "P0871", description: "Transmission Fluid Pressure Sensor/Switch 'C' Circuit Range/Performance" },
  { code: "P0872", description: "Transmission Fluid Pressure Sensor/Switch 'C' Circuit Low" },
  { code: "P0873", description: "Transmission Fluid Pressure Sensor/Switch 'C' Circuit High" },
  { code: "P0874", description: "Transmission Fluid Pressure Sensor/Switch 'C' Circuit Intermittent" },
  { code: "P0875", description: "Transmission Fluid Pressure Sensor/Switch 'D' Circuit" },
  { code: "P0876", description: "Transmission Fluid Pressure Sensor/Switch 'D' Circuit Range/Performance" },
  { code: "P0877", description: "Transmission Fluid Pressure Sensor/Switch 'D' Circuit Low" },
  { code: "P0878", description: "Transmission Fluid Pressure Sensor/Switch 'D' Circuit High" },
  { code: "P0879", description: "Transmission Fluid Pressure Sensor/Switch 'D' Circuit Intermittent" },
  { code: "P0880", description: "TCM Power Input Signal" },
  { code: "P0881", description: "TCM Power Input Signal Range/Performance" },
  { code: "P0882", description: "TCM Power Input Signal Low" },
  { code: "P0883", description: "TCM Power Input Signal High" },
  { code: "P0884", description: "TCM Power Input Signal Intermittent" },
  { code: "P0885", description: "TCM Power Relay Control Circuit/Open" },
  { code: "P0886", description: "TCM Power Relay Control Circuit Low" },
  { code: "P0887", description: "TCM Power Relay Control Circuit High" },
  { code: "P0888", description: "TCM Power Relay Sense Circuit" },
  { code: "P0889", description: "TCM Power Relay Sense Circuit Range/Performance" },
  { code: "P0890", description: "TCM Power Relay Sense Circuit Low" },
  { code: "P0891", description: "TCM Power Relay Sense Circuit High" },
  { code: "P0892", description: "TCM Power Relay Sense Circuit Intermittent" },
  { code: "P0893", description: "Multiple Gears Engaged" },
  { code: "P0894", description: "Transmission Component Slipping" },
  { code: "P0895", description: "Shift Time Too Short" },
  { code: "P0896", description: "Shift Time Too Long" },
  { code: "P0897", description: "Transmission Fluid Deteriorated" },
  { code: "P0898", description: "Transmission Control System MIL Request Circuit Low" },
  { code: "P0899", description: "Transmission Control System MIL Request Circuit High" }
];