import { DTC } from '../../types/dtc.types';

export const P09XX_DTCS: DTC[] = [
  { code: "P0900", description: "Clutch Actuator Circuit/Open" },
  { code: "P0901", description: "Clutch Actuator Circuit Range/Performance" },
  { code: "P0902", description: "Clutch Actuator Circuit Low" },
  { code: "P0903", description: "Clutch Actuator Circuit High" },
  { code: "P0904", description: "Gate Select Position Circuit" },
  { code: "P0905", description: "Gate Select Position Circuit Range/Performance" },
  { code: "P0906", description: "Gate Select Position Circuit Low" },
  { code: "P0907", description: "Gate Select Position Circuit High" },
  { code: "P0908", description: "Gate Select Position Circuit Intermittent" },
  { code: "P0909", description: "Gate Select Control Error" },
  { code: "P0910", description: "Gate Select Actuator Circuit/Open" },
  { code: "P0911", description: "Gate Select Actuator Circuit Range/Performance" },
  { code: "P0912", description: "Gate Select Actuator Circuit Low" },
  { code: "P0913", description: "Gate Select Actuator Circuit High" },
  { code: "P0914", description: "Gear Shift Position Circuit" },
  { code: "P0915", description: "Gear Shift Position Circuit Range/Performance" },
  { code: "P0916", description: "Gear Shift Position Circuit Low" },
  { code: "P0917", description: "Gear Shift Position Circuit High" },
  { code: "P0918", description: "Gear Shift Position Circuit Intermittent" },
  { code: "P0919", description: "Gear Shift Position Control Error" },
  { code: "P0920", description: "Gear Shift Forward Actuator Circuit/Open" },
  { code: "P0921", description: "Gear Shift Forward Actuator Circuit Range/Performance" },
  { code: "P0922", description: "Gear Shift Forward Actuator Circuit Low" },
  { code: "P0923", description: "Gear Shift Forward Actuator Circuit High" },
  { code: "P0924", description: "Gear Shift Reverse Actuator Circuit/Open" },
  { code: "P0925", description: "Gear Shift Reverse Actuator Circuit Range/Performance" },
  { code: "P0926", description: "Gear Shift Reverse Actuator Circuit Low" },
  { code: "P0927", description: "Gear Shift Reverse Actuator Circuit High" },
  { code: "P0928", description: "Gear Shift Lock Solenoid Control Circuit/Open" },
  { code: "P0929", description: "Gear Shift Lock Solenoid Control Circuit Range/Performance" },
  { code: "P0930", description: "Gear Shift Lock Solenoid Control Circuit Low" },
  { code: "P0931", description: "Gear Shift Lock Solenoid Control Circuit High" },
  { code: "P0932", description: "Hydraulic Pressure Sensor Circuit" },
  { code: "P0933", description: "Hydraulic Pressure Sensor Range/Performance" },
  { code: "P0934", description: "Hydraulic Pressure Sensor Circuit Low" },
  { code: "P0935", description: "Hydraulic Pressure Sensor Circuit High" },
  { code: "P0936", description: "Hydraulic Pressure Sensor Circuit Intermittent" },
  { code: "P0937", description: "Hydraulic Oil Temperature Sensor Circuit" },
  { code: "P0938", description: "Hydraulic Oil Temperature Sensor Range/Performance" },
  { code: "P0939", description: "Hydraulic Oil Temperature Sensor Circuit Low" },
  { code: "P0940", description: "Hydraulic Oil Temperature Sensor Circuit High" },
  { code: "P0941", description: "Hydraulic Oil Temperature Sensor Circuit Intermittent" },
  { code: "P0942", description: "Hydraulic Pressure Unit" },
  { code: "P0943", description: "Hydraulic Pressure Unit Cycling Period Too Short" },
  { code: "P0944", description: "Hydraulic Pressure Unit Loss of Pressure" },
  { code: "P0945", description: "Hydraulic Pump Relay Circuit/Open" },
  { code: "P0946", description: "Hydraulic Pump Relay Circuit Range/Performance" },
  { code: "P0947", description: "Hydraulic Pump Relay Circuit Low" },
  { code: "P0948", description: "Hydraulic Pump Relay Circuit High" },
  { code: "P0949", description: "Auto Shift Manual Adaptive Learning Not Complete" },
  { code: "P0950", description: "Auto Shift Manual Control Circuit" },
  { code: "P0951", description: "Auto Shift Manual Control Circuit Range/Performance" },
  { code: "P0952", description: "Auto Shift Manual Control Circuit Low" },
  { code: "P0953", description: "Auto Shift Manual Control Circuit High" },
  { code: "P0954", description: "Auto Shift Manual Control Circuit Intermittent" },
  { code: "P0955", description: "Auto Shift Manual Mode Circuit" },
  { code: "P0956", description: "Auto Shift Manual Mode Circuit Range/Performance" },
  { code: "P0957", description: "Auto Shift Manual Mode Circuit Low" },
  { code: "P0958", description: "Auto Shift Manual Mode Circuit High" },
  { code: "P0959", description: "Auto Shift Manual Mode Circuit Intermittent" },
  { code: "P0960", description: "Pressure Control Solenoid 'A' Control Circuit/Open" },
  { code: "P0961", description: "Pressure Control Solenoid 'A' Control Circuit Range/Performance" },
  { code: "P0962", description: "Pressure Control Solenoid 'A' Control Circuit Low" },
  { code: "P0963", description: "Pressure Control Solenoid 'A' Control Circuit High" },
  { code: "P0964", description: "Pressure Control Solenoid 'B' Control Circuit/Open" },
  { code: "P0965", description: "Pressure Control Solenoid 'B' Control Circuit Range/Performance" },
  { code: "P0966", description: "Pressure Control Solenoid 'B' Control Circuit Low" },
  { code: "P0967", description: "Pressure Control Solenoid 'B' Control Circuit High" },
  { code: "P0968", description: "Pressure Control Solenoid 'C' Control Circuit/Open" },
  { code: "P0969", description: "Pressure Control Solenoid 'C' Control Circuit Range/Performance" },
  { code: "P0970", description: "Pressure Control Solenoid 'C' Control Circuit Low" },
  { code: "P0971", description: "Pressure Control Solenoid 'C' Control Circuit High" },
  { code: "P0972", description: "Shift Solenoid 'A' Control Circuit Range/Performance" },
  { code: "P0973", description: "Shift Solenoid 'A' Control Circuit Low" },
  { code: "P0974", description: "Shift Solenoid 'A' Control Circuit High" },
  { code: "P0975", description: "Shift Solenoid 'B' Control Circuit Range/Performance" },
  { code: "P0976", description: "Shift Solenoid 'B' Control Circuit Low" },
  { code: "P0977", description: "Shift Solenoid 'B' Control Circuit High" },
  { code: "P0978", description: "Shift Solenoid 'C' Control Circuit Range/Performance" },
  { code: "P0979", description: "Shift Solenoid 'C' Control Circuit Low" },
  { code: "P0980", description: "Shift Solenoid 'C' Control Circuit High" },
  { code: "P0981", description: "Shift Solenoid 'D' Control Circuit Range/Performance" },
  { code: "P0982", description: "Shift Solenoid 'D' Control Circuit Low" },
  { code: "P0983", description: "Shift Solenoid 'D' Control Circuit High" },
  { code: "P0984", description: "Shift Solenoid 'E' Control Circuit Range/Performance" },
  { code: "P0985", description: "Shift Solenoid 'E' Control Circuit Low" },
  { code: "P0986", description: "Shift Solenoid 'E' Control Circuit High" },
  { code: "P0987", description: "Transmission Fluid Pressure Sensor/Switch 'E' Circuit" },
  { code: "P0988", description: "Transmission Fluid Pressure Sensor/Switch 'E' Circuit Range/Performance" },
  { code: "P0989", description: "Transmission Fluid Pressure Sensor/Switch 'E' Circuit Low" },
  { code: "P0990", description: "Transmission Fluid Pressure Sensor/Switch 'E' Circuit High" },
  { code: "P0991", description: "Transmission Fluid Pressure Sensor/Switch 'E' Circuit Intermittent" },
  { code: "P0992", description: "Transmission Fluid Pressure Sensor/Switch 'F' Circuit" },
  { code: "P0993", description: "Transmission Fluid Pressure Sensor/Switch 'F' Circuit Range/Performance" },
  { code: "P0994", description: "Transmission Fluid Pressure Sensor/Switch 'F' Circuit Low" },
  { code: "P0995", description: "Transmission Fluid Pressure Sensor/Switch 'F' Circuit High" },
  { code: "P0996", description: "Transmission Fluid Pressure Sensor/Switch 'F' Circuit Intermittent" },
  { code: "P0997", description: "Shift Solenoid 'F' Control Circuit Range/Performance" },
  { code: "P0998", description: "Shift Solenoid 'F' Control Circuit Low" },
  { code: "P0999", description: "Shift Solenoid 'F' Control Circuit High" }
];