import { DTC } from '../../types/dtc.types';

export const P0AXX_DTCS: DTC[] = [
  { code: "P0A00", description: "Motor Electronics Coolant Temperature Sensor Circuit" },
  { code: "P0A01", description: "Motor Electronics Coolant Temperature Sensor Circuit Range/Performance" },
  { code: "P0A02", description: "Motor Electronics Coolant Temperature Sensor Circuit Low" },
  { code: "P0A03", description: "Motor Electronics Coolant Temperature Sensor Circuit High" },
  { code: "P0A04", description: "Motor Electronics Coolant Temperature Sensor Circuit Intermittent" },
  { code: "P0A05", description: "Motor Electronics Coolant Pump Control Circuit/Open" },
  { code: "P0A06", description: "Motor Electronics Coolant Pump Control Circuit Low" },
  { code: "P0A07", description: "Motor Electronics Coolant Pump Control Circuit High" },
  { code: "P0A08", description: "DC/DC Converter Status Circuit" },
  { code: "P0A09", description: "DC/DC Converter Status Circuit Low Input" },
  { code: "P0A10", description: "DC/DC Converter Status Circuit High Input" },
  { code: "P0A11", description: "DC/DC Converter Enable Circuit/Open" },
  { code: "P0A12", description: "DC/DC Converter Enable Circuit Low" },
  { code: "P0A13", description: "DC/DC Converter Enable Circuit High" },
  { code: "P0A14", description: "Engine Mount Control Circuit/Open" },
  { code: "P0A15", description: "Engine Mount Control Circuit Low" },
  { code: "P0A16", description: "Engine Mount Control Circuit High" },
  { code: "P0A17", description: "Motor Torque Sensor Circuit" },
  { code: "P0A18", description: "Motor Torque Sensor Circuit Range/Performance" },
  { code: "P0A19", description: "Motor Torque Sensor Circuit Low" },
  { code: "P0A20", description: "Motor Torque Sensor Circuit High" },
  { code: "P0A21", description: "Motor Torque Sensor Circuit Intermittent" },
  { code: "P0A22", description: "Generator Torque Sensor Circuit" },
  { code: "P0A23", description: "Generator Torque Sensor Circuit Range/Performance" },
  { code: "P0A24", description: "Generator Torque Sensor Circuit Low" },
  { code: "P0A25", description: "Generator Torque Sensor Circuit High" },
  { code: "P0A26", description: "Generator Torque Sensor Circuit Intermittent" },
  { code: "P0A27", description: "Battery Power Off Circuit" },
  { code: "P0A28", description: "Battery Power Off Circuit Low" },
  { code: "P0A29", description: "Battery Power Off Circuit High" }
];