// p20xx-fuel-air-extended.js
export const P20XX_DTCS = [
  { code: "P2000", description: "NOx Trap Efficiency Below Threshold", location: "Bank 1" },
  { code: "P2001", description: "NOx Trap Efficiency Below Threshold", location: "Bank 2" },
  { code: "P2002", description: "Particulate Trap Efficiency Below Threshold", location: "Bank 1" },
  { code: "P2003", description: "Particulate Trap Efficiency Below Threshold", location: "Bank 2" },
  { code: "P2004", description: "Intake Manifold Runner Control Stuck Open", location: "Bank 1" },
  { code: "P2005", description: "Intake Manifold Runner Control Stuck Open", location: "Bank 2" },
  { code: "P2006", description: "Intake Manifold Runner Control Stuck Closed", location: "Bank 1" },
  { code: "P2007", description: "Intake Manifold Runner Control Stuck Closed", location: "Bank 2" },
  { code: "P2008", description: "Intake Manifold Runner Control Circuit/Open", location: "Bank 1" },
  { code: "P2009", description: "Intake Manifold Runner Control Circuit Low", location: "Bank 1" },
  { code: "P2010", description: "Intake Manifold Runner Control Circuit High", location: "Bank 1" },
  { code: "P2011", description: "Intake Manifold Runner Control Circuit/Open", location: "Bank 2" },
  { code: "P2012", description: "Intake Manifold Runner Control Circuit Low", location: "Bank 2" },
  { code: "P2013", description: "Intake Manifold Runner Control Circuit High", location: "Bank 2" },
  { code: "P2014", description: "Intake Manifold Runner Position Sensor/Switch Circuit", location: "Bank 1" },
  { code: "P2015", description: "Intake Manifold Runner Position Sensor/Switch Circuit Range/Performance", location: "Bank 1" },
  { code: "P2016", description: "Intake Manifold Runner Position Sensor/Switch Circuit Low", location: "Bank 1" },
  { code: "P2017", description: "Intake Manifold Runner Position Sensor/Switch Circuit High", location: "Bank 1" },
  { code: "P2018", description: "Intake Manifold Runner Position Sensor/Switch Circuit Intermittent", location: "Bank 1" },
  { code: "P2019", description: "Intake Manifold Runner Position Sensor/Switch Circuit", location: "Bank 2" },
  { code: "P2020", description: "Intake Manifold Runner Position Sensor/Switch Circuit Range/Performance", location: "Bank 2" },
  { code: "P2021", description: "Intake Manifold Runner Position Sensor/Switch Circuit Low", location: "Bank 2" },
  { code: "P2022", description: "Intake Manifold Runner Position Sensor/Switch Circuit High", location: "Bank 2" },
  { code: "P2023", description: "Intake Manifold Runner Position Sensor/Switch Circuit Intermittent", location: "Bank 2" },
  { code: "P2024", description: "Evaporative Emissions (EVAP) Fuel Vapor Temperature Sensor Circuit" },
  { code: "P2031", description: "Exhaust Gas Temperature Sensor Circuit", location: "Bank 1 Sensor 2" },
  { code: "P2032", description: "Exhaust Gas Temperature Sensor Circuit Low", location: "Bank 1 Sensor 2" },
  { code: "P2033", description: "Exhaust Gas Temperature Sensor Circuit High", location: "Bank 1 Sensor 2" },
  { code: "P2034", description: "Exhaust Gas Temperature Sensor Circuit", location: "Bank 2 Sensor 2" },
  { code: "P2035", description: "Exhaust Gas Temperature Sensor Circuit Low", location: "Bank 2 Sensor 2" },
  { code: "P2036", description: "Exhaust Gas Temperature Sensor Circuit High", location: "Bank 2 Sensor 2" },
  { code: "P2047", description: "Reductant Injector Circuit/Open", location: "Bank 1 Unit 1" },
  { code: "P2048", description: "Reductant Injector Circuit Low", location: "Bank 1 Unit 1" },
  { code: "P2049", description: "Reductant Injector Circuit High", location: "Bank 1 Unit 1" },
  { code: "P2050", description: "Reductant Injector Circuit/Open", location: "Bank 2 Unit 1" },
  { code: "P2051", description: "Reductant Injector Circuit Low", location: "Bank 2 Unit 1" },
  { code: "P2052", description: "Reductant Injector Circuit High", location: "Bank 2 Unit 1" },
  { code: "P2070", description: "Intake Manifold Tuning (IMT) Valve Stuck Open" },
  { code: "P2071", description: "Intake Manifold Tuning (IMT) Valve Stuck Closed" },
  { code: "P2080", description: "Exhaust Gas Temperature Sensor Circuit Range/Performance", location: "Bank 1 Sensor 1" },
  { code: "P2081", description: "Exhaust Gas Temperature Sensor Circuit Intermittent", location: "Bank 1 Sensor 1" },
  { code: "P2082", description: "Exhaust Gas Temperature Sensor Circuit Range/Performance", location: "Bank 2 Sensor 1" },
  { code: "P2083", description: "Exhaust Gas Temperature Sensor Circuit Intermittent", location: "Bank 2 Sensor 1" },
  { code: "P2096", description: "Post Catalyst Fuel Trim System Too Lean", location: "Bank 1" },
  { code: "P2097", description: "Post Catalyst Fuel Trim System Too Rich", location: "Bank 1" },
  { code: "P2098", description: "Post Catalyst Fuel Trim System Too Lean", location: "Bank 2" },
  { code: "P2099", description: "Post Catalyst Fuel Trim System Too Rich", location: "Bank 2" }
];