import { DTC } from '../../types/dtc.types';

export const P21XX_DTCS: DTC[] = [
  { code: "P2100", description: "Throttle Actuator Control Motor Circuit/Open" },
  { code: "P2101", description: "Throttle Actuator Control Motor Circuit Range/Performance" },
  { code: "P2102", description: "Throttle Actuator Control Motor Circuit Low" },
  { code: "P2103", description: "Throttle Actuator Control Motor Circuit High" },
  { code: "P2104", description: "Throttle Actuator Control System - Forced Idle" },
  { code: "P2105", description: "Throttle Actuator Control System - Forced Engine Shutdown" },
  { code: "P2106", description: "Throttle Actuator Control System - Forced Limited Power" },
  { code: "P2107", description: "Throttle Actuator Control Module Processor" },
  { code: "P2108", description: "Throttle Actuator Control Module Performance" },
  { code: "P2109", description: "Throttle/Pedal Position Sensor 'A' Minimum Stop Performance" },
  { code: "P2110", description: "Throttle Actuator Control System - Forced Limited RPM" },
  { code: "P2111", description: "Throttle Actuator Control System - Stuck Open" },
  { code: "P2112", description: "Throttle Actuator Control System - Stuck Closed" },
  { code: "P2113", description: "Throttle/Pedal Position Sensor 'B' Minimum Stop Performance" },
  { code: "P2114", description: "Throttle/Pedal Position Sensor 'C' Minimum Stop Performance" },
  { code: "P2115", description: "Throttle/Pedal Position Sensor 'D' Minimum Stop Performance" },
  { code: "P2116", description: "Throttle/Pedal Position Sensor 'E' Minimum Stop Performance" },
  { code: "P2117", description: "Throttle/Pedal Position Sensor 'F' Minimum Stop Performance" },
  { code: "P2118", description: "Throttle Actuator Control Motor Current Range/Performance" },
  { code: "P2119", description: "Throttle Actuator Control Throttle Body Range/Performance" },
  { code: "P2120", description: "Throttle/Pedal Position Sensor/Switch 'D' Circuit" },
  { code: "P2121", description: "Throttle/Pedal Position Sensor/Switch 'D' Circuit Range/Performance" },
  { code: "P2122", description: "Throttle/Pedal Position Sensor/Switch 'D' Circuit Low Input" },
  { code: "P2123", description: "Throttle/Pedal Position Sensor/Switch 'D' Circuit High Input" },
  { code: "P2124", description: "Throttle/Pedal Position Sensor/Switch 'D' Circuit Intermittent" },
  { code: "P2125", description: "Throttle/Pedal Position Sensor/Switch 'E' Circuit" },
  { code: "P2126", description: "Throttle/Pedal Position Sensor/Switch 'E' Circuit Range/Performance" },
  { code: "P2127", description: "Throttle/Pedal Position Sensor/Switch 'E' Circuit Low Input" },
  { code: "P2128", description: "Throttle/Pedal Position Sensor/Switch 'E' Circuit High Input" },
  { code: "P2129", description: "Throttle/Pedal Position Sensor/Switch 'E' Circuit Intermittent" },
  { code: "P2130", description: "Throttle/Pedal Position Sensor/Switch 'F' Circuit" },
  { code: "P2131", description: "Throttle/Pedal Position Sensor/Switch 'F' Circuit Range Performance" },
  { code: "P2132", description: "Throttle/Pedal Position Sensor/Switch 'F' Circuit Low Input" },
  { code: "P2133", description: "Throttle/Pedal Position Sensor/Switch 'F' Circuit High Input" },
  { code: "P2134", description: "Throttle/Pedal Position Sensor/Switch 'F' Circuit Intermittent" },
  { code: "P2135", description: "Throttle/Pedal Position Sensor/Switch 'A'/'B' Voltage Correlation" },
  { code: "P2136", description: "Throttle/Pedal Position Sensor/Switch 'A'/'C' Voltage Correlation" },
  { code: "P2137", description: "Throttle/Pedal Position Sensor/Switch 'B'/'C' Voltage Correlation" },
  { code: "P2138", description: "Throttle/Pedal Position Sensor/Switch 'D'/'E' Voltage Correlation" },
  { code: "P2139", description: "Throttle/Pedal Position Sensor/Switch 'D'/'F' Voltage Correlation" },
  { code: "P2140", description: "Throttle/Pedal Position Sensor/Switch 'E'/'F' Voltage Correlation" },
  { code: "P2141", description: "Exhaust Gas Recirculation Throttle Control Circuit Low" },
  { code: "P2142", description: "Exhaust Gas Recirculation Throttle Control Circuit High" },
  { code: "P2143", description: "Exhaust Gas Recirculation Vent Control Circuit/Open" },
  { code: "P2144", description: "Exhaust Gas Recirculation Vent Control Circuit Low" },
  { code: "P2145", description: "Exhaust Gas Recirculation Vent Control Circuit High" },
  { code: "P2146", description: "Fuel Injector Group 'A' Supply Voltage Circuit/Open" },
  { code: "P2147", description: "Fuel Injector Group 'A' Supply Voltage Circuit Low" },
  { code: "P2148", description: "Fuel Injector Group 'A' Supply Voltage Circuit High" },
  { code: "P2149", description: "Fuel Injector Group 'B' Supply Voltage Circuit/Open" },
  { code: "P2150", description: "Fuel Injector Group 'B' Supply Voltage Circuit Low" },
  { code: "P2151", description: "Fuel Injector Group 'B' Supply Voltage Circuit High" },
  { code: "P2152", description: "Fuel Injector Group 'C' Supply Voltage Circuit/Open" },
  { code: "P2153", description: "Fuel Injector Group 'C' Supply Voltage Circuit Low" },
  { code: "P2154", description: "Fuel Injector Group 'C' Supply Voltage Circuit High" },
  { code: "P2155", description: "Fuel Injector Group 'D' Supply Voltage Circuit/Open" },
  { code: "P2156", description: "Fuel Injector Group 'D' Supply Voltage Circuit Low" },
  { code: "P2157", description: "Fuel Injector Group 'D' Supply Voltage Circuit High" },
  { code: "P2158", description: "Vehicle Speed Sensor 'B'" },
  { code: "P2159", description: "Vehicle Speed Sensor 'B' Range/Performance" },
  { code: "P2160", description: "Vehicle Speed Sensor 'B' Circuit Low" },
  { code: "P2161", description: "Vehicle Speed Sensor 'B' Intermittent/Erratic" },
  { code: "P2162", description: "Vehicle Speed Sensor 'A' / 'B' Correlation" },
  { code: "P2163", description: "Throttle/Pedal Position Sensor 'A' Maximum Stop Performance" },
  { code: "P2164", description: "Throttle/Pedal Position Sensor 'B' Maximum Stop Performance" },
  { code: "P2165", description: "Throttle/Pedal Position Sensor 'C' Maximum Stop Performance" },
  { code: "P2166", description: "Throttle/Pedal Position Sensor 'D' Maximum Stop Performance" },
  { code: "P2167", description: "Throttle/Pedal Position Sensor 'E' Maximum Stop Performance" },
  { code: "P2168", description: "Throttle/Pedal Position Sensor 'F' Maximum Stop Performance" },
  { code: "P2169", description: "Exhaust Pressure Regulator Vent Solenoid Control Circuit/Open" },
  { code: "P2170", description: "Exhaust Pressure Regulator Vent Solenoid Control Circuit Low" },
  { code: "P2171", description: "Exhaust Pressure Regulator Vent Solenoid Control Circuit High" },
  { code: "P2172", description: "Throttle Actuator Control System - Sudden High Airflow Detected" },
  { code: "P2173", description: "Throttle Actuator Control System - High Airflow Detected" },
  { code: "P2174", description: "Throttle Actuator Control System - Sudden Low Airflow Detected" },
  { code: "P2175", description: "Throttle Actuator Control System - Low Airflow Detected" },
  { code: "P2176", description: "Throttle Actuator Control System - Idle Position Not Learned" },
  { code: "P2177", description: "System Too Lean Off Idle", location: "Bank 1" },
  { code: "P2178", description: "System Too Rich Off Idle", location: "Bank 1" },
  { code: "P2179", description: "System Too Lean Off Idle", location: "Bank 2" },
  { code: "P2180", description: "System Too Rich Off Idle", location: "Bank 2" },
  { code: "P2181", description: "Cooling System Performance" },
  { code: "P2182", description: "Engine Coolant Temperature Sensor 2 Circuit" },
  { code: "P2183", description: "Engine Coolant Temperature Sensor 2 Circuit Range/Performance" },
  { code: "P2184", description: "Engine Coolant Temperature Sensor 2 Circuit Low" },
  { code: "P2185", description: "Engine Coolant Temperature Sensor 2 Circuit High" },
  { code: "P2186", description: "Engine Coolant Temperature Sensor 2 Circuit Intermittent/Erratic" },
  { code: "P2187", description: "System Too Lean at Idle", location: "Bank 1" },
  { code: "P2188", description: "System Too Rich at Idle", location: "Bank 1" },
  { code: "P2189", description: "System Too Lean at Idle", location: "Bank 2" },
  { code: "P2190", description: "System Too Rich at Idle", location: "Bank 2" },
  { code: "P2191", description: "System Too Lean at Higher Load", location: "Bank 1" },
  { code: "P2192", description: "System Too Rich at Higher Load", location: "Bank 1" },
  { code: "P2193", description: "System Too Lean at Higher Load", location: "Bank 2" },
  { code: "P2194", description: "System Too Rich at Higher Load", location: "Bank 2" },
  { code: "P2195", description: "O2 Sensor Signal Stuck Lean", location: "Bank 1 Sensor 1" },
  { code: "P2196", description: "O2 Sensor Signal Stuck Rich", location: "Bank 1 Sensor 1" },
  { code: "P2197", description: "O2 Sensor Signal Stuck Lean", location: "Bank 2 Sensor 1" },
  { code: "P2198", description: "O2 Sensor Signal Stuck Rich", location: "Bank 2 Sensor 1" },
  { code: "P2199", description: "Intake Air Temperature Sensor 1/2 Correlation" }
];