import { DTC } from '../../types/dtc.types';

export const P22XX_DTCS: DTC[] = [
  { code: "P2200", description: "NOx Sensor Circuit", location: "Bank 1" },
  { code: "P2201", description: "NOx Sensor Circuit Range/Performance", location: "Bank 1" },
  { code: "P2202", description: "NOx Sensor Circuit Low Input", location: "Bank 1" },
  { code: "P2203", description: "NOx Sensor Circuit High Input", location: "Bank 1" },
  { code: "P2204", description: "NOx Sensor Circuit Intermittent Input", location: "Bank 1" },
  { code: "P2205", description: "NOx Sensor Heater Control Circuit/Open", location: "Bank 1" },
  { code: "P2206", description: "NOx Sensor Heater Control Circuit Low", location: "Bank 1" },
  { code: "P2207", description: "NOx Sensor Heater Control Circuit High", location: "Bank 1" },
  { code: "P2208", description: "NOx Sensor Heater Sense Circuit", location: "Bank 1" },
  { code: "P2209", description: "NOx Sensor Heater Sense Circuit Range/Performance", location: "Bank 1" },
  { code: "P2210", description: "NOx Sensor Heater Sense Circuit Low Input", location: "Bank 1" },
  { code: "P2211", description: "NOx Sensor Heater Sense Circuit High Input", location: "Bank 1" },
  { code: "P2212", description: "NOx Sensor Heater Sense Circuit Intermittent", location: "Bank 1" },
  { code: "P2213", description: "NOx Sensor Circuit", location: "Bank 2" },
  { code: "P2214", description: "NOx Sensor Circuit Range/Performance", location: "Bank 2" },
  { code: "P2215", description: "NOx Sensor Circuit Low Input", location: "Bank 2" },
  { code: "P2216", description: "NOx Sensor Circuit High Input", location: "Bank 2" },
  { code: "P2217", description: "NOx Sensor Circuit Intermittent Input", location: "Bank 2" },
  { code: "P2218", description: "NOx Sensor Heater Control Circuit/Open", location: "Bank 2" },
  { code: "P2219", description: "NOx Sensor Heater Control Circuit Low", location: "Bank 2" },
  { code: "P2220", description: "NOx Sensor Heater Control Circuit High", location: "Bank 2" },
  { code: "P2221", description: "NOx Sensor Heater Sense Circuit", location: "Bank 2" },
  { code: "P2222", description: "NOx Sensor Heater Sense Circuit Range/Performance", location: "Bank 2" },
  { code: "P2223", description: "NOx Sensor Heater Sense Circuit Low", location: "Bank 2" },
  { code: "P2224", description: "NOx Sensor Heater Sense Circuit High", location: "Bank 2" },
  { code: "P2225", description: "NOx Sensor Heater Sense Circuit Intermittent", location: "Bank 2" },
  { code: "P2226", description: "Barometric Pressure Circuit" },
  { code: "P2227", description: "Barometric Pressure Circuit Range/Performance" },
  { code: "P2228", description: "Barometric Pressure Circuit Low" },
  { code: "P2229", description: "Barometric Pressure Circuit High" },
  { code: "P2230", description: "Barometric Pressure Circuit Intermittent" },
  { code: "P2231", description: "O2 Sensor Signal Circuit Shorted to Heater Circuit", location: "Bank 1 Sensor 1" },
  { code: "P2232", description: "O2 Sensor Signal Circuit Shorted to Heater Circuit", location: "Bank 1 Sensor 2" },
  { code: "P2233", description: "O2 Sensor Signal Circuit Shorted to Heater Circuit", location: "Bank 1 Sensor 3" },
  { code: "P2234", description: "O2 Sensor Signal Circuit Shorted to Heater Circuit", location: "Bank 2 Sensor 1" },
  { code: "P2235", description: "O2 Sensor Signal Circuit Shorted to Heater Circuit", location: "Bank 2 Sensor 2" },
  { code: "P2236", description: "O2 Sensor Signal Circuit Shorted to Heater Circuit", location: "Bank 2 Sensor 3" },
  { code: "P2237", description: "O2 Sensor Positive Current Control Circuit/Open", location: "Bank 1 Sensor 1" },
  { code: "P2238", description: "O2 Sensor Positive Current Control Circuit Low", location: "Bank 1 Sensor 1" },
  { code: "P2239", description: "O2 Sensor Positive Current Control Circuit High", location: "Bank 1 Sensor 1" },
  { code: "P2240", description: "O2 Sensor Positive Current Control Circuit/Open", location: "Bank 2 Sensor 1" },
  { code: "P2241", description: "O2 Sensor Positive Current Control Circuit Low", location: "Bank 2 Sensor 1" },
  { code: "P2242", description: "O2 Sensor Positive Current Control Circuit High", location: "Bank 2 Sensor 1" },
  { code: "P2243", description: "O2 Sensor Reference Voltage Circuit/Open", location: "Bank 1 Sensor 1" },
  { code: "P2244", description: "O2 Sensor Reference Voltage Performance", location: "Bank 1 Sensor 1" },
  { code: "P2245", description: "O2 Sensor Reference Voltage Circuit Low", location: "Bank 1 Sensor 1" },
  { code: "P2246", description: "O2 Sensor Reference Voltage Circuit High", location: "Bank 1 Sensor 1" },
  { code: "P2247", description: "O2 Sensor Reference Voltage Circuit/Open", location: "Bank 2 Sensor 1" },
  { code: "P2248", description: "O2 Sensor Reference Voltage Performance", location: "Bank 2 Sensor 1" },
  { code: "P2249", description: "O2 Sensor Reference Voltage Circuit Low", location: "Bank 2 Sensor 1" },
  { code: "P2250", description: "O2 Sensor Reference Voltage Circuit High", location: "Bank 2 Sensor 1" },
  { code: "P2251", description: "O2 Sensor Negative Current Control Circuit/Open", location: "Bank 1 Sensor 1" },
  { code: "P2252", description: "O2 Sensor Negative Current Control Circuit Low", location: "Bank 1 Sensor 1" },
  { code: "P2253", description: "O2 Sensor Negative Current Control Circuit High", location: "Bank 1 Sensor 1" },
  { code: "P2254", description: "O2 Sensor Negative Current Control Circuit/Open", location: "Bank 2 Sensor 1" },
  { code: "P2255", description: "O2 Sensor Negative Current Control Circuit Low", location: "Bank 2 Sensor 1" },
  { code: "P2256", description: "O2 Sensor Negative Current Control Circuit High", location: "Bank 2 Sensor 1" },
  { code: "P2257", description: "Secondary Air Injection System Control 'A' Circuit Low" },
  { code: "P2258", description: "Secondary Air Injection System Control 'A' Circuit High" },
  { code: "P2259", description: "Secondary Air Injection System Control 'B' Circuit Low" },
  { code: "P2260", description: "Secondary Air Injection System Control 'B' Circuit High" },
  { code: "P2261", description: "Turbo/Super Charger Bypass Valve - Mechanical" },
  { code: "P2262", description: "Turbo Boost Pressure Not Detected - Mechanical" },
  { code: "P2263", description: "Turbo/Super Charger Boost System Performance" },
  { code: "P2264", description: "Water in Fuel Sensor Circuit" },
  { code: "P2265", description: "Water in Fuel Sensor Circuit Range/Performance" },
  { code: "P2266", description: "Water in Fuel Sensor Circuit Low" },
  { code: "P2267", description: "Water in Fuel Sensor Circuit High" },
  { code: "P2268", description: "Water in Fuel Sensor Circuit Intermittent" },
  { code: "P2269", description: "Water in Fuel Condition" },
  { code: "P2270", description: "O2 Sensor Signal Stuck Lean", location: "Bank 1 Sensor 2" },
  { code: "P2271", description: "O2 Sensor Signal Stuck Rich", location: "Bank 1 Sensor 2" },
  { code: "P2272", description: "O2 Sensor Signal Stuck Lean", location: "Bank 2 Sensor 2" },
  { code: "P2273", description: "O2 Sensor Signal Stuck Rich", location: "Bank 2 Sensor 2" },
  { code: "P2274", description: "O2 Sensor Signal Stuck Lean", location: "Bank 1 Sensor 3" },
  { code: "P2275", description: "O2 Sensor Signal Stuck Rich", location: "Bank 1 Sensor 3" },
  { code: "P2276", description: "O2 Sensor Signal Stuck Lean", location: "Bank 2 Sensor 3" },
  { code: "P2277", description: "O2 Sensor Signal Stuck Rich", location: "Bank 2 Sensor 3" },
  { code: "P2278", description: "O2 Sensor Signals Swapped", location: "Bank 1 Sensor 3/Bank 2 Sensor 3" },
  { code: "P2279", description: "Intake Air System Leak" },
  { code: "P2280", description: "Air Flow Restriction / Air Leak Between Air Filter and MAF" },
  { code: "P2281", description: "Air Leak Between MAF and Throttle Body" },
  { code: "P2282", description: "Air Leak Between Throttle Body and Intake Valves" },
  { code: "P2283", description: "Injector Control Pressure Sensor Circuit" },
  { code: "P2284", description: "Injector Control Pressure Sensor Circuit Range/Performance" },
  { code: "P2285", description: "Injector Control Pressure Sensor Circuit Low" },
  { code: "P2286", description: "Injector Control Pressure Sensor Circuit High" },
  { code: "P2287", description: "Injector Control Pressure Sensor Circuit Intermittent" },
  { code: "P2288", description: "Injector Control Pressure Too High" },
  { code: "P2289", description: "Injector Control Pressure Too High - Engine Off" },
  { code: "P2290", description: "Injector Control Pressure Too Low" },
  { code: "P2291", description: "Injector Control Pressure Too Low - Engine Cranking" },
  { code: "P2292", description: "Injector Control Pressure Erratic" },
  { code: "P2293", description: "Fuel Pressure Regulator 2 Performance" },
  { code: "P2294", description: "Fuel Pressure Regulator 2 Control Circuit" },
  { code: "P2295", description: "Fuel Pressure Regulator 2 Control Circuit Low" },
  { code: "P2296", description: "Fuel Pressure Regulator 2 Control Circuit High" },
  { code: "P2297", description: "O2 Sensor Out of Range During Deceleration", location: "Bank 1 Sensor 1" },
  { code: "P2298", description: "O2 Sensor Out of Range During Deceleration", location: "Bank 2 Sensor 1" },
  { code: "P2299", description: "Brake Pedal Position / Accelerator Pedal Position Incompatible" }
];