import { DTC } from '../../types/dtc.types';

export const P23XX_DTCS: DTC[] = [
  { code: "P2300", description: "Ignition Coil 'A' Primary Control Circuit Low" },
  { code: "P2301", description: "Ignition Coil 'A' Primary Control Circuit High" },
  { code: "P2302", description: "Ignition Coil 'A' Secondary Circuit" },
  { code: "P2303", description: "Ignition Coil 'B' Primary Control Circuit Low" },
  { code: "P2304", description: "Ignition Coil 'B' Primary Control Circuit High" },
  { code: "P2305", description: "Ignition Coil 'B' Secondary Circuit" },
  { code: "P2306", description: "Ignition Coil 'C' Primary Control Circuit Low" },
  { code: "P2307", description: "Ignition Coil 'C' Primary Control Circuit High" },
  { code: "P2308", description: "Ignition Coil 'C' Secondary Circuit" },
  { code: "P2309", description: "Ignition Coil 'D' Primary Control Circuit Low" },
  { code: "P2310", description: "Ignition Coil 'D' Primary Control Circuit High" },
  { code: "P2311", description: "Ignition Coil 'D' Secondary Circuit" },
  { code: "P2312", description: "Ignition Coil 'E' Primary Control Circuit Low" },
  { code: "P2313", description: "Ignition Coil 'E' Primary Control Circuit High" },
  { code: "P2314", description: "Ignition Coil 'E' Secondary Circuit" },
  { code: "P2315", description: "Ignition Coil 'F' Primary Control Circuit Low" },
  { code: "P2316", description: "Ignition Coil 'F' Primary Control Circuit High" },
  { code: "P2317", description: "Ignition Coil 'F' Secondary Circuit" },
  { code: "P2318", description: "Ignition Coil 'G' Primary Control Circuit Low" },
  { code: "P2319", description: "Ignition Coil 'G' Primary Control Circuit High" },
  { code: "P2320", description: "Ignition Coil 'G' Secondary Circuit" },
  { code: "P2321", description: "Ignition Coil 'H' Primary Control Circuit Low" },
  { code: "P2322", description: "Ignition Coil 'H' Primary Control Circuit High" },
  { code: "P2323", description: "Ignition Coil 'H' Secondary Circuit" },
  { code: "P2324", description: "Ignition Coil 'I' Primary Control Circuit Low" },
  { code: "P2325", description: "Ignition Coil 'I' Primary Control Circuit High" },
  { code: "P2326", description: "Ignition Coil 'I' Secondary Circuit" },
  { code: "P2327", description: "Ignition Coil 'J' Primary Control Circuit Low" },
  { code: "P2328", description: "Ignition Coil 'J' Primary Control Circuit High" },
  { code: "P2329", description: "Ignition Coil 'J' Secondary Circuit" },
  { code: "P2330", description: "Ignition Coil 'K' Primary Control Circuit Low" },
  { code: "P2331", description: "Ignition Coil 'K' Primary Control Circuit High" },
  { code: "P2332", description: "Ignition Coil 'K' Secondary Circuit" },
  { code: "P2333", description: "Ignition Coil 'L' Primary Control Circuit Low" },
  { code: "P2334", description: "Ignition Coil 'L' Primary Control Circuit High" },
  { code: "P2335", description: "Ignition Coil 'L' Secondary Circuit" },
  { code: "P2336", description: "Cylinder #1 Above Knock Threshold" },
  { code: "P2337", description: "Cylinder #2 Above Knock Threshold" },
  { code: "P2338", description: "Cylinder #3 Above Knock Threshold" },
  { code: "P2339", description: "Cylinder #4 Above Knock Threshold" },
  { code: "P2340", description: "Cylinder #5 Above Knock Threshold" },
  { code: "P2341", description: "Cylinder #6 Above Knock Threshold" },
  { code: "P2342", description: "Cylinder #7 Above Knock Threshold" },
  { code: "P2343", description: "Cylinder #8 Above Knock Threshold" },
  { code: "P2344", description: "Cylinder #9 Above Knock Threshold" },
  { code: "P2345", description: "Cylinder #10 Above Knock Threshold" },
  { code: "P2346", description: "Cylinder #11 Above Knock Threshold" },
  { code: "P2347", description: "Cylinder #12 Above Knock Threshold" }
];