import { DTC } from '../../types/dtc.types';

export const P24XX_DTCS: DTC[] = [
  { code: "P2400", description: "Evaporative Emission System Leak Detection Pump Control Circuit/Open" },
  { code: "P2401", description: "Evaporative Emission System Leak Detection Pump Control Circuit Low" },
  { code: "P2402", description: "Evaporative Emission System Leak Detection Pump Control Circuit High" },
  { code: "P2403", description: "Evaporative Emission System Leak Detection Pump Sense Circuit/Open" },
  { code: "P2404", description: "Evaporative Emission System Leak Detection Pump Sense Circuit Range/Performance" },
  { code: "P2405", description: "Evaporative Emission System Leak Detection Pump Sense Circuit Low" },
  { code: "P2406", description: "Evaporative Emission System Leak Detection Pump Sense Circuit High" },
  { code: "P2407", description: "Evaporative Emission System Leak Detection Pump Sense Circuit Intermittent/Erratic" },
  { code: "P2408", description: "Fuel Cap Sensor/Switch Circuit" },
  { code: "P2409", description: "Fuel Cap Sensor/Switch Circuit Range/Performance" },
  { code: "P2410", description: "Fuel Cap Sensor/Switch Circuit Low" },
  { code: "P2411", description: "Fuel Cap Sensor/Switch Circuit High" },
  { code: "P2412", description: "Fuel Cap Sensor/Switch Circuit Intermittent/Erratic" },
  { code: "P2413", description: "Exhaust Gas Recirculation System Performance" },
  { code: "P2414", description: "O2 Sensor Exhaust Sample Error", location: "Bank 1 Sensor 1" },
  { code: "P2415", description: "O2 Sensor Exhaust Sample Error", location: "Bank 2 Sensor 1" },
  { code: "P2416", description: "O2 Sensor Signals Swapped", location: "Bank 1 Sensor 2/Bank 1 Sensor 3" },
  { code: "P2417", description: "O2 Sensor Signals Swapped", location: "Bank 2 Sensor 2/Bank 2 Sensor 3" },
  { code: "P2418", description: "Evaporative Emission System Switching Valve Control Circuit/Open" },
  { code: "P2419", description: "Evaporative Emission System Switching Valve Control Circuit Low" },
  { code: "P2420", description: "Evaporative Emission System Switching Valve Control Circuit High" },
  { code: "P2421", description: "Evaporative Emission System Vent Valve Stuck Open" },
  { code: "P2422", description: "Evaporative Emission System Vent Valve Stuck Closed" },
  { code: "P2423", description: "HC Adsorption Catalyst Efficiency Below Threshold", location: "Bank 1" },
  { code: "P2424", description: "HC Adsorption Catalyst Efficiency Below Threshold", location: "Bank 2" },
  { code: "P2425", description: "Exhaust Gas Recirculation Cooling Valve Control Circuit/Open" },
  { code: "P2426", description: "Exhaust Gas Recirculation Cooling Valve Control Circuit Low" },
  { code: "P2427", description: "Exhaust Gas Recirculation Cooling Valve Control Circuit High" },
  { code: "P2428", description: "Exhaust Gas Temperature Too High", location: "Bank 1" },
  { code: "P2429", description: "Exhaust Gas Temperature Too High", location: "Bank 2" },
  { code: "P2430", description: "Secondary Air Injection System Air Flow/Pressure Sensor Circuit", location: "Bank 1" },
  { code: "P2431", description: "Secondary Air Injection System Air Flow/Pressure Sensor Circuit Range/Performance", location: "Bank 1" },
  { code: "P2432", description: "Secondary Air Injection System Air Flow/Pressure Sensor Circuit Low", location: "Bank 1" },
  { code: "P2433", description: "Secondary Air Injection System Air Flow/Pressure Sensor Circuit High", location: "Bank 1" },
  { code: "P2434", description: "Secondary Air Injection System Air Flow/Pressure Sensor Circuit Intermittent/Erratic", location: "Bank 1" },
  { code: "P2435", description: "Secondary Air Injection System Air Flow/Pressure Sensor Circuit", location: "Bank 2" },
  { code: "P2436", description: "Secondary Air Injection System Air Flow/Pressure Sensor Circuit Range/Performance", location: "Bank 2" },
  { code: "P2437", description: "Secondary Air Injection System Air Flow/Pressure Sensor Circuit Low", location: "Bank 2" },
  { code: "P2438", description: "Secondary Air Injection System Air Flow/Pressure Sensor Circuit High", location: "Bank 2" },
  { code: "P2439", description: "Secondary Air Injection System Air Flow/Pressure Sensor Circuit Intermittent/Erratic", location: "Bank 2" },
  { code: "P2440", description: "Secondary Air Injection System Switching Valve Stuck Open", location: "Bank 1" },
  { code: "P2441", description: "Secondary Air Injection System Switching Valve Stuck Closed", location: "Bank 1" },
  { code: "P2442", description: "Secondary Air Injection System Switching Valve Stuck Open", location: "Bank 2" },
  { code: "P2443", description: "Secondary Air Injection System Switching Valve Stuck Closed", location: "Bank 2" },
  { code: "P2444", description: "Secondary Air Injection System Pump Stuck On", location: "Bank 1" },
  { code: "P2445", description: "Secondary Air Injection System Pump Stuck Off", location: "Bank 1" },
  { code: "P2446", description: "Secondary Air Injection System Pump Stuck On", location: "Bank 2" },
  { code: "P2447", description: "Secondary Air Injection System Pump Stuck Off", location: "Bank 2" }
];