import { DTC } from '../../types/dtc.types';

export const P25XX_DTCS: DTC[] = [
  { code: "P2500", description: "Generator Lamp/L-Terminal Circuit Low" },
  { code: "P2501", description: "Generator Lamp/L-Terminal Circuit High" },
  { code: "P2502", description: "Charging System Voltage" },
  { code: "P2503", description: "Charging System Voltage Low" },
  { code: "P2504", description: "Charging System Voltage High" },
  { code: "P2505", description: "ECM/PCM Power Input Signal" },
  { code: "P2506", description: "ECM/PCM Power Input Signal Range/Performance" },
  { code: "P2507", description: "ECM/PCM Power Input Signal Low" },
  { code: "P2508", description: "ECM/PCM Power Input Signal High" },
  { code: "P2509", description: "ECM/PCM Power Input Signal Intermittent" },
  { code: "P2510", description: "ECM/PCM Power Relay Sense Circuit Range/Performance" },
  { code: "P2511", description: "ECM/PCM Power Relay Sense Circuit Intermittent" },
  { code: "P2512", description: "Event Data Recorder Request Circuit/Open" },
  { code: "P2513", description: "Event Data Recorder Request Circuit Low" },
  { code: "P2514", description: "Event Data Recorder Request Circuit High" },
  { code: "P2515", description: "A/C Refrigerant Pressure Sensor 'B' Circuit" },
  { code: "P2516", description: "A/C Refrigerant Pressure Sensor 'B' Circuit Range/Performance" },
  { code: "P2517", description: "A/C Refrigerant Pressure Sensor 'B' Circuit Low" },
  { code: "P2518", description: "A/C Refrigerant Pressure Sensor 'B' Circuit High" },
  { code: "P2519", description: "A/C Request 'A' Circuit" },
  { code: "P2520", description: "A/C Request 'A' Circuit Low" },
  { code: "P2521", description: "A/C Request 'A' Circuit High" },
  { code: "P2522", description: "A/C Request 'B' Circuit" },
  { code: "P2523", description: "A/C Request 'B' Circuit Low" },
  { code: "P2524", description: "A/C Request 'B' Circuit High" },
  { code: "P2525", description: "Vacuum Reservoir Pressure Sensor Circuit" },
  { code: "P2526", description: "Vacuum Reservoir Pressure Sensor Circuit Range/Performance" },
  { code: "P2527", description: "Vacuum Reservoir Pressure Sensor Circuit Low" },
  { code: "P2528", description: "Vacuum Reservoir Pressure Sensor Circuit High" },
  { code: "P2529", description: "Vacuum Reservoir Pressure Sensor Circuit Intermittent" },
  { code: "P2530", description: "Ignition Switch Run Position Circuit" },
  { code: "P2531", description: "Ignition Switch Run Position Circuit Low" },
  { code: "P2532", description: "Ignition Switch Run Position Circuit High" },
  { code: "P2533", description: "Ignition Switch Run/Start Position Circuit" },
  { code: "P2534", description: "Ignition Switch Run/Start Position Circuit Low" },
  { code: "P2535", description: "Ignition Switch Run/Start Position Circuit High" },
  { code: "P2536", description: "Ignition Switch Accessory Position Circuit" },
  { code: "P2537", description: "Ignition Switch Accessory Position Circuit Low" },
  { code: "P2538", description: "Ignition Switch Accessory Position Circuit High" },
  { code: "P2539", description: "Low Pressure Fuel System Sensor Circuit" },
  { code: "P2540", description: "Low Pressure Fuel System Sensor Circuit Range/Performance" },
  { code: "P2541", description: "Low Pressure Fuel System Sensor Circuit Low" },
  { code: "P2542", description: "Low Pressure Fuel System Sensor Circuit High" },
  { code: "P2543", description: "Low Pressure Fuel System Sensor Circuit Intermittent" },
  { code: "P2544", description: "Torque Management Request Input Signal 'A'" },
  { code: "P2545", description: "Torque Management Request Input Signal 'A' Range/Performance" },
  { code: "P2546", description: "Torque Management Request Input Signal 'A' Low" },
  { code: "P2547", description: "Torque Management Request Input Signal 'A' High" },
  { code: "P2548", description: "Torque Management Request Input Signal 'B'" },
  { code: "P2549", description: "Torque Management Request Input Signal 'B' Range/Performance" },
  { code: "P2550", description: "Torque Management Request Input Signal 'B' Low" },
  { code: "P2551", description: "Torque Management Request Input Signal 'B' High" },
  { code: "P2552", description: "Throttle/Fuel Inhibit Circuit" },
  { code: "P2553", description: "Throttle/Fuel Inhibit Circuit Range/Performance" },
  { code: "P2554", description: "Throttle/Fuel Inhibit Circuit Low" },
  { code: "P2555", description: "Throttle/Fuel Inhibit Circuit High" },
  { code: "P2556", description: "Engine Coolant Level Sensor/Switch Circuit" },
  { code: "P2557", description: "Engine Coolant Level Sensor/Switch Circuit Range/Performance" },
  { code: "P2558", description: "Engine Coolant Level Sensor/Switch Circuit Low" },
  { code: "P2559", description: "Engine Coolant Level Sensor/Switch Circuit High" },
  { code: "P2560", description: "Engine Coolant Level Low" },
  { code: "P2561", description: "A/C Control Module Requested MIL Illumination" },
  { code: "P2562", description: "Turbocharger Boost Control Position Sensor Circuit" },
  { code: "P2563", description: "Turbocharger Boost Control Position Sensor Circuit Range/Performance" },
  { code: "P2564", description: "Turbocharger Boost Control Position Sensor Circuit Low" },
  { code: "P2565", description: "Turbocharger Boost Control Position Sensor Circuit High" },
  { code: "P2566", description: "Turbocharger Boost Control Position Sensor Circuit Intermittent" },
  { code: "P2567", description: "Direct Ozone Reduction Catalyst Temperature Sensor Circuit" },
  { code: "P2568", description: "Direct Ozone Reduction Catalyst Temperature Sensor Circuit Range/Performance" },
  { code: "P2569", description: "Direct Ozone Reduction Catalyst Temperature Sensor Circuit Low" },
  { code: "P2570", description: "Direct Ozone Reduction Catalyst Temperature Sensor Circuit High" },
  { code: "P2571", description: "Direct Ozone Reduction Catalyst Temperature Sensor Circuit Intermittent/Erratic" },
  { code: "P2572", description: "Direct Ozone Reduction Catalyst Deterioration Sensor Circuit" },
  { code: "P2573", description: "Direct Ozone Reduction Catalyst Deterioration Sensor Circuit Range/Performance" },
  { code: "P2574", description: "Direct Ozone Reduction Catalyst Deterioration Sensor Circuit Low" },
  { code: "P2575", description: "Direct Ozone Reduction Catalyst Deterioration Sensor Circuit High" },
  { code: "P2576", description: "Direct Ozone Reduction Catalyst Deterioration Sensor Circuit Intermittent/Erratic" },
  { code: "P2577", description: "Direct Ozone Reduction Catalyst Efficiency Below Threshold" }
];