import { DTC } from '../../types/dtc.types';

export const P26XX_DTCS: DTC[] = [
  { code: "P2600", description: "Coolant Pump Control Circuit/Open" },
  { code: "P2601", description: "Coolant Pump Control Circuit Range/Performance" },
  { code: "P2602", description: "Coolant Pump Control Circuit Low" },
  { code: "P2603", description: "Coolant Pump Control Circuit High" },
  { code: "P2604", description: "Intake Air Heater 'A' Circuit Range/Performance" },
  { code: "P2605", description: "Intake Air Heater 'A' Circuit/Open" },
  { code: "P2606", description: "Intake Air Heater 'B' Circuit Range/Performance" },
  { code: "P2607", description: "Intake Air Heater 'B' Circuit Low" },
  { code: "P2608", description: "Intake Air Heater 'B' Circuit High" },
  { code: "P2609", description: "Intake Air Heater System Performance" },
  { code: "P2610", description: "ECM/PCM Internal Engine Off Timer Performance" },
  { code: "P2611", description: "A/C Refrigerant Distribution Valve Control Circuit/Open" },
  { code: "P2612", description: "A/C Refrigerant Distribution Valve Control Circuit Low" },
  { code: "P2613", description: "A/C Refrigerant Distribution Valve Control Circuit High" },
  { code: "P2614", description: "Camshaft Position Signal Output Circuit/Open" },
  { code: "P2615", description: "Camshaft Position Signal Output Circuit Low" },
  { code: "P2616", description: "Camshaft Position Signal Output Circuit High" },
  { code: "P2617", description: "Crankshaft Position Signal Output Circuit/Open" },
  { code: "P2618", description: "Crankshaft Position Signal Output Circuit Low" },
  { code: "P2619", description: "Crankshaft Position Signal Output Circuit High" },
  { code: "P2620", description: "Throttle Position Output Circuit/Open" },
  { code: "P2621", description: "Throttle Position Output Circuit Low" },
  { code: "P2622", description: "Throttle Position Output Circuit High" },
  { code: "P2623", description: "Injector Control Pressure Regulator Circuit/Open" },
  { code: "P2624", description: "Injector Control Pressure Regulator Circuit Low" },
  { code: "P2625", description: "Injector Control Pressure Regulator Circuit High" },
  { code: "P2626", description: "O2 Sensor Pumping Current Trim Circuit/Open", location: "Bank 1 Sensor 1" },
  { code: "P2627", description: "O2 Sensor Pumping Current Trim Circuit Low", location: "Bank 1 Sensor 1" },
  { code: "P2628", description: "O2 Sensor Pumping Current Trim Circuit High", location: "Bank 1 Sensor 1" },
  { code: "P2629", description: "O2 Sensor Pumping Current Trim Circuit/Open", location: "Bank 2 Sensor 1" },
  { code: "P2630", description: "O2 Sensor Pumping Current Trim Circuit Low", location: "Bank 2 Sensor 1" },
  { code: "P2631", description: "O2 Sensor Pumping Current Trim Circuit High", location: "Bank 2 Sensor 1" },
  { code: "P2632", description: "Fuel Pump 'B' Control Circuit/Open" },
  { code: "P2633", description: "Fuel Pump 'B' Control Circuit Low" },
  { code: "P2634", description: "Fuel Pump 'B' Control Circuit High" },
  { code: "P2635", description: "Fuel Pump 'A' Low Flow / Performance" },
  { code: "P2636", description: "Fuel Pump 'B' Low Flow / Performance" },
  { code: "P2637", description: "Torque Management Feedback Signal 'A'" },
  { code: "P2638", description: "Torque Management Feedback Signal 'A' Range/Performance" },
  { code: "P2639", description: "Torque Management Feedback Signal 'A' Low" },
  { code: "P2640", description: "Torque Management Feedback Signal 'A' High" },
  { code: "P2641", description: "Torque Management Feedback Signal 'B'" },
  { code: "P2642", description: "Torque Management Feedback Signal 'B' Range/Performance" },
  { code: "P2643", description: "Torque Management Feedback Signal 'B' Low" },
  { code: "P2644", description: "Torque Management Feedback Signal 'B' High" },
  { code: "P2645", description: "'A' Rocker Arm Actuator Control Circuit/Open", location: "Bank 1" },
  { code: "P2646", description: "'A' Rocker Arm Actuator System Performance or Stuck Off", location: "Bank 1" },
  { code: "P2647", description: "'A' Rocker Arm Actuator System Stuck On", location: "Bank 1" },
  { code: "P2648", description: "'A' Rocker Arm Actuator Control Circuit Low", location: "Bank 1" },
  { code: "P2649", description: "'A' Rocker Arm Actuator Control Circuit High", location: "Bank 1" },
  { code: "P2650", description: "'B' Rocker Arm Actuator Control Circuit/Open", location: "Bank 1" },
  { code: "P2651", description: "'B' Rocker Arm Actuator System Performance or Stuck Off", location: "Bank 1" },
  { code: "P2652", description: "'B' Rocker Arm Actuator System Stuck On", location: "Bank 1" },
  { code: "P2653", description: "'B' Rocker Arm Actuator Control Circuit Low", location: "Bank 1" },
  { code: "P2654", description: "'B' Rocker Arm Actuator Control Circuit High", location: "Bank 1" },
  { code: "P2655", description: "'A' Rocker Arm Actuator Control Circuit/Open", location: "Bank 2" },
  { code: "P2656", description: "'A' Rocker Arm Actuator System Performance or Stuck Off", location: "Bank 2" },
  { code: "P2657", description: "'A' Rocker Arm Actuator System Stuck On", location: "Bank 2" },
  { code: "P2658", description: "'A' Rocker Arm Actuator Control Circuit Low", location: "Bank 2" },
  { code: "P2659", description: "'A' Rocker Arm Actuator Control Circuit High", location: "Bank 2" },
  { code: "P2660", description: "'B' Rocker Arm Actuator Control Circuit/Open", location: "Bank 2" },
  { code: "P2661", description: "'B' Rocker Arm Actuator System Performance or Stuck Off", location: "Bank 2" },
  { code: "P2662", description: "'B' Rocker Arm Actuator System Stuck On", location: "Bank 2" },
  { code: "P2663", description: "'B' Rocker Arm Actuator Control Circuit Low", location: "Bank 2" },
  { code: "P2664", description: "'B' Rocker Arm Actuator Control Circuit High", location: "Bank 2" },
  { code: "P2665", description: "Fuel Shutoff Valve 'B' Control Circuit/Open" },
  { code: "P2666", description: "Fuel Shutoff Valve 'B' Control Circuit Low" },
  { code: "P2667", description: "Fuel Shutoff Valve 'B' Control Circuit High" },
  { code: "P2668", description: "Fuel Mode Indicator Lamp Control Circuit" },
  { code: "P2669", description: "Actuator Supply Voltage 'B' Circuit/Open" },
  { code: "P2670", description: "Actuator Supply Voltage 'B' Circuit Low" },
  { code: "P2671", description: "Actuator Supply Voltage 'B' Circuit High" }
];