import { DTC } from '../../types/dtc.types';

export const P27XX_DTCS: DTC[] = [
  { code: "P2700", description: "Transmission Friction Element 'A' Apply Time Range/Performance" },
  { code: "P2701", description: "Transmission Friction Element 'B' Apply Time Range/Performance" },
  { code: "P2702", description: "Transmission Friction Element 'C' Apply Time Range/Performance" },
  { code: "P2703", description: "Transmission Friction Element 'D' Apply Time Range/Performance" },
  { code: "P2704", description: "Transmission Friction Element 'E' Apply Time Range/Performance" },
  { code: "P2705", description: "Transmission Friction Element 'F' Apply Time Range/Performance" },
  { code: "P2706", description: "Shift Solenoid 'F'" },
  { code: "P2707", description: "Shift Solenoid 'F' Performance or Stuck Off" },
  { code: "P2708", description: "Shift Solenoid 'F' Stuck On" },
  { code: "P2709", description: "Shift Solenoid 'F' Electrical" },
  { code: "P2710", description: "Shift Solenoid 'F' Intermittent" },
  { code: "P2711", description: "Unexpected Mechanical Gear Disengagement" },
  { code: "P2712", description: "Hydraulic Power Unit Leakage" },
  { code: "P2713", description: "Pressure Control Solenoid 'D'" },
  { code: "P2714", description: "Pressure Control Solenoid 'D' Performance or Stuck Off" },
  { code: "P2715", description: "Pressure Control Solenoid 'D' Stuck On" },
  { code: "P2716", description: "Pressure Control Solenoid 'D' Electrical" },
  { code: "P2717", description: "Pressure Control Solenoid 'D' Intermittent" },
  { code: "P2718", description: "Pressure Control Solenoid 'D' Control Circuit/Open" },
  { code: "P2719", description: "Pressure Control Solenoid 'D' Control Circuit Range/Performance" },
  { code: "P2720", description: "Pressure Control Solenoid 'D' Control Circuit Low" },
  { code: "P2721", description: "Pressure Control Solenoid 'D' Control Circuit High" },
  { code: "P2722", description: "Pressure Control Solenoid 'E'" },
  { code: "P2723", description: "Pressure Control Solenoid 'E' Performance or Stuck Off" },
  { code: "P2724", description: "Pressure Control Solenoid 'E' Stuck On" },
  { code: "P2725", description: "Pressure Control Solenoid 'E' Electrical" },
  { code: "P2726", description: "Pressure Control Solenoid 'E' Intermittent" },
  { code: "P2727", description: "Pressure Control Solenoid 'E' Control Circuit/Open" },
  { code: "P2728", description: "Pressure Control Solenoid 'E' Control Circuit Range/Performance" },
  { code: "P2729", description: "Pressure Control Solenoid 'E' Control Circuit Low" },
  { code: "P2730", description: "Pressure Control Solenoid 'E' Control Circuit High" },
  { code: "P2731", description: "Pressure Control Solenoid 'F'" },
  { code: "P2732", description: "Pressure Control Solenoid 'F' Performance or Stuck Off" },
  { code: "P2733", description: "Pressure Control Solenoid 'F' Stuck On" },
  { code: "P2734", description: "Pressure Control Solenoid 'F' Electrical" },
  { code: "P2735", description: "Pressure Control Solenoid 'F' Intermittent" },
  { code: "P2736", description: "Pressure Control Solenoid 'F' Control Circuit/Open" },
  { code: "P2737", description: "Pressure Control Solenoid 'F' Control Circuit Range/Performance" },
  { code: "P2738", description: "Pressure Control Solenoid 'F' Control Circuit Low" },
  { code: "P2739", description: "Pressure Control Solenoid 'F' Control Circuit High" },
  { code: "P2740", description: "Transmission Fluid Temperature Sensor 'B' Circuit" },
  { code: "P2741", description: "Transmission Fluid Temperature Sensor 'B' Circuit Range Performance" },
  { code: "P2742", description: "Transmission Fluid Temperature Sensor 'B' Circuit Low" },
  { code: "P2743", description: "Transmission Fluid Temperature Sensor 'B' Circuit High" },
  { code: "P2744", description: "Transmission Fluid Temperature Sensor 'B' Circuit Intermittent" },
  { code: "P2745", description: "Intermediate Shaft Speed Sensor 'B' Circuit" },
  { code: "P2746", description: "Intermediate Shaft Speed Sensor 'B' Circuit Range/Performance" },
  { code: "P2747", description: "Intermediate Shaft Speed Sensor 'B' Circuit No Signal" },
  { code: "P2748", description: "Intermediate Shaft Speed Sensor 'B' Circuit Intermittent" },
  { code: "P2749", description: "Intermediate Shaft Speed Sensor 'C' Circuit" },
  { code: "P2750", description: "Intermediate Shaft Speed Sensor 'C' Circuit Range/Performance" },
  { code: "P2751", description: "Intermediate Shaft Speed Sensor 'C' Circuit No Signal" },
  { code: "P2752", description: "Intermediate Shaft Speed Sensor 'C' Circuit Intermittent" },
  { code: "P2753", description: "Transmission Fluid Cooler Control Circuit Open" },
  { code: "P2754", description: "Transmission Fluid Cooler Control Circuit Low" },
  { code: "P2755", description: "Transmission Fluid Cooler Control Circuit High" },
  { code: "P2756", description: "Torque Converter Clutch Pressure Control Solenoid" },
  { code: "P2757", description: "Torque Converter Clutch Pressure Control Solenoid Control Circuit Performance or Stuck Off" },
  { code: "P2758", description: "Torque Converter Clutch Pressure Control Solenoid Control Circuit Stuck On" },
  { code: "P2759", description: "Torque Converter Clutch Pressure Control Solenoid Control Circuit Electrical" },
  { code: "P2760", description: "Torque Converter Clutch Pressure Control Solenoid Control Circuit Intermittent" },
  { code: "P2761", description: "Torque Converter Clutch Pressure Control Solenoid Control Circuit/Open" },
  { code: "P2762", description: "Torque Converter Clutch Pressure Control Solenoid Control Circuit Range/Performance" },
  { code: "P2763", description: "Torque Converter Clutch Pressure Control Solenoid Control Circuit High" },
  { code: "P2764", description: "Torque Converter Clutch Pressure Control Solenoid Control Circuit Low" },
  { code: "P2765", description: "Input/Turbine Speed Sensor 'B' Circuit" },
  { code: "P2766", description: "Input/Turbine Speed Sensor 'B' Circuit Range/Performance" },
  { code: "P2767", description: "Input/Turbine Speed Sensor 'B' Circuit No Signal" },
  { code: "P2768", description: "Input/Turbine Speed Sensor 'B' Circuit Intermittent" },
  { code: "P2769", description: "Torque Converter Clutch Circuit Low" },
  { code: "P2770", description: "Torque Converter Clutch Circuit High" },
  { code: "P2771", description: "Four Wheel Drive (4WD) Low Switch Circuit" },
  { code: "P2772", description: "Four Wheel Drive (4WD) Low Switch Circuit Range/Performance" },
  { code: "P2773", description: "Four Wheel Drive (4WD) Low Switch Circuit Low" },
  { code: "P2774", description: "Four Wheel Drive (4WD) Low Switch Circuit High" },
  { code: "P2775", description: "Upshift Switch Circuit Range/Performance" },
  { code: "P2776", description: "Upshift Switch Circuit Low" },
  { code: "P2777", description: "Upshift Switch Circuit High" },
  { code: "P2778", description: "Upshift Switch Circuit Intermittent/Erratic" },
  { code: "P2779", description: "Downshift Switch Circuit Range/Performance" },
  { code: "P2780", description: "Downshift Switch Circuit Low" },
  { code: "P2781", description: "Downshift Switch Circuit High" },
  { code: "P2782", description: "Downshift Switch Circuit Intermittent/Erratic" },
  { code: "P2783", description: "Torque Converter Temperature Too High" },
  { code: "P2784", description: "Input/Turbine Speed Sensor 'A'/'B' Correlation" },
  { code: "P2785", description: "Clutch Actuator Temperature Too High" },
  { code: "P2786", description: "Gear Shift Actuator Temperature Too High" },
  { code: "P2787", description: "Clutch Temperature Too High" },
  { code: "P2788", description: "Auto Shift Manual Adaptive Learning at Limit" },
  { code: "P2789", description: "Clutch Adaptive Learning at Limit" },
  { code: "P2790", description: "Gate Select Direction Circuit" },
  { code: "P2791", description: "Gate Select Direction Circuit Low" },
  { code: "P2792", description: "Gate Select Direction Circuit High" },
  { code: "P2793", description: "Gear Shift Direction Circuit" },
  { code: "P2794", description: "Gear Shift Direction Circuit Low" },
  { code: "P2795", description: "Gear Shift Direction Circuit High" }
];