import { DTC } from '../../types/dtc.types';

export const P34XX_DTCS: DTC[] = [
  { code: "P3400", description: "Cylinder Deactivation System", location: "Bank 1" },
  { code: "P3401", description: "Cylinder 1 Deactivation/Intake Valve Control Circuit/Open" },
  { code: "P3402", description: "Cylinder 1 Deactivation/Intake Valve Control Performance" },
  { code: "P3403", description: "Cylinder 1 Deactivation/Intake Valve Control Circuit Low" },
  { code: "P3404", description: "Cylinder 1 Deactivation/Intake Valve Control Circuit High" },
  { code: "P3405", description: "Cylinder 1 Exhaust Valve Control Circuit/Open" },
  { code: "P3406", description: "Cylinder 1 Exhaust Valve Control Performance" },
  { code: "P3407", description: "Cylinder 1 Exhaust Valve Control Circuit Low" },
  { code: "P3408", description: "Cylinder 1 Exhaust Valve Control Circuit High" },
  { code: "P3409", description: "Cylinder 2 Deactivation/Intake Valve Control Circuit/Open" },
  { code: "P3410", description: "Cylinder 2 Deactivation/Intake Valve Control Performance" },
  { code: "P3411", description: "Cylinder 2 Deactivation/Intake Valve Control Circuit Low" },
  { code: "P3412", description: "Cylinder 2 Deactivation/Intake Valve Control Circuit High" },
  { code: "P3413", description: "Cylinder 2 Exhaust Valve Control Circuit/Open" },
  { code: "P3414", description: "Cylinder 2 Exhaust Valve Control Performance" },
  { code: "P3415", description: "Cylinder 2 Exhaust Valve Control Circuit Low" },
  { code: "P3416", description: "Cylinder 2 Exhaust Valve Control Circuit High" },
  { code: "P3417", description: "Cylinder 3 Deactivation/Intake Valve Control Circuit/Open" },
  { code: "P3418", description: "Cylinder 3 Deactivation/Intake Valve Control Performance" },
  { code: "P3419", description: "Cylinder 3 Deactivation/Intake Valve Control Circuit Low" },
  { code: "P3420", description: "Cylinder 3 Deactivation/Intake Valve Control Circuit High" },
  { code: "P3421", description: "Cylinder 3 Exhaust Valve Control Circuit/Open" },
  { code: "P3422", description: "Cylinder 3 Exhaust Valve Control Performance" },
  { code: "P3423", description: "Cylinder 3 Exhaust Valve Control Circuit Low" },
  { code: "P3424", description: "Cylinder 3 Exhaust Valve Control Circuit High" },
  { code: "P3425", description: "Cylinder 4 Deactivation/Intake Valve Control Circuit/Open" },
  { code: "P3426", description: "Cylinder 4 Deactivation/Intake Valve Control Performance" },
  { code: "P3427", description: "Cylinder 4 Deactivation/Intake Valve Control Circuit Low" },
  { code: "P3428", description: "Cylinder 4 Deactivation/Intake Valve Control Circuit High" },
  { code: "P3429", description: "Cylinder 4 Exhaust Valve Control Circuit/Open" },
  { code: "P3430", description: "Cylinder 4 Exhaust Valve Control Performance" },
  { code: "P3431", description: "Cylinder 4 Exhaust Valve Control Circuit Low" },
  { code: "P3432", description: "Cylinder 4 Exhaust Valve Control Circuit High" },
  { code: "P3433", description: "Cylinder 5 Deactivation/Intake Valve Control Circuit/Open" },
  { code: "P3434", description: "Cylinder 5 Deactivation/Intake Valve Control Performance" },
  { code: "P3435", description: "Cylinder 5 Deactivation/Intake Valve Control Circuit Low" },
  { code: "P3436", description: "Cylinder 5 Deactivation/Intake Valve Control Circuit High" },
  { code: "P3437", description: "Cylinder 5 Exhaust Valve Control Circuit/Open" },
  { code: "P3438", description: "Cylinder 5 Exhaust Valve Control Performance" },
  { code: "P3439", description: "Cylinder 5 Exhaust Valve Control Circuit Low" },
  { code: "P3440", description: "Cylinder 5 Exhaust Valve Control Circuit High" },
  { code: "P3441", description: "Cylinder 6 Deactivation/Intake Valve Control Circuit/Open" },
  { code: "P3442", description: "Cylinder 6 Deactivation/Intake Valve Control Performance" },
  { code: "P3443", description: "Cylinder 6 Deactivation/Intake Valve Control Circuit Low" },
  { code: "P3444", description: "Cylinder 6 Deactivation/Intake Valve Control Circuit High" },
  { code: "P3445", description: "Cylinder 6 Exhaust Valve Control Circuit/Open" },
  { code: "P3446", description: "Cylinder 6 Exhaust Valve Control Performance" },
  { code: "P3447", description: "Cylinder 6 Exhaust Valve Control Circuit Low" },
  { code: "P3448", description: "Cylinder 6 Exhaust Valve Control Circuit High" },
  { code: "P3449", description: "Cylinder 7 Deactivation/Intake Valve Control Circuit/Open" },
  { code: "P3450", description: "Cylinder 7 Deactivation/Intake Valve Control Performance" },
  { code: "P3451", description: "Cylinder 7 Deactivation/Intake Valve Control Circuit Low" },
  { code: "P3452", description: "Cylinder 7 Deactivation/Intake Valve Control Circuit High" },
  { code: "P3453", description: "Cylinder 7 Exhaust Valve Control Circuit/Open" },
  { code: "P3454", description: "Cylinder 7 Exhaust Valve Control Performance" },
  { code: "P3455", description: "Cylinder 7 Exhaust Valve Control Circuit Low" },
  { code: "P3456", description: "Cylinder 7 Exhaust Valve Control Circuit High" },
  { code: "P3457", description: "Cylinder 8 Deactivation/Intake Valve Control Circuit/Open" },
  { code: "P3458", description: "Cylinder 8 Deactivation/Intake Valve Control Performance" },
  { code: "P3459", description: "Cylinder 8 Deactivation/Intake Valve Control Circuit Low" },
  { code: "P3460", description: "Cylinder 8 Deactivation/Intake Valve Control Circuit High" },
  { code: "P3461", description: "Cylinder 8 Exhaust Valve Control Circuit/Open" },
  { code: "P3462", description: "Cylinder 8 Exhaust Valve Control Performance" },
  { code: "P3463", description: "Cylinder 8 Exhaust Valve Control Circuit Low" },
  { code: "P3464", description: "Cylinder 8 Exhaust Valve Control Circuit High" },
  { code: "P3465", description: "Cylinder 9 Deactivation/Intake Valve Control Circuit/Open" },
  { code: "P3466", description: "Cylinder 9 Deactivation/Intake Valve Control Performance" },
  { code: "P3467", description: "Cylinder 9 Deactivation/Intake Valve Control Circuit Low" },
  { code: "P3468", description: "Cylinder 9 Deactivation/Intake Valve Control Circuit High" },
  { code: "P3469", description: "Cylinder 9 Exhaust Valve Control Circuit/Open" },
  { code: "P3470", description: "Cylinder 9 Exhaust Valve Control Performance" },
  { code: "P3471", description: "Cylinder 9 Exhaust Valve Control Circuit Low" },
  { code: "P3472", description: "Cylinder 9 Exhaust Valve Control Circuit High" },
  { code: "P3473", description: "Cylinder 10 Deactivation/Intake Valve Control Circuit/Open" },
  { code: "P3474", description: "Cylinder 10 Deactivation/Intake Valve Control Performance" },
  { code: "P3475", description: "Cylinder 10 Deactivation/Intake Valve Control Circuit Low" },
  { code: "P3476", description: "Cylinder 10 Deactivation/Intake Valve Control Circuit High" },
  { code: "P3477", description: "Cylinder 10 Exhaust Valve Control Circuit/Open" },
  { code: "P3478", description: "Cylinder 10 Exhaust Valve Control Performance" },
  { code: "P3479", description: "Cylinder 10 Exhaust Valve Control Circuit Low" },
  { code: "P3480", description: "Cylinder 10 Exhaust Valve Control Circuit High" },
  { code: "P3481", description: "Cylinder 11 Deactivation/Intake Valve Control Circuit/Open" },
  { code: "P3482", description: "Cylinder 11 Deactivation/Intake Valve Control Performance" },
  { code: "P3483", description: "Cylinder 11 Deactivation/Intake Valve Control Circuit Low" },
  { code: "P3484", description: "Cylinder 11 Deactivation/Intake Valve Control Circuit High" },
  { code: "P3485", description: "Cylinder 11 Exhaust Valve Control Circuit/Open" },
  { code: "P3486", description: "Cylinder 11 Exhaust Valve Control Performance" },
  { code: "P3487", description: "Cylinder 11 Exhaust Valve Control Circuit Low" },
  { code: "P3488", description: "Cylinder 11 Exhaust Valve Control Circuit High" },
  { code: "P3489", description: "Cylinder 12 Deactivation/Intake Valve Control Circuit/Open" },
  { code: "P3490", description: "Cylinder 12 Deactivation/Intake Valve Control Performance" },
  { code: "P3491", description: "Cylinder 12 Deactivation/Intake Valve Control Circuit Low" },
  { code: "P3492", description: "Cylinder 12 Deactivation/Intake Valve Control Circuit High" },
  { code: "P3493", description: "Cylinder 12 Exhaust Valve Control Circuit/Open" },
  { code: "P3494", description: "Cylinder 12 Exhaust Valve Control Performance" },
  { code: "P3495", description: "Cylinder 12 Exhaust Valve Control Circuit Low" },
  { code: "P3496", description: "Cylinder 12 Exhaust Valve Control Circuit High" },
  { code: "P3497", description: "Cylinder Deactivation System", location: "Bank 2" }
];