import { DTC } from '../../types/dtc.types';

export const U00XX_DTCS: DTC[] = [
  { code: "U0001", description: "High Speed CAN Communication Bus" },
  { code: "U0002", description: "High Speed CAN Communication Bus Performance" },
  { code: "U0003", description: "High Speed CAN Communication Bus (+) Open" },
  { code: "U0004", description: "High Speed CAN Communication Bus (+) Low" },
  { code: "U0005", description: "High Speed CAN Communication Bus (+) High" },
  { code: "U0006", description: "High Speed CAN Communication Bus (-) Open" },
  { code: "U0007", description: "High Speed CAN Communication Bus (-) Low" },
  { code: "U0008", description: "High Speed CAN Communication Bus (-) High" },
  { code: "U0009", description: "High Speed CAN Communication Bus (-) shorted to Bus (+)" },
  { code: "U0010", description: "Medium Speed CAN Communication Bus" },
  { code: "U0011", description: "Medium Speed CAN Communication Bus Performance" },
  { code: "U0012", description: "Medium Speed CAN Communication Bus (+) Open" },
  { code: "U0013", description: "Medium Speed CAN Communication Bus (+) Low" },
  { code: "U0014", description: "Medium Speed CAN Communication Bus (+) High" },
  { code: "U0015", description: "Medium Speed CAN Communication Bus (-) Open" },
  { code: "U0016", description: "Medium Speed CAN Communication Bus (-) Low" },
  { code: "U0017", description: "Medium Speed CAN Communication Bus (-) High" },
  { code: "U0018", description: "Medium Speed CAN Communication Bus (-) shorted to Bus (+)" },
  { code: "U0019", description: "Low Speed CAN Communication Bus" },
  { code: "U0020", description: "Low Speed CAN Communication Bus Performance" },
  { code: "U0021", description: "Low Speed CAN Communication Bus (+) Open" },
  { code: "U0022", description: "Low Speed CAN Communication Bus (+) Low" },
  { code: "U0023", description: "Low Speed CAN Communication Bus (+) High" },
  { code: "U0024", description: "Low Speed CAN Communication Bus (-) Open" },
  { code: "U0025", description: "Low Speed CAN Communication Bus (-) Low" },
  { code: "U0026", description: "Low Speed CAN Communication Bus (-) High" },
  { code: "U0027", description: "Low Speed CAN Communication Bus (-) shorted to Bus (+)" },
  { code: "U0028", description: "Vehicle Communication Bus A" },
  { code: "U0029", description: "Vehicle Communication Bus A Performance" },
  { code: "U0030", description: "Vehicle Communication Bus A (+) Open" },
  { code: "U0031", description: "Vehicle Communication Bus A (+) Low" },
  { code: "U0032", description: "Vehicle Communication Bus A (+) High" },
  { code: "U0033", description: "Vehicle Communication Bus A (-) Open" },
  { code: "U0034", description: "Vehicle Communication Bus A (-) Low" },
  { code: "U0035", description: "Vehicle Communication Bus A (-) High" },
  { code: "U0036", description: "Vehicle Communication Bus A (-) shorted to Bus A (+)" },
  { code: "U0037", description: "Vehicle Communication Bus B" },
  { code: "U0038", description: "Vehicle Communication Bus B Performance" },
  { code: "U0039", description: "Vehicle Communication Bus B (+) Open" },
  { code: "U0040", description: "Vehicle Communication Bus B (+) Low" },
  { code: "U0041", description: "Vehicle Communication Bus B (+) High" },
  { code: "U0042", description: "Vehicle Communication Bus B (-) Open" },
  { code: "U0043", description: "Vehicle Communication Bus B (-) Low" },
  { code: "U0044", description: "Vehicle Communication Bus B (-) High" },
  { code: "U0045", description: "Vehicle Communication Bus B (-) shorted to Bus B (+)" },
  { code: "U0046", description: "Vehicle Communication Bus C" },
  { code: "U0047", description: "Vehicle Communication Bus C Performance" },
  { code: "U0048", description: "Vehicle Communication Bus C (+) Open" },
  { code: "U0049", description: "Vehicle Communication Bus C (+) Low" },
  { code: "U0050", description: "Vehicle Communication Bus C (+) High" },
  { code: "U0051", description: "Vehicle Communication Bus C (-) Open" },
  { code: "U0052", description: "Vehicle Communication Bus C (-) Low" },
  { code: "U0053", description: "Vehicle Communication Bus C (-) High" },
  { code: "U0054", description: "Vehicle Communication Bus C (-) shorted to Bus C (+)" },
  { code: "U0055", description: "Vehicle Communication Bus D" },
  { code: "U0056", description: "Vehicle Communication Bus D Performance" },
  { code: "U0057", description: "Vehicle Communication Bus D (+) Open" },
  { code: "U0058", description: "Vehicle Communication Bus D (+) Low" },
  { code: "U0059", description: "Vehicle Communication Bus D (+) High" },
  { code: "U0060", description: "Vehicle Communication Bus D (-) Open" },
  { code: "U0061", description: "Vehicle Communication Bus D (-) Low" },
  { code: "U0062", description: "Vehicle Communication Bus D (-) High" },
  { code: "U0063", description: "Vehicle Communication Bus D (-) shorted to Bus D (+)" },
  { code: "U0064", description: "Vehicle Communication Bus E" },
  { code: "U0065", description: "Vehicle Communication Bus E Performance" },
  { code: "U0066", description: "Vehicle Communication Bus E (+) Open" },
  { code: "U0067", description: "Vehicle Communication Bus E (+) Low" },
  { code: "U0068", description: "Vehicle Communication Bus E (+) High" },
  { code: "U0069", description: "Vehicle Communication Bus E (-) Open" },
  { code: "U0070", description: "Vehicle Communication Bus E (-) Low" },
  { code: "U0071", description: "Vehicle Communication Bus E (-) High" },
  { code: "U0072", description: "Vehicle Communication Bus E (-) shorted to Bus E (+)" },
  { code: "U0073", description: "Control Module Communication Bus Off" }
];