import { DTC } from '../../types/dtc.types';

export const U01XX_DTCS: DTC[] = [
  { code: "U0100", description: "Lost Communication With ECM/PCM 'A'" },
  { code: "U0101", description: "Lost Communication With TCM" },
  { code: "U0102", description: "Lost Communication With Transfer Case Control Module" },
  { code: "U0103", description: "Lost Communication With Gear Shift Module" },
  { code: "U0104", description: "Lost Communication With Cruise Control Module" },
  { code: "U0105", description: "Lost Communication With Fuel Injector Control Module" },
  { code: "U0106", description: "Lost Communication With Glow Plug Control Module" },
  { code: "U0107", description: "Lost Communication With Throttle Actuator Control Module" },
  { code: "U0108", description: "Lost Communication With Alternative Fuel Control Module" },
  { code: "U0109", description: "Lost Communication With Fuel Pump Control Module" },
  { code: "U0110", description: "Lost Communication With Drive Motor Control Module" },
  { code: "U0111", description: "Lost Communication With Battery Energy Control Module 'A'" },
  { code: "U0112", description: "Lost Communication With Battery Energy Control Module 'B'" },
  { code: "U0113", description: "Lost Communication With Emissions Critical Control Information" },
  { code: "U0114", description: "Lost Communication With Four-Wheel Drive Clutch Control Module" },
  { code: "U0115", description: "Lost Communication With ECM/PCM 'B'" },
  { code: "U0121", description: "Lost Communication With Anti-Lock Brake System (ABS) Control Module" },
  { code: "U0122", description: "Lost Communication With Vehicle Dynamics Control Module" },
  { code: "U0123", description: "Lost Communication With Yaw Rate Sensor Module" },
  { code: "U0124", description: "Lost Communication With Lateral Acceleration Sensor Module" },
  { code: "U0125", description: "Lost Communication With Multi-axis Acceleration Sensor Module" },
  { code: "U0126", description: "Lost Communication With Steering Angle Sensor Module" },
  { code: "U0127", description: "Lost Communication With Tire Pressure Monitor Module" },
  { code: "U0128", description: "Lost Communication With Park Brake Control Module" },
  { code: "U0129", description: "Lost Communication With Brake System Control Module" },
  { code: "U0130", description: "Lost Communication With Steering Effort Control Module" },
  { code: "U0131", description: "Lost Communication With Power Steering Control Module" },
  { code: "U0132", description: "Lost Communication With Ride Level Control Module" },
  { code: "U0140", description: "Lost Communication With Body Control Module" },
  { code: "U0141", description: "Lost Communication With Body Control Module 'A'" },
  { code: "U0142", description: "Lost Communication With Body Control Module 'B'" },
  { code: "U0143", description: "Lost Communication With Body Control Module 'C'" },
  { code: "U0144", description: "Lost Communication With Body Control Module 'D'" },
  { code: "U0145", description: "Lost Communication With Body Control Module 'E'" },
  { code: "U0146", description: "Lost Communication With Gateway 'A'" },
  { code: "U0147", description: "Lost Communication With Gateway 'B'" },
  { code: "U0148", description: "Lost Communication With Gateway 'C'" },
  { code: "U0149", description: "Lost Communication With Gateway 'D'" },
  { code: "U0150", description: "Lost Communication With Gateway 'E'" },
  { code: "U0151", description: "Lost Communication With Restraints Control Module" },
  { code: "U0152", description: "Lost Communication With Side Restraints Control Module Left" },
  { code: "U0153", description: "Lost Communication With Side Restraints Control Module Right" },
  { code: "U0154", description: "Lost Communication With Restraints Occupant Sensing Control Module" },
  { code: "U0155", description: "Lost Communication With Instrument Panel Cluster (IPC) Control Module" },
  { code: "U0156", description: "Lost Communication With Information Center 'A'" },
  { code: "U0157", description: "Lost Communication With Information Center 'B'" },
  { code: "U0158", description: "Lost Communication With Head Up Display" },
  { code: "U0159", description: "Lost Communication With Parking Assist Control Module" },
  { code: "U0160", description: "Lost Communication With Audible Alert Control Module" },
  { code: "U0161", description: "Lost Communication With Compass Module" },
  { code: "U0162", description: "Lost Communication With Navigation Display Module" },
  { code: "U0163", description: "Lost Communication With Navigation Control Module" },
  { code: "U0164", description: "Lost Communication With HVAC Control Module" },
  { code: "U0165", description: "Lost Communication With HVAC Control Module Rear" },
  { code: "U0166", description: "Lost Communication With Auxiliary Heater Control Module" },
  { code: "U0167", description: "Lost Communication With Vehicle Immobilizer Control Module" },
  { code: "U0168", description: "Lost Communication With Vehicle Security Control Module" },
  { code: "U0169", description: "Lost Communication With Sunroof Control Module" },
  { code: "U0170", description: "Lost Communication With 'Restraints System Sensor A'" },
  { code: "U0171", description: "Lost Communication With 'Restraints System Sensor B'" },
  { code: "U0172", description: "Lost Communication With 'Restraints System Sensor C'" },
  { code: "U0173", description: "Lost Communication With 'Restraints System Sensor D'" },
  { code: "U0174", description: "Lost Communication With 'Restraints System Sensor E'" },
  { code: "U0175", description: "Lost Communication With 'Restraints System Sensor F'" },
  { code: "U0176", description: "Lost Communication With 'Restraints System Sensor G'" },
  { code: "U0177", description: "Lost Communication With 'Restraints System Sensor H'" },
  { code: "U0178", description: "Lost Communication With 'Restraints System Sensor I'" },
  { code: "U0179", description: "Lost Communication With 'Restraints System Sensor J'" },
  { code: "U0180", description: "Lost Communication With Automatic Lighting Control Module" },
  { code: "U0181", description: "Lost Communication With Headlamp Leveling Control Module" },
  { code: "U0182", description: "Lost Communication With Lighting Control Module Front" },
  { code: "U0183", description: "Lost Communication With Lighting Control Module Rear" },
  { code: "U0184", description: "Lost Communication With Radio" },
  { code: "U0185", description: "Lost Communication With Antenna Control Module" },
  { code: "U0186", description: "Lost Communication With Audio Amplifier" },
  { code: "U0187", description: "Lost Communication With Digital Disc Player/Changer Module 'A'" },
  { code: "U0188", description: "Lost Communication With Digital Disc Player/Changer Module 'B'" },
  { code: "U0189", description: "Lost Communication With Digital Disc Player/Changer Module 'C'" },
  { code: "U0190", description: "Lost Communication With Digital Disc Player/Changer Module 'D'" },
  { code: "U0191", description: "Lost Communication With Television" },
  { code: "U0192", description: "Lost Communication With Personal Computer" },
  { code: "U0193", description: "Lost Communication With Digital Audio Control Module A" },
  { code: "U0194", description: "Lost Communication With Digital Audio Control Module B" },
  { code: "U0195", description: "Lost Communication With Subscription Entertainment Receiver Module" },
  { code: "U0196", description: "Lost Communication With Rear Seat Entertainment Control Module" },
  { code: "U0197", description: "Lost Communication With Telephone Control Module" },
  { code: "U0198", description: "Lost Communication With Telematic Control Module" },
  { code: "U0199", description: "Lost Communication With Door Control Module A" }
];