import { DTC } from '../../types/dtc.types';

export const U02XX_DTCS: DTC[] = [
  { code: "U0200", description: "Lost Communication With Door Control Module B" },
  { code: "U0201", description: "Lost Communication With Door Control Module C" },
  { code: "U0202", description: "Lost Communication With Door Control Module D" },
  { code: "U0203", description: "Lost Communication With Door Control Module E" },
  { code: "U0204", description: "Lost Communication With Door Control Module F" },
  { code: "U0205", description: "Lost Communication With Door Control Module G" },
  { code: "U0206", description: "Lost Communication With Folding Top Control Module" },
  { code: "U0207", description: "Lost Communication With Moveable Roof Control Module" },
  { code: "U0208", description: "Lost Communication With Seat Control Module A" },
  { code: "U0209", description: "Lost Communication With Seat Control Module B" },
  { code: "U0210", description: "Lost Communication With Seat Control Module C" },
  { code: "U0211", description: "Lost Communication With Seat Control Module D" },
  { code: "U0212", description: "Lost Communication With Steering Column Control Module" },
  { code: "U0213", description: "Lost Communication With Mirror Control Module" },
  { code: "U0214", description: "Lost Communication With Remote Function Actuation" },
  { code: "U0215", description: "Lost Communication With Door Switch A" },
  { code: "U0216", description: "Lost Communication With Door Switch B" },
  { code: "U0217", description: "Lost Communication With Door Switch C" },
  { code: "U0218", description: "Lost Communication With Door Switch D" },
  { code: "U0219", description: "Lost Communication With Door Switch E" },
  { code: "U0220", description: "Lost Communication With Door Switch F" },
  { code: "U0221", description: "Lost Communication With Door Switch G" },
  { code: "U0222", description: "Lost Communication With Door Window Motor A" },
  { code: "U0223", description: "Lost Communication With Door Window Motor B" },
  { code: "U0224", description: "Lost Communication With Door Window Motor C" },
  { code: "U0225", description: "Lost Communication With Door Window Motor D" },
  { code: "U0226", description: "Lost Communication With Door Window Motor E" },
  { code: "U0227", description: "Lost Communication With Door Window Motor F" },
  { code: "U0228", description: "Lost Communication With Door Window Motor G" },
  { code: "U0229", description: "Lost Communication With Heated Steering Wheel Module" },
  { code: "U0230", description: "Lost Communication With Rear Gate Module" },
  { code: "U0231", description: "Lost Communication With Rain Sensing Module" },
  { code: "U0232", description: "Lost Communication With Side Obstacle Detection Control Module Left" },
  { code: "U0233", description: "Lost Communication With Side Obstacle Detection Control Module Right" },
  { code: "U0234", description: "Lost Communication With Convenience Recall Module" },
  { code: "U0235", description: "Lost Communication With Cruise Control Front Distance Range Sensor" }
];