import { DTC } from '../../types/dtc.types';

export const U03XX_DTCS: DTC[] = [
  { code: "U0300", description: "Internal Control Module Software Incompatibility" },
  { code: "U0301", description: "Software Incompatibility with Transmission Control Module" },
  { code: "U0302", description: "Software Incompatibility with ECM/PCM" },
  { code: "U0303", description: "Software Incompatibility with Transfer Case Control Module" },
  { code: "U0304", description: "Software Incompatibility with Gear Shift Control Module" },
  { code: "U0305", description: "Software Incompatibility with Cruise Control Module" },
  { code: "U0306", description: "Software Incompatibility with Fuel Injector Control Module" },
  { code: "U0307", description: "Software Incompatibility with Glow Plug Control Module" },
  { code: "U0308", description: "Software Incompatibility with Throttle Actuator Control Module" },
  { code: "U0309", description: "Software Incompatibility with Alternative Fuel Control Module" },
  { code: "U0310", description: "Software Incompatibility with Fuel Pump Control Module" },
  { code: "U0311", description: "Software Incompatibility with Drive Motor Control Module" },
  { code: "U0312", description: "Software Incompatibility with Battery Energy Control Module A" },
  { code: "U0313", description: "Software Incompatibility with Battery Energy Control Module B" },
  { code: "U0314", description: "Software Incompatibility with Four-Wheel Drive Clutch Control Module" },
  { code: "U0315", description: "Software Incompatibility with Anti-Lock Brake System Control Module" },
  { code: "U0316", description: "Software Incompatibility with Vehicle Dynamics Control Module" },
  { code: "U0317", description: "Software Incompatibility with Park Brake Control Module" },
  { code: "U0318", description: "Software Incompatibility with Brake System Control Module" },
  { code: "U0319", description: "Software Incompatibility with Steering Effort Control Module" },
  { code: "U0320", description: "Software Incompatibility with Power Steering Control Module" },
  { code: "U0321", description: "Software Incompatibility with Ride Level Control Module" },
  { code: "U0322", description: "Software Incompatibility with Body Control Module" },
  { code: "U0323", description: "Software Incompatibility with Instrument Panel Control Module" },
  { code: "U0324", description: "Software Incompatibility with HVAC Control Module" },
  { code: "U0325", description: "Software Incompatibility with Auxiliary Heater Control Module" },
  { code: "U0326", description: "Software Incompatibility with Vehicle Immobilizer Control Module" },
  { code: "U0327", description: "Software Incompatibility with Vehicle Security Control Module" },
  { code: "U0328", description: "Software Incompatibility with Steering Angle Sensor Module" },
  { code: "U0329", description: "Software Incompatibility with Steering Column Control Module" },
  { code: "U0330", description: "Software Incompatibility with Tire Pressure Monitor Module" },
  { code: "U0331", description: "Software Incompatibility with Body Control Module 'A'" }
];