import { DTC } from '../../types/dtc.types';

export const U04XX_DTCS: DTC[] = [
  { code: "U0400", description: "Invalid Data Received" },
  { code: "U0401", description: "Invalid Data Received From ECM/PCM" },
  { code: "U0402", description: "Invalid Data Received From Transmission Control Module" },
  { code: "U0403", description: "Invalid Data Received From Transfer Case Control Module" },
  { code: "U0404", description: "Invalid Data Received From Gear Shift Control Module" },
  { code: "U0405", description: "Invalid Data Received From Cruise Control Module" },
  { code: "U0406", description: "Invalid Data Received From Fuel Injector Control Module" },
  { code: "U0407", description: "Invalid Data Received From Glow Plug Control Module" },
  { code: "U0408", description: "Invalid Data Received From Throttle Actuator Control Module" },
  { code: "U0409", description: "Invalid Data Received From Alternative Fuel Control Module" },
  { code: "U0410", description: "Invalid Data Received From Fuel Pump Control Module" },
  { code: "U0411", description: "Invalid Data Received From Drive Motor Control Module" },
  { code: "U0412", description: "Invalid Data Received From Battery Energy Control Module A" },
  { code: "U0413", description: "Invalid Data Received From Battery Energy Control Module B" },
  { code: "U0414", description: "Invalid Data Received From Four-Wheel Drive Clutch Control Module" },
  { code: "U0415", description: "Invalid Data Received From Anti-Lock Brake System Control Module" },
  { code: "U0416", description: "Invalid Data Received From Vehicle Dynamics Control Module" },
  { code: "U0417", description: "Invalid Data Received From Park Brake Control Module" },
  { code: "U0418", description: "Invalid Data Received From Brake System Control Module" },
  { code: "U0419", description: "Invalid Data Received From Steering Effort Control Module" },
  { code: "U0420", description: "Invalid Data Received From Power Steering Control Module" },
  { code: "U0421", description: "Invalid Data Received From Ride Level Control Module" },
  { code: "U0422", description: "Invalid Data Received From Body Control Module" },
  { code: "U0423", description: "Invalid Data Received From Instrument Panel Control Module" },
  { code: "U0424", description: "Invalid Data Received From HVAC Control Module" },
  { code: "U0425", description: "Invalid Data Received From Auxiliary Heater Control Module" },
  { code: "U0426", description: "Invalid Data Received From Vehicle Immobilizer Control Module" },
  { code: "U0427", description: "Invalid Data Received From Vehicle Security Control Module" },
  { code: "U0428", description: "Invalid Data Received From Steering Angle Sensor Module" },
  { code: "U0429", description: "Invalid Data Received From Steering Column Control Module" },
  { code: "U0430", description: "Invalid Data Received From Tire Pressure Monitor Module" },
  { code: "U0431", description: "Invalid Data Received From Body Control Module 'A'" }
];