// components/DTCDetailsModal.tsx
import { Ionicons } from '@expo/vector-icons';
import * as Clipboard from 'expo-clipboard';
import * as FileSystem from 'expo-file-system';
import * as Sharing from 'expo-sharing';
import React, { useState } from 'react';
import {
    Alert,
    Linking,
    Modal,
    ScrollView,
    StyleSheet,
    Text,
    TouchableOpacity,
    View
} from 'react-native';

import { useTheme } from '../constants/ThemeContext';
import {
    getDTCCategory,
    getDTCCodeType,
    getDTCDefinition,
    getDTCDTCSystem,
    getDTCSeverity
} from '../services/DTCDatabase';
import { DTC } from '../types/dtc.types';

interface DTCDetailsModalProps {
  visible: boolean;
  dtc: DTC | null;
  onClose: () => void;
}

// Get urgency color and label
const getUrgencyInfo = (severity: string): { color: string; label: string; icon: string } => {
  switch(severity) {
    case 'critical':
      return { 
        color: '#FF3B30', 
        label: 'Critical - Fix Immediately',
        icon: 'warning'
      };
    case 'warning':
      return { 
        color: '#FF9500', 
        label: 'Warning - Should Be Addressed Soon',
        icon: 'alert'
      };
    case 'info':
      return { 
        color: '#34C759', 
        label: 'Informational - Monitor',
        icon: 'information-circle'
      };
    default:
      return { 
        color: '#8E8E93', 
        label: 'Unknown Severity',
        icon: 'help-circle'
      };
  }
};

// Get difficulty color
const getDifficultyColor = (difficulty: string): string => {
  switch(difficulty) {
    case 'Easy': return '#34C759';
    case 'Moderate': return '#FF9500';
    case 'Difficult': return '#FF3B30';
    default: return '#8E8E93';
  }
};

export const DTCDetailsModal: React.FC<DTCDetailsModalProps> = ({
  visible,
  dtc,
  onClose
}) => {
  const { colors } = useTheme();
  const [expandedSection, setExpandedSection] = useState<string | null>('symptoms');

  if (!dtc) return null;

  const fullDtcInfo = getDTCDefinition(dtc.code);
  const severity = getDTCSeverity(dtc.code);
  const category = getDTCCategory(dtc.code);
  const system = getDTCDTCSystem(dtc.code);
  const codeType = getDTCCodeType(dtc.code);
  const urgencyInfo = getUrgencyInfo(severity);
  const hasRepairInfo = fullDtcInfo.symptoms && fullDtcInfo.symptoms.length > 0;

  // Copy DTC to clipboard
  const copyToClipboard = async () => {
    await Clipboard.setStringAsync(dtc.code);
    Alert.alert('Copied!', 'DTC code copied to clipboard');
  };

  // Search on Google
  const searchOnline = () => {
    const query = encodeURIComponent(`${dtc.code} ${fullDtcInfo.description} diagnostic repair`);
    Linking.openURL(`https://www.google.com/search?q=${query}`);
  };

  // Search on YouTube
  const searchYouTube = () => {
    const query = encodeURIComponent(`${dtc.code} repair guide`);
    Linking.openURL(`https://m.youtube.com/results?search_query=${query}`);
  };

  // Generate and share report
  const shareReport = async () => {
    const report = `
DTC DIAGNOSTIC REPORT
${'='.repeat(30)}

Code: ${dtc.code}
Description: ${fullDtcInfo.description}
System: ${system}
Category: ${category}
Severity: ${severity.toUpperCase()}
Code Type: ${codeType}
${dtc.location ? `Location: ${dtc.location}` : ''}

${fullDtcInfo.symptoms ? `
SYMPTOMS:
${fullDtcInfo.symptoms.map(s => '• ' + s).join('\n')}
` : ''}

${fullDtcInfo.commonCauses ? `
COMMON CAUSES:
${fullDtcInfo.commonCauses.map(c => '• ' + c).join('\n')}
` : ''}

${fullDtcInfo.repairEstimate ? `
REPAIR ESTIMATE:
• Time: ${fullDtcInfo.repairEstimate.time}
• Cost: ${fullDtcInfo.repairEstimate.cost}
• Difficulty: ${fullDtcInfo.repairEstimate.difficulty}
• Parts Needed: ${fullDtcInfo.repairEstimate.parts.join(', ')}
` : ''}

${fullDtcInfo.priority ? `
PRIORITY: ${fullDtcInfo.priority}
` : ''}

Generated by AI Car Scanner
    `;

    const fileUri = FileSystem.documentDirectory + `dtc_${dtc.code}_report.txt`;
    await FileSystem.writeAsStringAsync(fileUri, report);
    
    if (await Sharing.isAvailableAsync()) {
      await Sharing.shareAsync(fileUri);
    }
  };

  const toggleSection = (section: string) => {
    setExpandedSection(expandedSection === section ? null : section);
  };

  return (
    <Modal
      visible={visible}
      transparent
      animationType="slide"
      onRequestClose={onClose}
    >
      <View style={styles.modalOverlay}>
        <View style={[styles.modalContent, { backgroundColor: colors.screenBg }]}>
          {/* Header */}
          <View style={styles.modalHeader}>
            <View style={styles.headerLeft}>
              <TouchableOpacity onPress={onClose}>
                <Ionicons name="close" size={24} color={colors.textPrimary} />
              </TouchableOpacity>
              <Text style={[styles.modalTitle, { color: colors.textPrimary }]}>
                DTC Details
              </Text>
            </View>
            <View style={styles.headerActions}>
              <TouchableOpacity onPress={copyToClipboard} style={styles.headerButton}>
                <Ionicons name="copy-outline" size={22} color={colors.textSecondary} />
              </TouchableOpacity>
              <TouchableOpacity onPress={shareReport} style={styles.headerButton}>
                <Ionicons name="share-outline" size={22} color={colors.textSecondary} />
              </TouchableOpacity>
            </View>
          </View>

          <ScrollView style={styles.modalBody} showsVerticalScrollIndicator={false}>
            {/* Code and Severity */}
            <View style={[styles.codeSection, { borderColor: urgencyInfo.color }]}>
              <Text style={[styles.dtcCode, { color: colors.textPrimary }]}>
                {dtc.code}
              </Text>
              <View style={[styles.urgencyBadge, { backgroundColor: urgencyInfo.color }]}>
                <Ionicons name={urgencyInfo.icon as any} size={12} color="#FFFFFF" />
                <Text style={styles.urgencyText}>{severity.toUpperCase()}</Text>
              </View>
            </View>

            {/* Quick Action Buttons */}
            <View style={styles.quickActions}>
              <TouchableOpacity 
                style={[styles.quickAction, { backgroundColor: colors.cardBg }]}
                onPress={searchOnline}
              >
                <Ionicons name="logo-google" size={20} color={colors.borderPrimary} />
                <Text style={[styles.quickActionText, { color: colors.textPrimary }]}>Search</Text>
              </TouchableOpacity>
              
              <TouchableOpacity 
                style={[styles.quickAction, { backgroundColor: colors.cardBg }]}
                onPress={searchYouTube}
              >
                <Ionicons name="logo-youtube" size={20} color="#FF0000" />
                <Text style={[styles.quickActionText, { color: colors.textPrimary }]}>Video</Text>
              </TouchableOpacity>
              
              <TouchableOpacity 
                style={[styles.quickAction, { backgroundColor: colors.cardBg }]}
                onPress={shareReport}
              >
                <Ionicons name="document-text" size={20} color={colors.accentGreen} />
                <Text style={[styles.quickActionText, { color: colors.textPrimary }]}>Report</Text>
              </TouchableOpacity>
            </View>

            {/* Description */}
            <View style={styles.section}>
              <Text style={[styles.sectionLabel, { color: colors.textSecondary }]}>
                Description
              </Text>
              <Text style={[styles.description, { color: colors.textPrimary }]}>
                {fullDtcInfo.description}
              </Text>
            </View>

            {/* Priority Alert */}
            {fullDtcInfo.priority && (
              <View style={[styles.priorityCard, { 
                backgroundColor: urgencyInfo.color + '20',
                borderColor: urgencyInfo.color 
              }]}>
                <Ionicons name="flag" size={20} color={urgencyInfo.color} />
                <Text style={[styles.priorityText, { color: colors.textPrimary }]}>
                  {fullDtcInfo.priority}
                </Text>
              </View>
            )}

            {/* System Information Grid */}
            <View style={styles.infoGrid}>
              <View style={[styles.infoCard, { backgroundColor: colors.cardBg }]}>
                <Ionicons name="hardware-chip" size={16} color={colors.borderPrimary} />
                <Text style={[styles.infoLabel, { color: colors.textSecondary }]}>System</Text>
                <Text style={[styles.infoValue, { color: colors.textPrimary }]}>{system}</Text>
              </View>

              <View style={[styles.infoCard, { backgroundColor: colors.cardBg }]}>
                <Ionicons name="folder" size={16} color={colors.borderPrimary} />
                <Text style={[styles.infoLabel, { color: colors.textSecondary }]}>Category</Text>
                <Text style={[styles.infoValue, { color: colors.textPrimary }]}>{category}</Text>
              </View>

              <View style={[styles.infoCard, { backgroundColor: colors.cardBg }]}>
                <Ionicons name="barcode" size={16} color={colors.borderPrimary} />
                <Text style={[styles.infoLabel, { color: colors.textSecondary }]}>Code Type</Text>
                <Text style={[styles.infoValue, { color: colors.textPrimary }]}>{codeType}</Text>
              </View>
            </View>

            {/* Location */}
            {dtc.location && (
              <View style={[styles.locationCard, { backgroundColor: colors.cardBg }]}>
                <Ionicons name="location" size={16} color={colors.borderPrimary} />
                <Text style={[styles.locationText, { color: colors.textPrimary }]}>
                  {dtc.location}
                </Text>
              </View>
            )}

            {/* Repair Information - Only show if available */}
            {hasRepairInfo && (
              <>
                {/* Symptoms Section */}
                <View style={styles.expandableSection}>
                  <TouchableOpacity 
                    style={styles.sectionHeader}
                    onPress={() => toggleSection('symptoms')}
                  >
                    <View style={styles.sectionHeaderLeft}>
                      <Ionicons name="pulse" size={20} color={colors.borderPrimary} />
                      <Text style={[styles.sectionHeaderText, { color: colors.textPrimary }]}>
                        Symptoms
                      </Text>
                    </View>
                    <Ionicons 
                      name={expandedSection === 'symptoms' ? 'chevron-up' : 'chevron-down'} 
                      size={20} 
                      color={colors.textSecondary} 
                    />
                  </TouchableOpacity>
                  
                  {expandedSection === 'symptoms' && (
                    <View style={styles.sectionContent}>
                      {fullDtcInfo.symptoms?.map((symptom, index) => (
                        <View key={index} style={styles.bulletItem}>
                          <View style={[styles.bullet, { backgroundColor: colors.borderPrimary }]} />
                          <Text style={[styles.bulletText, { color: colors.textSecondary }]}>
                            {symptom}
                          </Text>
                        </View>
                      ))}
                    </View>
                  )}
                </View>

                {/* Common Causes Section */}
                <View style={styles.expandableSection}>
                  <TouchableOpacity 
                    style={styles.sectionHeader}
                    onPress={() => toggleSection('causes')}
                  >
                    <View style={styles.sectionHeaderLeft}>
                      <Ionicons name="construct" size={20} color={colors.borderPrimary} />
                      <Text style={[styles.sectionHeaderText, { color: colors.textPrimary }]}>
                        Common Causes
                      </Text>
                    </View>
                    <Ionicons 
                      name={expandedSection === 'causes' ? 'chevron-up' : 'chevron-down'} 
                      size={20} 
                      color={colors.textSecondary} 
                    />
                  </TouchableOpacity>
                  
                  {expandedSection === 'causes' && (
                    <View style={styles.sectionContent}>
                      {fullDtcInfo.commonCauses?.map((cause, index) => (
                        <View key={index} style={styles.bulletItem}>
                          <Ionicons name="warning" size={14} color={colors.accentAmber} />
                          <Text style={[styles.bulletText, { color: colors.textSecondary }]}>
                            {cause}
                          </Text>
                        </View>
                      ))}
                    </View>
                  )}
                </View>

                {/* Diagnostic Steps Section */}
                <View style={styles.expandableSection}>
                  <TouchableOpacity 
                    style={styles.sectionHeader}
                    onPress={() => toggleSection('diagnostic')}
                  >
                    <View style={styles.sectionHeaderLeft}>
                      <Ionicons name="search" size={20} color={colors.borderPrimary} />
                      <Text style={[styles.sectionHeaderText, { color: colors.textPrimary }]}>
                        Diagnostic Steps
                      </Text>
                    </View>
                    <Ionicons 
                      name={expandedSection === 'diagnostic' ? 'chevron-up' : 'chevron-down'} 
                      size={20} 
                      color={colors.textSecondary} 
                    />
                  </TouchableOpacity>
                  
                  {expandedSection === 'diagnostic' && (
                    <View style={styles.sectionContent}>
                      {fullDtcInfo.diagnosticSteps?.map((step, index) => (
                        <View key={index} style={styles.stepItem}>
                          <View style={[styles.stepNumber, { backgroundColor: colors.borderPrimary }]}>
                            <Text style={styles.stepNumberText}>{index + 1}</Text>
                          </View>
                          <Text style={[styles.stepText, { color: colors.textSecondary }]}>
                            {step}
                          </Text>
                        </View>
                      ))}
                    </View>
                  )}
                </View>

                {/* Repair Estimate */}
                {fullDtcInfo.repairEstimate && (
                  <View style={styles.repairSection}>
                    <Text style={[styles.repairTitle, { color: colors.borderPrimary }]}>
                      REPAIR ESTIMATE
                    </Text>
                    
                    <View style={styles.repairGrid}>
                      <View style={[styles.repairCard, { backgroundColor: colors.cardBg }]}>
                        <Ionicons name="time" size={24} color={colors.borderPrimary} />
                        <Text style={[styles.repairCardLabel, { color: colors.textSecondary }]}>
                          Time
                        </Text>
                        <Text style={[styles.repairCardValue, { color: colors.textPrimary }]}>
                          {fullDtcInfo.repairEstimate.time}
                        </Text>
                      </View>

                      <View style={[styles.repairCard, { backgroundColor: colors.cardBg }]}>
                        <Ionicons name="cash" size={24} color={colors.borderPrimary} />
                        <Text style={[styles.repairCardLabel, { color: colors.textSecondary }]}>
                          Cost
                        </Text>
                        <Text style={[styles.repairCardValue, { color: colors.textPrimary }]}>
                          {fullDtcInfo.repairEstimate.cost}
                        </Text>
                      </View>

                      <View style={[styles.repairCard, { backgroundColor: colors.cardBg }]}>
                        <Ionicons name="speedometer" size={24} color={colors.borderPrimary} />
                        <Text style={[styles.repairCardLabel, { color: colors.textSecondary }]}>
                          Difficulty
                        </Text>
                        <Text style={[
                          styles.repairCardValue, 
                          { color: getDifficultyColor(fullDtcInfo.repairEstimate.difficulty) }
                        ]}>
                          {fullDtcInfo.repairEstimate.difficulty}
                        </Text>
                      </View>
                    </View>

                    {/* Parts Needed */}
                    <View style={[styles.partsCard, { backgroundColor: colors.cardBg }]}>
                      <Text style={[styles.partsTitle, { color: colors.textPrimary }]}>
                        Parts Needed:
                      </Text>
                      {fullDtcInfo.repairEstimate.parts.map((part, index) => (
                        <View key={index} style={styles.partItem}>
                          <Ionicons name="checkbox" size={14} color={colors.accentGreen} />
                          <Text style={[styles.partText, { color: colors.textSecondary }]}>
                            {part}
                          </Text>
                        </View>
                      ))}
                    </View>

                    {/* DIY Possibility */}
                    <View style={[styles.diyCard, { backgroundColor: colors.cardBg }]}>
                      <View style={styles.diyRow}>
                        <Ionicons name="construct" size={20} color={colors.accentGreen} />
                        <Text style={[styles.diyLabel, { color: colors.textPrimary }]}>
                          DIY Possibility:
                        </Text>
                      </View>
                      <Text style={[styles.diyText, { color: colors.textSecondary }]}>
                        {fullDtcInfo.diyPossibility}
                      </Text>
                      <Text style={[styles.professionalText, { color: colors.accentAmber }]}>
                        {fullDtcInfo.professionalRequired}
                      </Text>
                    </View>
                  </View>
                )}
              </>
            )}

            {/* No Repair Info Available */}
            {!hasRepairInfo && (
              <View style={[styles.noInfoCard, { backgroundColor: colors.cardBg }]}>
                <Ionicons name="information-circle" size={48} color={colors.textSecondary} />
                <Text style={[styles.noInfoTitle, { color: colors.textPrimary }]}>
                  Limited Information Available
                </Text>
                <Text style={[styles.noInfoText, { color: colors.textSecondary }]}>
                  This is a manufacturer-specific code. Please consult your vehicle's service manual or search online for more details.
                </Text>
                <TouchableOpacity 
                  style={[styles.searchButton, { borderColor: colors.borderPrimary }]}
                  onPress={searchOnline}
                >
                  <Ionicons name="search" size={16} color={colors.borderPrimary} />
                  <Text style={[styles.searchButtonText, { color: colors.borderPrimary }]}>
                    Search Online
                  </Text>
                </TouchableOpacity>
              </View>
            )}
          </ScrollView>

          {/* Footer */}
          <View style={styles.modalFooter}>
            <TouchableOpacity
              style={[styles.closeButton, { borderColor: colors.borderPrimary }]}
              onPress={onClose}
            >
              <Text style={[styles.closeButtonText, { color: colors.borderPrimary }]}>
                CLOSE
              </Text>
            </TouchableOpacity>
          </View>
        </View>
      </View>
    </Modal>
  );
};

const styles = StyleSheet.create({
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.7)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  modalContent: {
    width: '94%',
    maxHeight: '90%',
    borderRadius: 24,
    overflow: 'hidden',
    elevation: 5,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.25,
    shadowRadius: 4,
  },
  modalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: 16,
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(108, 92, 231, 0.25)',
  },
  headerLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  modalTitle: {
    fontSize: 18,
    fontWeight: 'bold',
  },
  headerActions: {
    flexDirection: 'row',
    gap: 16,
  },
  headerButton: {
    padding: 4,
  },
  modalBody: {
    padding: 16,
    maxHeight: '80%',
  },
  codeSection: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    borderWidth: 2,
    borderRadius: 12,
    padding: 16,
    marginBottom: 12,
  },
  dtcCode: {
    fontSize: 28,
    fontWeight: 'bold',
    fontFamily: 'monospace',
  },
  urgencyBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 16,
    gap: 4,
  },
  urgencyText: {
    color: '#FFFFFF',
    fontSize: 11,
    fontWeight: 'bold',
  },
  quickActions: {
    flexDirection: 'row',
    gap: 8,
    marginBottom: 16,
  },
  quickAction: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    padding: 10,
    borderRadius: 8,
    gap: 6,
  },
  quickActionText: {
    fontSize: 12,
    fontWeight: '500',
  },
  section: {
    marginBottom: 16,
  },
  sectionLabel: {
    fontSize: 11,
    marginBottom: 4,
    textTransform: 'uppercase',
    letterSpacing: 0.5,
  },
  description: {
    fontSize: 15,
    lineHeight: 20,
  },
  priorityCard: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: 12,
    borderRadius: 8,
    marginBottom: 16,
    gap: 8,
    borderWidth: 1,
  },
  priorityText: {
    fontSize: 13,
    flex: 1,
    lineHeight: 18,
  },
  infoGrid: {
    flexDirection: 'row',
    gap: 8,
    marginBottom: 12,
  },
  infoCard: {
    flex: 1,
    alignItems: 'center',
    padding: 10,
    borderRadius: 8,
    gap: 2,
  },
  infoLabel: {
    fontSize: 9,
    marginTop: 2,
  },
  infoValue: {
    fontSize: 11,
    fontWeight: '600',
    textAlign: 'center',
  },
  locationCard: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: 12,
    borderRadius: 8,
    marginBottom: 16,
    gap: 8,
  },
  locationText: {
    fontSize: 13,
    flex: 1,
  },
  expandableSection: {
    marginBottom: 8,
    borderRadius: 8,
    overflow: 'hidden',
  },
  sectionHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: 12,
    backgroundColor: 'rgba(108, 92, 231, 0.1)',
  },
  sectionHeaderLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  sectionHeaderText: {
    fontSize: 14,
    fontWeight: '600',
  },
  sectionContent: {
    padding: 12,
    gap: 8,
  },
  bulletItem: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  bullet: {
    width: 4,
    height: 4,
    borderRadius: 2,
  },
  bulletText: {
    fontSize: 13,
    flex: 1,
    lineHeight: 18,
  },
  stepItem: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    marginBottom: 8,
  },
  stepNumber: {
    width: 22,
    height: 22,
    borderRadius: 11,
    alignItems: 'center',
    justifyContent: 'center',
  },
  stepNumberText: {
    color: '#FFFFFF',
    fontSize: 12,
    fontWeight: 'bold',
  },
  stepText: {
    fontSize: 13,
    flex: 1,
    lineHeight: 18,
  },
  repairSection: {
    marginTop: 16,
    marginBottom: 8,
  },
  repairTitle: {
    fontSize: 13,
    fontWeight: '700',
    marginBottom: 12,
    letterSpacing: 0.5,
  },
  repairGrid: {
    flexDirection: 'row',
    gap: 8,
    marginBottom: 8,
  },
  repairCard: {
    flex: 1,
    alignItems: 'center',
    padding: 12,
    borderRadius: 8,
    gap: 4,
  },
  repairCardLabel: {
    fontSize: 10,
  },
  repairCardValue: {
    fontSize: 12,
    fontWeight: '600',
  },
  partsCard: {
    padding: 12,
    borderRadius: 8,
    marginBottom: 8,
    gap: 6,
  },
  partsTitle: {
    fontSize: 13,
    fontWeight: '600',
    marginBottom: 4,
  },
  partItem: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  partText: {
    fontSize: 12,
    flex: 1,
  },
  diyCard: {
    padding: 12,
    borderRadius: 8,
    marginBottom: 8,
    gap: 8,
  },
  diyRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  diyLabel: {
    fontSize: 13,
    fontWeight: '600',
  },
  diyText: {
    fontSize: 13,
    lineHeight: 18,
    marginLeft: 28,
  },
  professionalText: {
    fontSize: 12,
    marginLeft: 28,
  },
  noInfoCard: {
    alignItems: 'center',
    padding: 24,
    borderRadius: 12,
    marginVertical: 16,
    gap: 12,
  },
  noInfoTitle: {
    fontSize: 16,
    fontWeight: '600',
    textAlign: 'center',
  },
  noInfoText: {
    fontSize: 13,
    textAlign: 'center',
    lineHeight: 18,
    marginBottom: 8,
  },
  searchButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    padding: 10,
    borderRadius: 8,
    borderWidth: 1,
    gap: 6,
    width: '100%',
  },
  searchButtonText: {
    fontSize: 13,
    fontWeight: '500',
  },
  modalFooter: {
    padding: 16,
    borderTopWidth: 1,
    borderTopColor: 'rgba(108, 92, 231, 0.25)',
  },
  closeButton: {
    borderWidth: 2,
    borderRadius: 30,
    padding: 14,
    alignItems: 'center',
  },
  closeButtonText: {
    fontSize: 16,
    fontWeight: 'bold',
    textTransform: 'uppercase',
    letterSpacing: 1,
  },
});